### ISSUE TITLE
Bindvars are not working

### ISSUE THREAD

**Issue by yandooo** [ibmdb/go_ibm_db#102]
- os Version: macos
- cli-driver Version: go_ibm_db@v0.3.0 and whatever it downloads
- Db2 Server Version: 11
- go Version: 1.13
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env

</pre></details>

It looks like the library does not handle properly bindvars

```
import (
	""github.com/jmoiron/sqlx""
)

readSchemaVersionQuery = "SELECT curr_version from schema_version where db_name=?"
...
var version string
err := sqlx.db.Get(&version, readSchemaVersionQuery, database)
```

the error coming back

```
error: SQLExecDirectW: {07001} [IBM][CLI Driver] CLI0100E  Wrong number of parameters. SQLSTATE=07001
```

I tried to `fmt.Sprintf` string bind value and I can confirm that it works fine. I also tried different sqlx/sql queries and getting the same error back. So the only way to work around this issue is to go through all the queries and `fmt.Sprintf` it before passing to the driver. That's basically a lot of work.

**Comment by akhilravuri1** [comment]
Hi @yandooo 

I haven't used github.com/jmoiron/sqlx package and our driver is based on database/sql package.

If you provide a sample program that reproduces the issue would be helpful.
If you can provide another sample using the database/sql package would be great.


Thanks,
Akhil.

**Comment by akhilravuri1** [comment]
Hi @yandooo 

But from the error, I see you are using db.Get() which might me db.Query() but our driver is changed a bit.

Please create a statement handle and use it to send the data. (st.Query()).

please check the issue number #91 

Thanks,
Akhil

**Comment by yandooo** [comment]
@akhilravuri1 actually sqlx is basically containing all the methods from database/sql. So it should work. Checking your issue...

**Comment by akhilravuri1** [comment]
Please replace your db.Get() like this...
```
stmt, err := db.Preparex(`SELECT * FROM place WHERE telcode=?`)
var p Place
err = stmt.Get(&p, 852)
```
-Akhil

**Comment by yandooo** [comment]
@akhilravuri1 well. It also means I have to close stmt manually. It looks like x2 more work than just running `fmt.Sprintf`

**Comment by akhilravuri1** [comment]
Yes, you need to close the statement as you close the connection.
But if you are using the same sql somewhere you can just use the created statement which takes less time when compared to db.Get().

-Akhil

**Comment by yandooo** [comment]
@akhilravuri1 thanks.
