### ISSUE TITLE
Release 0.3.0 Wrong Number of Parameters Error on Query

### ISSUE THREAD

**Issue by dandandy** [ibmdb/go_ibm_db#104]
- os Version: Buster Linux docker image
- cli-driver Version: 0.3.0
- Db2 Server Version: Informix 12.10.FC9DE
- go Version: 1.14.7
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/db/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/db/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build506887941=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

When we upgraded to release 0.3.0, SQL queries which were working in release 0.2.0 started failing with `SQLExecDirectW: {07001} [IBM][CLI Driver] CLI0100E  Wrong number of parameters. SQLSTATE=07001`.
I believe this is because the new Query function introduced in release 0.3.0 is not substituting the query arguments into the SQL query. 

Steps to Reproduce:

1. First create a table and insert dummy data into the table: 
`CREATE TABLE test(case INT, name VARCHAR(255)); INSERT INTO test (case, name) VALUES (1, "test-a")`

2. Use sqlx to query the test table
```
        import (	
            _ "github.com/ibmdb/go_ibm_db" 
           "github.com/jmoiron/sqlx"
        )
	type test struct {
		Case int
		Name string
	}
        func main() {
            db, err := sqlx.Open(common.InformixDRDADriver, fmt.Sprintf("HOSTNAME=%s;PORT=%s;DATABASE=%s;UID=%s;PWD=%s", "host", "port", "db", "user", "password"))
	    where := "test-a"
	    var testA test
	    err := db.Get(&testA, `SELECT * FROM test WHERE name=?`, where)
            fmt.Println(testA, err)
        }

```

**Comment by akhilravuri1** [comment]
Please check #91 issue..

Thanks,
Akil

**Comment by dandandy** [comment]
Thank you
