### ISSUE TITLE
New version does not work for parameterized queries

### ISSUE THREAD

**Issue by alexcocia** [ibmdb/go_ibm_db#105]
We recently updated to new version 0.3.0, and existing queries are no longer working.

Query like: `SELECT * FROM dummy_table WHERE cod_1 = ? AND cod_2 = ? AND cod_3 = '24'`

Provides a **CLI0100E Wrong number of parameters. SQLSTATE=07001**

I've been debugging a bit, and seen that provided args are not used in https://github.com/ibmdb/go_ibm_db/blob/6d3b2e8acd84b85fba599aa27246921a9b5482d2/conn.go#L50

Using DB2Driver 11.5

Any idea with that?

**Comment by akhilravuri1** [comment]
Please see the #91 issue.

Thanks,
Akhil
