### ISSUE TITLE
Can not build package on AIX.

### ISSUE THREAD

**Issue by zhangyunbo1994** [ibmdb/go_ibm_db#107]
- os Version: AIX 7.2
- cli-driver Version: 0.3
- Db2 Server Version: v0.3.0
- go Version: go version go1.14.2 aix/ppc64
<details><summary><code>go env</code> Output:</summary><br><pre>

$ go env
GO111MODULE=""
GOARCH="ppc64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="ppc64"
GOHOSTOS="aix"
GOINSECURE=""
GONOPROXY="github.xxx.com/*"
GONOSUMDB="github.xxx.com/*"
GOOS="aix"
GOPATH="/root/go"
GOPRIVATE="github.xxx.com/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/freeware/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/freeware/lib/golang/pkg/tool/aix_ppc64"
GCCGO="gccgo"
GOPPC64="power8"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/go/src/job-scheduler/go.mod"
CGO_CFLAGS="-I/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -maix64 -pthread -mcmodel=large -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build078309884=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

Steps to Reproduce:

1. I download clidiver, and place to /root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver 
Actually, we should run `go run setup.go` in `/root/go/src/github.com/ibmdb/go_ibm_db/installer` folder, but I found setup.go have some issue for support AIX. So I download clidiver manaually.
2. 
+ export DB2HOME=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
+ export CGO_CFLAGS=-I/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include
+ export CGO_LDFLAGS=-L/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
+ export LD_LIBRARY_PATH=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

3. run `env CGO_ENABLED=1 GOOS=aix GOARCH=ppc64 go build -o <packagename>`
4. error:
```
# github.com/ibmdb/go_ibm_db/api
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:14:9: undefined: SQLSMALLINT
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:15:9: undefined: SQLUSMALLINT
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:16:9: undefined: SQLUSMALLINT
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:20:12: undefined: SQLSMALLINT
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:21:12: undefined: SQLUSMALLINT
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:22:12: undefined: SQLUSMALLINT
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:23:12: undefined: SQLUSMALLINT
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:24:12: undefined: SQLUSMALLINT
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:25:12: undefined: SQLUSMALLINT
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:26:12: undefined: SQLUINTEGER
/root/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/api/api.go:26:12: too many errors
```

**Comment by akhilravuri1** [comment]
Hi @zhangyunbo1994 

Are you using the latest code? because 2 days back I have added six support see #96 

How did you install the go lang? Did you build it using source code?

Thanks,
Akhil

**Comment by zhangyunbo1994** [comment]
Hi @akhilravuri1 

Yes, I can make sure we use the latest code. 

<details><summary><code>git show master</code> Output:</summary><br><pre>
root@leganes /root/go/src/github.com/ibmdb/go_ibm_db # git show master
commit 8c50dcf7da898a1c2ccadcdacb0488e44052f3fd (HEAD -> master, origin/master, origin/HEAD)
Merge: 6d3b2e8 ae3f801
Author: Akhil Ravuri <rakhil@rocketsoftware.com>
Date:   Mon Sep 7 12:13:15 2020 +0530

    Merge pull request #96 from rahul-s-s/master

    AIX support for go_ibm_db
</pre></details>

I use `yum install go` to install golang, should I using golang source code to install go on AIX?

Thanks,
Yunbo

**Comment by zhangyunbo1994** [comment]
Oh, my go application can build successfully now, I do the following:
change go_ibm_db version in go.mod file:
	`github.com/ibmdb/go_ibm_db v0.3.0`
to :
	`github.com/ibmdb/go_ibm_db v0.3.1-0.20200907064315-8c50dcf7da89`
go build can passed.
Many thanks! @akhilravuri1

**Comment by zhangyunbo1994** [comment]
btw: 
I also found AIX not support `tar -xzvf xxx.tgz `
If you want to unzip xxx.tgz file, you should 
1. `gunzip xxx.tgz`
2. xxx.tgz will change to xxx.tar
3. `tar -xvf xxx.tar`

So, we should add aix_untar function to support AIX platform. I will help to open a PR to fix this issue.

**Comment by akhilravuri1** [comment]
Okay..thanks @zhangyunbo1994 

I will test the pull request and I will merge it.

-Akhil
