### ISSUE TITLE
Issue when building in powershell api.go undefined sqlsmallint...

### ISSUE THREAD

**Issue by MICGe** [ibmdb/go_ibm_db#109]
Hello, I am trying to build in powershell using : $env:GOOS = "linux"; $Env:GOARCH = "amd64"; go build

but i keep getting error:
# github.com/ibmdb/go_ibm_db/api
..\..\..\pkg\mod\github.com\ibmdb\go_ibm_db@v0.2.0\api\api.go:14:9: undefined: SQLSMALLINT
..\..\..\pkg\mod\github.com\ibmdb\go_ibm_db@v0.2.0\api\api.go:15:9: undefined: SQLUSMALLINT
..\..\..\pkg\mod\github.com\ibmdb\go_ibm_db@v0.2.0\api\api.go:16:9: undefined: SQLUSMALLINT

my version : github.com/ibmdb/go_ibm_db v0.3.0 // indirect
go 1.13

This is causing issue for project.Any fix?

**Comment by akhilravuri1** [comment]
Hi @MICGe 

Are you planning to build a Linux binary on windows?

Did you set all the env variables?

Please run go env and paste the output here.

Thanks,
Akhil

**Comment by MICGe** [comment]
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\MICGUPTA\AppData\Local\go-build
set GOENV=C:\Users\MICGUPTA\AppData\Roaming\go\env
set GOEXE=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=github.cms.gov,github.cms.gov/MEPS
set GONOSUMDB=github.cms.gov/meps
set GOOS=linux
set GOPATH=C:\Users\MICGUPTA\go
set GOPRIVATE=github.cms.gov,github.cms.gov/MEPS
set GOPROXY=direct
set GOROOT=c:\go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\MICGUPTA\go\src\projects\marx-dev-dod-update\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Temp\go-build931283626=/tmp/go-build -gno-record-gcc-switches

i changed cgo_enabled to 1 here and it get this error now : exec: "gcc": executable file not found in %PATH%

**Comment by MICGe** [comment]
Trying to build so i can insert into lambda using db2

**Comment by akhilravuri1** [comment]
If you enable cgo you need gcc to compile c code.

**Comment by akhilravuri1** [comment]
Hi @MICGe 

This error looks like not related to go driver..but I will try to reproduce.

As of understanding on windows, you are trying to build a Linux binary right?

Thanks,
Akhil

**Comment by MICGe** [comment]
Thats correct, right now its making it into a windows exe  even if i do it in gitbash

**Comment by bimalkjha** [comment]
@MICGe Are you still facing this issue or able to resolve and move on? Please update. Thanks.

**Comment by Shah-Aayush** [comment]
I was able to resolve the issue by installing gcc (`apt install gcc`)
---
I was getting this error : 
`ibmdb/go_ibm_db/api/api.go:14:9: undefined: SQLSMALLINT`
