### ISSUE TITLE
No support for untarring symlinks

### ISSUE THREAD

**Issue by smuda** [ibmdb/go_ibm_db#11]
There seems to be in the current macos64_odbc_cli.tar.gz file:

- clidriver/lib/libDB2xml4c.58.0.dylib
- clidriver/lib/libDB2xml4c.58.dylib

Untarring the symlinks are not supported by setup.go.

This creates a warning during running the setup.go installation:
```
john$ go run setup.go 
darwin
macos64_odbc_cli.tar.gz
Downloading...
download successful
Creating directory : clidriver/

... (lot of files untarred) ...

Creating directory : clidriver/lib/icc/
Untarring : clidriver/lib/libdb2.dylib
Untarring : clidriver/lib/libdb2clixml4c.dylib
Unable to untar type : 2 in file clidriver/lib/libDB2xml4c.58.0.dylib
Unable to untar type : 2 in file clidriver/lib/libDB2xml4c.58.dylib

... (lot of files untarred) ...
```

**Comment by akhilravuri1** [comment]
Hi smuda

I have fixed the issue. Can you pull the latest code from the master branch and verify the fix.

Thanks.

**Comment by smuda** [comment]
@akhilravuri1 That works nicely, thank you!

Looking at the setup.go file, when an unknown platform is detected, a message is printed and then tries to download a file which doesn't have a name ("cliFileName"). Adding a return statement would handle that case. 

```
} else {
    fmt.Println("not a known platform")
    return
}
```

Since an unknown platform don't know the filename and therefor cannot download the file, there is now no platform that uses anything else then i=1 or i=2, so perhaps deleting the Untaring function would be a good thing?

That would also effectively handle my pull request #10.

**Comment by akhilravuri1** [comment]
Hi @smuda

1) Good catch, I will change the code for the unknown platform.

2) I am trying to improve untaring function so that it will untar any type of files. As an instant fix, I have used os command to untar the file.

Thanks.
