### ISSUE TITLE
Dose go_ibm_db support query Chinese char?

### ISSUE THREAD

**Issue by zhangyunbo1994** [ibmdb/go_ibm_db#112]
- os Version: MacOS 10.15
- cli-driver Version: Maybe latest
- Db2 Server Version: 11.1
- go Version: 1.13.15

Steps to Reproduce:

1. Use example2.go to do testing for query Chinese characters: https://github.com/ibmdb/go_ibm_db#example2go-
2. Do following changes in example2.go file. Just insert some Chinese characters into SAMPLE table.
```
func insert(db *sql.DB) error{
    st, err:=db.Prepare("Insert into SAMPLE(ID,NAME,LOCATION,POSITION) values('3242','中文','hyd','manager')")
    if err != nil{
        return err
    }
    st.Query()
    return nil
}
```
3. I got following output (Lost NAME data.):
![image](https://user-images.githubusercontent.com/44389598/94420803-439df380-01b7-11eb-87c6-9935d2d4490d.png)

Seems all functions can be execute successfully but **_execquery_** function not.
So I think go_ibm_db does not support query Chinese characters, right? 

Many thanks!

**Comment by akhilravuri1** [comment]
Hi, 
I am able to reproduce it.

I will try to fix it.

Thanks,
Akhil

**Comment by zhangyunbo1994** [comment]
Hello @akhilravuri1 
This bug is very urgent in our product, may I ask this issue when can be fixed? Also I can provide some help. Many thanks!
