### ISSUE TITLE
How should I set to connect to the database with different authentication types

### ISSUE THREAD

**Issue by WTaoGitHub** [ibmdb/go_ibm_db#115]
I can connect to a Db2 server which dbm cfg parameter "AUTHENTICATION" is "SERVER", with the example code.

` con:="HOSTNAME=host;DATABASE=name;PORT=number;UID=username;PWD=password"
`
Now I am trying with different authentication types to connect to the db2 server.  we can see there have several authentication types
CLIENT; 
SERVER; 
SERVER_ENCRYPT; 
DATA_ENCRYPT; 
DATA_ENCRYPT_CMP; 
KERBEROS; 
GSSPLUGIN; 

https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.admin.config.doc/doc/r0000294.html

So I wonder does the db2 go CLI driver support all these authentication types or parts of them.
And If the driver supports any of the authentication types, what should I set for connections.

Best wishes, thank you.

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

Just add the authentication types to the connection string.

Example:-
```go
conn :="database=DB;hostname=1.1.1.1;port=500;Authentication=GSSPLUGIN;protocol=TCPIP;accesstoken=abc"

or

con:="DATABASE=DB;HOSTNAME=1.1.1.1;PORT=501;PROTOCOL=TCPIP;SECURITY=SSL;APIKEY=YX_MRi"

```

**Comment by WTaoGitHub** [comment]
@akhilravuri1 
 I try to make a connection with the SECURITY=SSL and SSLServerCertificate=/tmp/myCert.pem options, that can work.
Do we have any options for indicating a Keystore or trust store location which keeps the server certificates?

As I know, we can indicate 3 properties to try to connect the database with the JDBC driver, with SSL connection.
1 sslConnection=true
2 sslTrustStoreLocation=/tmp/myTrustStore.jks
3 sslTrustStorePassword=password
Does the db2 go CLI driver have the same or similar options we can try to use.

Thank you.

**Comment by bimalkjha** [comment]
@WTaoGitHub To use the other authentication types as you posted like SERVER, you can use it in connection string using AUTHENTICATION keyword. You can add "AUTHENTICATION=SERVER_ENCRYPT" in connection string to use this authentication types. Same for other types as per the documentation link that you shared.

Regarding, other SSL related keywords, JDBC keywords do not work for go driver. You can use corresponding ODBC/CLI keywords in connection string and it works using Go driver too.
If you have GSKit installed, then you can create keystoredb and specify it using SSLClientKeyStoreDB keyword in connection string. That means, your connection string should be like: `"Database=sampledb; Protocol=tcpip; Hostname= myhost; Servicename=50001; 
Security=ssl; SSLClientKeystoredb=/home/test1/keystore/clientstore.kdb;
SSLClientKeystash=/home/test1/keystore/clientstore.sth;"`
You should follow this doc page to configure client side SSL fo rall non-Java drivers including Go driver: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.admin.sec.doc/doc/t0053518.html

If you have certificate file, installing GSKit and creating KeystoreDB manually for Go driver and other non-Java clients is not required. You can use only SSL and SSLServerCertificate keywords in connection string. The clidriver, internally creates KeyStoreDB in memory and add certificate file to it before attempting connection. So, using `SSL and SSLServerCertificate` keywords in Go connection string is sufficient for SSL connection. Thanks.
