### ISSUE TITLE
Column type DECIMAL data error

### ISSUE THREAD

**Issue by travelliu** [ibmdb/go_ibm_db#116]
The table has a DECIMAL column, and there is an error in the query data

```
select * from mtk1.test;

COL1
--------------------------------
 9999999999999999999999999999.99
         99999999999999999999.00
    9999999999999999999999999.00

  3 record(s) selected.
```
go test

```
	t.Run("DECIMAL", func(t *testing.T) {
		/*
		CREATE TABLE MTK1.test(col1 DECIMAL(30,2));
		INSERT INTO MTK1.test(col1) VALUES (9999999999999999999999999999.99);
		INSERT INTO MTK1.test(col1) VALUES (99999999999999999999);
		INSERT INTO MTK1.test(col1) VALUES (9999999999999999999999999);
		COMMIT;
		 */
		err := m.ConnectDatabase(ctx) // connect database 
		if err != nil {
			t.Error(err)
		}
		rows,err := m.DB.Query("SELECT col1 FROM MTK1.test")
		if err != nil {
			t.Error(err)
		}
		for rows.Next() {
			var f float64
			if err := rows.Scan(&f); err != nil {
				t.Error(err)
			}
			fmt.Println(f)
		}
		if err := rows.Err();err != nil {
			t.Error(err)
		}
	})
```
```
=== RUN   Test_DB2_Sequence
--- PASS: Test_DB2_Sequence (0.06s)
=== RUN   Test_DB2_Sequence/DECIMAL
1e+28   <> 9999999999999999999999999999.99
1e+20
1.0000000000000003e+25
    --- PASS: Test_DB2_Sequence/DECIMAL (0.06s)
PASS
```

- os Version: macOS Catalina 10.15.7 19H2 x86_64 
- cli-driver Version:v11.5
- Db2 Server Version: DB2 v11.5.4.0
- go Version: go version go1.13.15 darwin/amd64
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/travel/Library/Caches/go-build"
GOENV="/Users/travel/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/travel/Documents/Code/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/Cellar/go@1.13/1.13.15/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.13/1.13.15/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/travel/Documents/Code/Enmotech/cloudAssistant/mtk/go.mod"
CGO_CFLAGS="-I/Users/travel/Oracle_tools/db2client/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/Users/travel/Oracle_tools/db2client/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k1/vqmqkz_s4gg5c0775rlv4g000000gn/T/go-build390576298=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

Steps to Reproduce:

1. create table
```
CREATE TABLE MTK1.test(col1 DECIMAL(30,2));
		INSERT INTO MTK1.test(col1) VALUES (9999999999999999999999999999.99);
		INSERT INTO MTK1.test(col1) VALUES (99999999999999999999);
		INSERT INTO MTK1.test(col1) VALUES (9999999999999999999999999);
		COMMIT;
```
2. go test

**Comment by akhilravuri1** [comment]
Hi @travelliu 

I am able to reproduce the issue.

But if we use fmt.Printf("%f", f) it prints in the value.

But, I was surprised to see the output. 

Just declare a variable with float64 and assign one of your values to it and print it. you will see it.

I am doing the research go handles it.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @travelliu 

This is because the value is exceeding the float64 size.

Need to make a change that decimal value will be returned as a string since float cannot handle such big values.

I will fix this and push the code so that can access the decimal value by storing it in a string.

Thanks,
Akhil
