### ISSUE TITLE
how to set Unicode & characterEncoding when create connection ?

### ISSUE THREAD

**Issue by bjwyun** [ibmdb/go_ibm_db#119]
Does there's a way to add params in ``sql.Open("go_ibm_db", conn)`` to set Unicode & characterEncoding ? faced Chinese garbled code error.

**Comment by akhilravuri1** [comment]
Hi @bjwyun 

Just add the parameter in the connection string itself.
For example:- (I am planning to add query timeout Parameter)

```
con:="DATABASE=DB;HOSTNAME=localhost;PORT=50001;PROTOCOL=TCPIP;UID=uid;PWD=pwd!;QueryTimeout=0"
```
For a complete list of parameters please check the link in the readme after example1.

Thanks,
Akhil

**Comment by bjwyun** [comment]
@akhilravuri1 Do you have any suggestions about Encoding error ？    such as the value in db2 is ``合约`` but what we get is ``\u001a\u001a``

**Comment by akhilravuri1** [comment]
If possible please give me a sample program that reproduces the issue.
And give me your database territory with which you are connecting.

Thanks,
Akhil

**Comment by bjwyun** [comment]
Fixed ,as I'm in Docker container ENV, everyone who face this problem please try to add 
```
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
```
in dockerfile
