### ISSUE TITLE
Spurious output from ColumnTypes function

### ISSUE THREAD

**Issue by axelniedenhoff** [ibmdb/go_ibm_db#120]
When I call the ColumnTypes function on an db/sql.Rows object, I get the column types listed on standard output as a side effect, which interferes with the output from my program itself. I believe the culprit is this line:

https://github.com/ibmdb/go_ibm_db/blob/7939fe644850f79e32774481e3cf6adb05b617e0/rows.go#L51

This is probably some debug output that can be removed…

**Comment by akhilravuri1** [comment]
Yes...Sorry for the trouble.
Will remove it.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Remove the print line and pushed it.
Please pull the latest code.

Thanks,
Akhil

**Comment by axelniedenhoff** [comment]
Thank you! The problem is fixed.
