### ISSUE TITLE
setup.go is missing from /go/src/github.com/ibmdb/go_ibm_db/installer

### ISSUE THREAD

**Issue by Chekuru-Ravi** [ibmdb/go_ibm_db#123]
- os Version: using golang:latest in docker
- cli-driver Version: v0.3.0 and v0.2.0
- Db2 Server Version: db2 on ibm cloud
- go Version: golang:latest
<details>
               While building golang docker image with go_ibm_db, until today (16-02-2021) it was working fine, on (17-02-2021) when we start building images for our code changes we are getting this error that setup.go is missing
</details>

Steps to Reproduce:

STEP 3: RUN go get -d github.com/ibmdb/go_ibm_db@v0.2.0
go: downloading github.com/ibmdb/go_ibm_db v0.2.0
STEP 4: WORKDIR /go/src/github.com/ibmdb/go_ibm_db/installer
STEP 5: RUN go run setup.go
stat setup.go: no such file or directory

or

STEP 3: RUN go get -d github.com/ibmdb/go_ibm_db
go: downloading github.com/ibmdb/go_ibm_db v0.3.0
STEP 4: WORKDIR /go/src/github.com/ibmdb/go_ibm_db/installer
STEP 5: RUN go run setup.go
stat setup.go: no such file or directory

**Comment by akhilravuri1** [comment]
Hi @Chekuru-Ravi 

No changes are done recently.
Is it possible to share the docker file or sample docker file which reproduces the issue?

Thanks,
Akhil

**Comment by Chekuru-Ravi** [comment]
FROM golang:latest
RUN apt-get update -y && apt-get install libxml2 -y
RUN go get -d github.com/ibmdb/go_ibm_db
WORKDIR /go/src/github.com/ibmdb/go_ibm_db/installer
RUN go run setup.go
ENV DB2HOME=/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ENV CGO_CFLAGS=-I$DB2HOME/include
ENV CGO_LDFLAGS=-L$DB2HOME/lib
ENV LD_LIBRARY_PATH=/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
WORKDIR /
#ENTRYPOINT ["/bin/bash"]

**Comment by akhilravuri1** [comment]
Hi @Chekuru-Ravi 

I will try to reproduce it but from the file, I can say that this can be an issue ```WORKDIR /go/src/github.com/ibmdb/go_ibm_db/installer```

If you pass any value it will not return an error so we need to find out whether this is the right path or not.

Thanks,
Akhil

**Comment by Chekuru-Ravi** [comment]
ok more thing we found is when we use golang:latest from today its giving us (bin, pkg and src) folders.
so the setup.go file is not in src folder but it got moved to pkg folder. 

WORKDIR /go/src/github.com/ibmdb/go_ibm_db/installer (we have taken this step from this github wiki page)

**Comment by akhilravuri1** [comment]
Hi @Chekuru-Ravi 

I am able to reproduce the issue.
yesterday golang 1.16 was released which is triggering that error.
so please install 1.15 or change your Docker file to /home/rakhil/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer
this path.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @Chekuru-Ravi 

Please use this Dockerfile to run with 1.15 or lower...
```
FROM golang:1.15
RUN apt-get update -y && apt-get install libxml2 -y
RUN go get -d github.com/ibmdb/go_ibm_db
WORKDIR /go/src/github.com/ibmdb/go_ibm_db/installer
RUN go run setup.go
ENV DB2HOME=/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ENV CGO_CFLAGS=-I$DB2HOME/include
ENV CGO_LDFLAGS=-L$DB2HOME/lib
ENV LD_LIBRARY_PATH=/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
```
For the latest please give me 5 mins.

Thanks,
Akhil

**Comment by Chekuru-Ravi** [comment]
@akhilravuri1 : Yes we did that and it is working.  thank you (I will wait for your latest version thing)

**Comment by akhilravuri1** [comment]
Hi @Chekuru-Ravi 

Now Go has completely moved to Modules from this version. 
So the updated file will be 
```
FROM golang:latest
RUN apt-get update -y && apt-get install libxml2 -y
RUN go get -d github.com/ibmdb/go_ibm_db
WORKDIR /go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer
RUN go run setup.go
ENV DB2HOME=/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer/clidriver
ENV CGO_CFLAGS=-I$DB2HOME/include
ENV CGO_LDFLAGS=-L$DB2HOME/lib
ENV LD_LIBRARY_PATH=/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer/clidriver/lib
```

If possible I will try to make the same code workable with lower versions.

Thanks,
Akhil

**Comment by Chekuru-Ravi** [comment]
@akhilravuri1 : we have similar thing in mind, but had doughts, as the version of go_ibm_db changes then the path has to be changed. So will there be any better approach.

**Comment by akhilravuri1** [comment]
Hi @Chekuru-Ravi 

No need to change the path. The path will be the same.
You just need to change the in go.mod file.
Once Go is moved to the modules this means there is no global thing like GOPATH.
Please take a look at this https://blog.golang.org/using-go-modules

If you want to use the older way you have to use this env ``` export GO111MODULE="auto" ``` which will make your go version work like the older one.
But I don't know when they will remove this option.

Thanks,
Akhil
