### ISSUE TITLE
encounter error while running programs on windows 10

### ISSUE THREAD

**Issue by WTaoGitHub** [ibmdb/go_ibm_db#124]
Hi, I encountered an error while running the program on Windows 10.
`SQLDriverConnect: {HY000} [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004
`
The program tries to create a connection to a database and then executes a query.
The same code runs successfully on a server of Windows Server 2012.

- os Version: Windows 10
- cli-driver Version: v0.3.0
- Db2 Server Version: 10.5.6 and 11.5
- go Version: 1.16
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\dmc\wtaobj\GO\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\dmc\wtaobj\GO
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\dmc\wtaobj\GO
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\dmc\wtaobj\GO\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\dmc\wtaobj\workSpace\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build637168441=/tmp/go-build -gno-record-gcc-switches
</pre></details>

please help to give some advice, thank you.

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

Both are 64 bit?
please run db2level in the cmd and paste the output.

Thanks,
Akhil

**Comment by WTaoGitHub** [comment]
Hi Akhil，

Windows 10
```
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11055" with level identifier "0606010F".
Informational tokens are "DB2 v11.5.5000.1587", "s2011011400",
"DYN2011011400WIN64", and Fix Pack "0".
Product is installed at
"C:\dmc\wtaobj\GO\pkg\mod\github.com\ibmdb\go_ibm_db@v0.3.0\installer\clidriver
" with DB2 Copy Name "IBM Data Server Driver For ODBC and CLI".
```


Windows Server 2012
```
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11054" with level identifier "0605010F".
Informational tokens are "DB2 v11.5.4000.1449", "s2006161200",
"DYN2006161200WIN64", and Fix Pack "0".
Product is installed at
"C:\Users\Administrator\Downloads\ntx64_odbc_cli\clidriver" with DB2 Copy Name
"IBM Data Server Driver For ODBC and CLI".
```

**Comment by WTaoGitHub** [comment]
Hi Akhil,

On the server of Windows 10, I tried to change the driver to the one the server of Windows Server 2012 is using but still has the error.

C:\dmc\wtaobj\workSpace>db2level
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11054" with level identifier "0605010F".
Informational tokens are "DB2 v11.5.4000.1449", "s2006161200",
"DYN2006161200WIN64", and Fix Pack "0".
Product is installed at
"C:\dmc\ibm-datamgmtconsole\addons\job-scheduler\clidriver" with DB2 Copy Name
"IBM Data Server Driver For ODBC and CLI".


C:\dmc\wtaobj\workSpace>go run .
SQLDriverConnect: {HY000} [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

It can also be due to an ownership issue.
If the server is installed in that system please run the below command:-
1. log in as instance owner and execute db2start/db2 connect to tsmdb1, the command finished successful,
2. db2 "select service_level from sysIBMADM.ENV_INST_INFO"
If you receive an error, paste it here.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

Please Add C:\dmc\wtaobj\GO\pkg\mod\github.com\ibmdb\go_ibm_db@v0.3.0\installer\clidriver\bin\amd64.VC12.CRT to your PATH variable and run it again.

Thanks,
Akhil

**Comment by WTaoGitHub** [comment]
> Hi @WTaoGitHub
> 
> Please Add C:\dmc\wtaobj\GO\pkg\mod\github.com\ibmdb\go_ibm_db@v0.3.0\installer\clidriver\bin\amd64.VC12.CRT to your PATH variable and run it again.
> 
> Thanks,
> Akhil

Hi Akhil，
That works in my case. 
Do you think it is a defect? Actually, I tested this case on some other servers, Windows 10 and Linux.
Only one server of Windows 10 has this problem.

Thanks for your help

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

I think in some new versions these DLLs are missing.  So it is causing the error.
Is your system 10th gen?

Thanks,
Akhil

**Comment by WTaoGitHub** [comment]
Hi Akhil,  
My VM is Intel Core. But from the output of go env. it says "GOARCH=amd64", is that anything incorrect.
![image](https://user-images.githubusercontent.com/20013162/108589272-9d869c00-7398-11eb-9b32-356e22d62507.png)

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

That is not the problem. One is architecture and the other is a processor. Intel processors can have AMD architecture.

Thanks,
Akhil

**Comment by WTaoGitHub** [comment]
Hi @akhilravuri1 
Is there any plan to fix this issue?

Thank you.

**Comment by WTaoGitHub** [comment]
Hi @akhilravuri1 
Is that also a problem on an Intel architecture server,
Do we need to set the icc64 folder to the path?
Thank you

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

For now please set this path or copy the two DLLs in amd64.VC12.CRT to the clidriver/bin.(Copy it don't cut and paste)
We are analyzing the issue of why these DLLs are missing in the latest windows 10 versions.

Thanks,
Akhil

**Comment by WTaoGitHub** [comment]
@akhilravuri1 
OK, it's great, Thanks for your helps.
