### ISSUE TITLE
Why we don't need to specify the Authentication keyword to connect to a SERVER_ENCRYPT authentication database.

### ISSUE THREAD

**Issue by WTaoGitHub** [ibmdb/go_ibm_db#125]
Hi, I encounter a very strange case while connecting to a database with the CLI driver.
I set up the DB2 server to applying `AUTHENTICATION=SERVER_ENCTYPT.
```
db2 get dbm cfg |grep AUTHENTICATION
Database manager authentication        (AUTHENTICATION) = SERVER_ENCRYPT
```
Case 1 
Using a connectionString contains "Authentication=SERVER", the connection fails. It makes sense.
``` 
HOSTNAME=127.0.0.1;DATABASE=sample;PORT=50001;UID=test;PWD=123456;Authentication=SERVER;SECURITY=SSL;
```

Case 2 
Using "Authentication=SERVER_ENCRYPT", the connection successes. 
``` 
HOSTNAME=127.0.0.1;DATABASE=sample;PORT=50001;UID=test;PWD=123456;Authentication=SERVER_ENCRYPT;SECURITY=SSL;
```

Case 3 
If I don't specify the Authentication keyword, the connection still successes.
``` 
HOSTNAME=127.0.0.1;DATABASE=sample;PORT=50001;UID=test;PWD=123456;SECURITY=SSL;
```

My question is in case 3, why the connection is successful? Is that a feature of the CLI driver to handle the difference of the Db2 server configurations (AUTHENTICATION) = SERVER_ENCRYPT and (AUTHENTICATION) = SERVER

**Comment by akhilravuri1** [comment]
If you don't pass anything clidriver default authentication is server_encrypt.

So your connection string in 3rd case is similar to case 2 under the clidriver level

Thanks,
Akhil

**Comment by WTaoGitHub** [comment]
Hi @akhilravuri1, I did a new test.

I set up the DB2 server to applying **AUTHENTICATION=SERVER**
```
db2 get dbm cfg |grep AUTHENTICATION
Database manager authentication        (AUTHENTICATION) = SERVER
```
Case 4 
Using a connectionString contains "Authentication=SERVER", the connection successes.
``` 
HOSTNAME=127.0.0.1;DATABASE=sample;PORT=50001;UID=test;PWD=123456;Authentication=SERVER;SECURITY=SSL;
```
Case 5 
Using "Authentication=SERVER_ENCRYPT", the connection fails. 
``` 
HOSTNAME=127.0.0.1;DATABASE=sample;PORT=50001;UID=test;PWD=123456;Authentication=SERVER_ENCRYPT;SECURITY=SSL;
```
Case 6 
If I don't specify the Authentication keyword, the connection successes.
``` 
HOSTNAME=127.0.0.1;DATABASE=sample;PORT=50001;UID=test;PWD=123456;SECURITY=SSL;

I don't think the default value of the authentication keyword is "SERVER_ENCRYPT".
could you please help to explain this case? 


Thank you.

**Comment by akhilravuri1** [comment]
If you set the authentication parameter in cfg then the default will be the value in cfg. If it is unset in cfg the default value is server_encrypt.

Thanks,
Akhil

**Comment by WTaoGitHub** [comment]
@akhilravuri1 
Which cfg you are mentioning, the Db2 server configuration?

And didn't change any cfg of the CLI driver.

Thank you.

**Comment by WTaoGitHub** [comment]
hi @akhilravuri1 
I still don't understand this case, would you please give some more explanations, Thank you.

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

Sorry for the late reply.

db2 get dbm cfg |grep AUTHENTICATION this authentication parameter is from the Server side.

If you don't pass anything then it will always set the auth parameter based on the server. So if your server Auth is set to SERVER then it will set to SERVER if it is SERVER_ENCRYPT then it will set to SERVER_ENCRYPT.

So that's why your case 3 and case 6 are passing.

If you pass auth value differently then it will return an unsupported function that why your case 1 and case 5 are failing.

If you have any other questions please let me know.

Thanks,
Akhil

**Comment by WTaoGitHub** [comment]
@akhilravuri1 
Thanks for your explanation, now I get the feature's point.  Thank you so much.
