### ISSUE TITLE
how to add prefix for statements in construction/execution phrase

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#127]
Dear team,

This is a question.  Is there a parameter or method to add prefix for statements in construction or execution phrase?

For example, for each statement to add a comment prefix ,  `/* This is a system query */ <following sql statement>`.

The easiest way is to add it when defining the query string,  for example,
```
queryString := "/* This is a system query */ "+"select * from table"
```
But this will need to do in every query.

Is there a way to add the comment prefix when constructing connection or in before-execution phrase?

Thank you.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 

No, we don't have a parameter setting for adding comments to every query exec.

You can write a small func that returns "comment"+"sql" and use it.

Thanks,
Akhil

**Comment by maxatcn** [comment]
Thank you Akhil.  I got it. Let me close it.
