### ISSUE TITLE
Unable to get go_ibm_db driver on linux

### ISSUE THREAD

**Issue by Shilpa-Jadhav** [ibmdb/go_ibm_db#128]
- os Version: RHEL -7.4
- cli-driver Version:
- Db2 Server Version:
- go Version: go version go1.15.2 linux/amd64
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="<homedir>/.cache/go-build"
GOENV="<homedir>/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="<homedir>/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="<homedir>/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

</pre></details>

Steps to Reproduce:

1. i have installed  go1.15.2 
2. mkdir go_db2
3. cd go_db2
3. Ran --> go get -d github.com/ibmdb/go_ibm_db
4.  no errors but no folder nothing is created here it is empty 

I am unable to do anything. Can you check let me know what's going wrong here?

**Comment by akhilravuri1** [comment]
Hi @Shilpa-Jadhav 

go_ibm_db will not be downloaded in your current path. It is downloaded in your GOPATH dir.

Thanks,
Akhil

**Comment by Shilpa-Jadhav** [comment]
Thank you Akhil. Yes, it is present in GOPATH
