### ISSUE TITLE
Driver seems to encounter an unrecoverable exception when executing system call

### ISSUE THREAD

**Issue by cwatson-cgi** [ibmdb/go_ibm_db#131]
Driver seems to encounter an unrecoverable exception at a system call:
ret = api.SQLDriverConnect(h, 0,
		(*api.SQLWCHAR)(unsafe.Pointer(&b[0])), api.SQLSMALLINT(len(b)),
		nil, 0, nil, api.SQL_DRIVER_NOPROMPT)

- os Version: Windows 10 version 10.0.17134 Build 17134  BUT also happens in our AWS Linux boxes.
- cli-driver Version: Output from db2level:
            DB21085I  This instance or install (instance name, where applicable: "*") uses
            "64" bits and DB2 code release "SQL11014" with level identifier "0205010F".
            Informational tokens are "DB2 v11.1.4050.860", "special_39510",
            "DYN1911120100WIN64_39510", and Fix Pack "5".

- Driver version:  github.com/ibmdb/go_ibm_db v0.4.1
- Db2 Server Version: DB2 for z/OS
- go Version: 1.13.11 
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\XXXXX\AppData\Local\go-build
set GOENV=C:\Users\XXXXX\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=<repo>/XXXX
set GONOSUMDB=<repo>/XXXX
set GOOS=windows
set GOPATH=C:\Users\XXXXXX\go
set GOPRIVATE=<repo>/XXXX
set GOPROXY=direct
set GOROOT=c:\go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\XXXXX\go\src\github.cms.gov\MEPS\marx-premium-scripts\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Temp\go-build179894498=/tmp/go-build -gno-record-gcc-switches
</pre></details>

Steps to Reproduce:
1. This seems to be happening sporadically, every 20k to 100k calls, at different points in our code. It has happened when initiating a transaction, preparing a statement, and executing a query. 
2. We are generally using a max idle connections value of one fewer than max open connections (variable number of max open connections, most recently 100.) 
3. Representative Stack Trace:

Exception 0xc0000005 0x0 0x1bebf870 0x7ffcb7a44dcc
PC=0x7ffcb7a44dcc

syscall.Syscall9(0x7ffd279a112c, 0x8, 0x16, 0x0, 0xc005182000, 0xd4, 0x0, 0x0, 0x0, 0x0, ...)
        c:/go/src/runtime/syscall_windows.go:214 +0xfa
github.com/ibmdb/go_ibm_db/api.SQLDriverConnect(0x16, 0x0, 0xc005182000, 0xc0051800d4, 0x0, 0x0, 0x0, 0x1e0000, 0x203000000000000)
        C:/Users/XXXX/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/api/zapi_windows.go:94 +0xfa
github.com/ibmdb/go_ibm_db.(*Driver).Open(0x17faf20, 0xc00002a380, 0xd3, 0x0, 0x0, 0x0, 0x0)
        C:/Users/XXXX/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/conn.go:29 +0x199
database/sql.dsnConnector.Connect(...)
        c:/go/src/database/sql/sql.go:688
database/sql.(*DB).conn(0xc0003ac000, 0x11ab380, 0xc00001a238, 0xc00681d901, 0x44754e, 0x0, 0xc00681da10)
        c:/go/src/database/sql/sql.go:1228 +0x208
database/sql.(*DB).query(0xc0003ac000, 0x11ab380, 0xc00001a238, 0xc0054c0360, 0x111, 0x0, 0x0, 0x0, 0x1, 0xc005dce2a0, ...)
        c:/go/src/database/sql/sql.go:1565 +0x6d
database/sql.(*DB).QueryContext(0xc0003ac000, 0x11ab380, 0xc00001a238, 0xc0054c0360, 0x111, 0x0, 0x0, 0x0, 0xc00681dc28, 0x18, ...)
        c:/go/src/database/sql/sql.go:1547 +0xd8
database/sql.(*DB).Query(...)
        c:/go/src/database/sql/sql.go:1561
github/repo/common.QueryUnsafe(0xc0003ac000, 0xf1ff14, 0xf8, 0xc00681dc60, 0x3, 0x3, 0xa, 0xed9603f00, 0x0)

**Comment by akhilravuri1** [comment]
Hi @cwatson-cgi 

Is it possible to provide a sample application that reproduces the issue?

Thanks,
Akhil

**Comment by cwatson-cgi** [comment]
That is going to be a challenge because it happens intermittently in an application for which I don't have permission to share code.

**Comment by akhilravuri1** [comment]
Hi @cwatson-cgi 

I will create a sample application with transaction, prepare, and execute.
I will try to reproduce the issue.

Thanks,
Akhil

**Comment by cwatson-cgi** [comment]
@akhilravuri1  this seems to have been specific to the combination of Go and the driver we were using. Upgrading to the newest driver and go 1.15 seems to have resolved it.
