### ISSUE TITLE
error when trying compile as static

### ISSUE THREAD

**Issue by knight-ni** [ibmdb/go_ibm_db#132]
- os Version: CentOS Linux release 7.7.1908 (Core)
- cli-driver Version:linuxx64_odbc_cli.tar.gz
- Db2 Server Version:Informix 12.10FC6
- go Version:1.16.3
<details><summary><code>go env</code> Output: </summary><br><pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/testgo/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/testgo"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/root/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/testgo/src/agent/go.mod"
CGO_CFLAGS="-I/home/testgo/pkg/mod/github.com/ibmdb/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/testgo/pkg/mod/github.com/ibmdb/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2657974003=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

Steps to Reproduce:

1. create a package which import go_ibm_db@v0.4.1 and seal as dbdriver package
2. create another package which handle sql import the dbdriver 
3. create main using sql handler
4. go build --ldflags '-extldflags "-static"' -x ./server/main.go 

# Detail Message
/root/go/pkg/tool/linux_amd64/link -o $WORK/b001/exe/a.out -importcfg $WORK/b001/importcfg.link -buildmode=exe -buildid=nLm1mTDEtDzcaVzOfdzy/xNlL7t_eUhyqCYPuLv2m/hHbFdjP6ReDAcASJ0sX0/nLm1mTDEtDzcaVzOfdzy -extldflags -static -extld=gcc /root/.cache/go-build/06/06bfd80fb372f68bbb0ab467fceda38199ec4be4281d265744cb147a334053c2-d
/root/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -ldb2
/usr/bin/ld: cannot find -ldb2
/tmp/go-link-000593544/000004.o: In function `_cgo_26061493d47f_C2func_getaddrinfo':
cgo_unix.cgo2.c:(.text+0x81): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

but this library should already been there:

[root@gbasehost agent]# env|grep CGO
CGO_LDFLAGS=-L/home/testgo/pkg/mod/github.com/ibmdb/clidriver/lib
CGO_CFLAGS=-I/home/testgo/pkg/mod/github.com/ibmdb/clidriver/include

[root@gbasehost agent]# env|grep LD
OLDPWD=/home/testgo
CGO_LDFLAGS=-L/home/testgo/pkg/mod/github.com/ibmdb/clidriver/lib
LD_LIBRARY_PATH=/home/testgo/pkg/mod/github.com/ibmdb/clidriver/lib

[root@gbasehost agent]# ls -la /home/testgo/pkg/mod/github.com/ibmdb/clidriver/
total 4
drwxr-xr-x 14 5976  105 183 Jan 11 16:34 .
drwxr-xr-x  5 root root  96 May 15 08:45 ..
drwxr-xr-x  2 5976  105 152 Jan 11 16:34 bin
drwxr-xr-x  2 5976  105 122 Jan 11 16:34 bnd
drwxr-xr-x  2 5976  105 116 Nov  2  2020 cfg
drwxr-xr-x  2 5976  105  24 Nov  2  2020 cfgcache
drwxr-xr-x  4 5976  105  27 Nov  2  2020 conv
drwxr-xr-x  3 5976  105  27 Nov  2  2020 db2dump
-rw-r--r--  1 root root   4 May 12 09:54 .ftok
drwxr-xr-x  2 5976  105 202 Nov  2  2020 include
drwxr-xr-x  3 5976  105 179 Jan 11 16:34 lib
drwxr-xr-x  3 5976  105  65 Nov  2  2020 license
drwxr-xr-x  3 5976  105  28 Nov  2  2020 msg
drwxr-xr-x  3 5976  105  21 Nov  2  2020 properties
drwxr-xr-x  3 5976  105  20 Jan 11 16:34 security64

[root@gbasehost agent]# ldconfig -p|grep db2
   libdb2clixml4c.so.1 (libc6,x86-64) => /home/testgo/pkg/mod/github.com/ibmdb/clidriver/lib/libdb2clixml4c.so.1
   libdb2clixml4c.so (libc6,x86-64) => /home/testgo/pkg/mod/github.com/ibmdb/clidriver/lib/libdb2clixml4c.so
   libdb2.so.1 (libc6,x86-64) => /home/testgo/pkg/mod/github.com/ibmdb/clidriver/lib/libdb2.so.1
   libdb2.so (libc6,x86-64) => /home/testgo/pkg/mod/github.com/ibmdb/clidriver/lib/libdb2.so

working like this:

main.go --> sqlHandler --> dbDriver --> GBase8s --> "github.com/ibmdb/go_ibm_db"

directories as followed:
.
├── cfgparser
│   └── cfgparser.go
├── client
│   ├── client
│   ├── cmdRunner
│   │   └── cmdRunner.go
│   ├── conf
│   │   └── conf.ini
│   ├── main.go
│   └── sqlRunner
│       └── sqlRunner.go
├── go.mod
├── go.sum
├── README.md
└── server
    ├── cmdHandler
    │   └── cmdHandler.go
    ├── conf
    │   └── conf.ini
    ├── dbDriver
    │   └── GBase8s
    │       └── GBase8s.go
    ├── main.go
    ├── nohup.out
    ├── server
    ├── sqlHandler
    │   └── sqlHandler.go
    ├── start.sh
    └── stop.sh

what should i do to fix this？

**Comment by tpokki** [comment]
@knight-ni did you fix it?
