### ISSUE TITLE
How to pass cipherSuites to the server

### ISSUE THREAD

**Issue by iamsainianuj** [ibmdb/go_ibm_db#133]
Does anyone knows how to pass Cipher Suites to the server using this driver. along with other tls parameters like CA certificate, public key etc. just like we have in the mySql package RegisterTLSConfig(key string, config *tls.Config) error {}
?

**Comment by bimalkjha** [comment]
@iamsainianuj go_ibm_db uses GSKit libraries for SSL/TSL connection. The supported Cipher Suites are described here: https://www.ibm.com/support/pages/encryption-algorithms-supported-ibm-personal-communications-60

The GSKIT Cipher Specs can be either TLS1.0 or TLS1.1 or TLS1.2 and FIPS mode is enabled by default. Option to control FIPS processing mode has been disabled. This change has been made to protect against security vulnerability in RC4 stream cipher, also commonly referred to as "Bar Mitzvah Attack".

Currently, the cipher suite is decided based on the maximum supported cipher suites by client and server both. So, no need to specify specifically. We are working on an enhancement in our driver, where user can specify the cipher specs as TLS1.0 or TSL1.1 or TLS1.2 via connection string while making a connection with server. But, this support is not available yet. It'll be available by end of 2021. Thanks.
