### ISSUE TITLE
How do I set Application Name through the driver

### ISSUE THREAD

**Issue by WTaoGitHub** [ibmdb/go_ibm_db#134]
Hi experts,
we are using the driver to connect to a  Db2 database server, when the connection establishes, from the db2 side we can use the " db2 list application " command to view the application info.

```
Auth Id  Application    Appl.      Application Id                                                 DB       # of
         Name           Handle                                                                    Name    Agents
-------- -------------- ---------- -------------------------------------------------------------- -------- -----
DB2INST1 out            7465       9.125.230.180.53229.210527043902                               SAMPLE   1    
```
My question is how do I set the Application Name through the driver, I searched the CLI/ODBC configuration keywords and found a key ClientApplName, but in my test, ClientApplName didn't work as I expect.
I build up a connection string and appends "ClientApplName=myapp" in my test case, and then execute a query, hold on the close the connection. With the  " db2 list application " command, I can see the connection established but the Application Name doesn't change.

Thanks for your time.

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

Are you running the `db2 list application` command in the system where the server is installed?

Thanks,
Akhil

**Comment by WTaoGitHub** [comment]
Hi @akhilravuri1 
Yes, I run the command `db2 list application` on the DB2 server-side.
my go program is trying to connect  to the DB2 database server, when the go program running, I log in to the DB2 server and run to command

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

I am trying to reproduce the problem.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @WTaoGitHub 

You have to use ```ProgramName=myapp``` not ```ClientApplName=myapp```

Thanks,
Akhil

**Comment by WTaoGitHub** [comment]
HI  @akhilravuri1，
That works in my test case, thanks a lot.
I closed the issue.
Best wishes
