### ISSUE TITLE
MSCK REPAIR returns error

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#135]
Dear team,

This is to connect to bigsql and run statement `MSCK REPAIR TABLE <schema>.<table>`,  it returned error.

When with code,
```
_, err = db.Exec("MSCK REPAIR TABLE test1.table1")
```
It returned error message,
```
2021/05/27 19:43:47 SQLExecute: {     } [IBM][CLI Driver][DB2/LINUXX8664] SQL0142N  The SQL statement is not supported
```

If changing to Query,
```
_, err = db.Query("MSCK REPAIR TABLE test1.table1")
```
It returned error messge,
```
2021/05/27 19:52:43 Stmt did not create a result set
```

Can you please help check and advise?  Thanks.

**Comment by bimalkjha** [comment]
@maxatcn I think MSCK REPAIR is a hive command that you might be executing db2 command line processor or a hive client. It is not a valid SQL statement and go_ibm_db support execution of only valid SQL statement. MSCK command is not mentioned in the list of SQL statements here: https://www.ibm.com/docs/en/db2-big-sql/5.0.1?topic=reference-statements
Thanks.

**Comment by bimalkjha** [comment]
To be precise, go_ibm_db supports only the SQL statement supported by an ODBC driver. Thanks.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 

db.Query did not return any error it just returned that this query did not return any result set.

It is a normal behaviour.

You can validate the the change you have done.

Please let me know if you any information on this.


Thanks,
Akhil

**Comment by maxatcn** [comment]
Thank you @akhilravuri1 . 
I tried with 'begin execute immediate...',  it works for now. 
Let's keep it. Close this issue for now.
