### ISSUE TITLE
DB2 ACR support

### ISSUE THREAD

**Issue by kushaal-veijay** [ibmdb/go_ibm_db#136]
From what I read in DB2 documentation(https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/c0056196.html) and DB2 wiki(https://www.ibm.com/support/pages/howto-configure-non-java-automatic-client-reroute), we can enable automatic client reroute setting in non-java client using db2dsdriver.cfg. So, is that true with Golang DB2 driver as well? Is the ACR mode supported?

**Comment by akhilravuri1** [comment]
Hi @kushaal-veijay 

Sorry for the late reply.

Yes, our Go driver supports all the features supported by the cli driver.
Yes, ACR mode is also supported.

Thanks,
Akhil

**Comment by kushaal-veijay** [comment]
Thanks @akhilravuri1 !
