### ISSUE TITLE
cannot download db2 driver from ibm website

### ISSUE THREAD

**Issue by Seakia** [ibmdb/go_ibm_db#137]
https://www.ibm.com/support/pages/node/387577
the website includes driver, but we cannot download. And i'm in China.
pls fix it.

**Comment by akhilravuri1** [comment]
we will look into this.

-Akhil

**Comment by bimalkjha** [comment]
@Seakia You can download it from [Fix Central](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=11.5.5.0&platform=All&function=fixId&fixids=*FP000*&includeSupersedes=0&source=fc) or contact IBM Support for help. Thanks.
