### ISSUE TITLE
library panics when test is run with race flag

### ISSUE THREAD

**Issue by iamsainianuj** [ibmdb/go_ibm_db#138]
- os Version: Mac OS X (ProductVersion: 10.157, BuildVersion: 19H1217)
- cli-driver Version: 11.5.0
- Db2 Server Version: (DB2 Community Edition, 11.5)
- go Version: (1.15.8)
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/anujsain/go/bin"
GOCACHE="/Users/anujsain/Library/Caches/go-build"
GOENV="/Users/anujsain/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/anujsain/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="true"
GOOS="darwin"
GOPATH="/Users/anujsain/go"
GOPRIVATE=""
GOPROXY=
GOROOT="/usr/local/Cellar/go/1.15.8/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=
CGO_CFLAGS="-I/Users/anujsain/go/src/github.com/ibmdb/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/Users/anujsain/go/src/github.com/ibmdb/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hy/2stw2mc91hbct5v_7fx8dy303rb7bh/T/go-build960349166=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

Steps to Reproduce:

```go
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/ibmdb/go_ibm_db"
	"github.com/stretchr/testify/assert"
	"testing"
)

func Test_Main(t *testing.T) {
	con := "HOSTNAME=127.0.0.1;DATABASE=testdb;PORT=50000;UID=db2inst1;PWD=mydb2"
	type Db *sql.DB
	var re Db
	re = createCon(con)
	err := create(re)
	assert.Nil(t, err)
	if err != nil {
		fmt.Println(err)
	}
	assert.Nil(t, err)
	err := insert(re)
	if err != nil {
		fmt.Println(err)
	}
	assert.Nil(t, err)
	err = display(re)
	if err != nil {
		fmt.Println(err)
	}
	assert.Nil(t, err)
}

func createCon(con string) *sql.DB {
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)
		return nil
	}
	return db
}

func insert(db *sql.DB) error {
	st, err := db.Prepare("Insert into SAMPLE(ID,NAME,LOCATION,POSITION) values('3242','mike','hyd','manager')")
	if err != nil {
		return err
	}
	st.Query()
	return nil
}

func create(db *sql.DB) error {
	_, err := db.Exec("DROP table SAMPLE")
	if err != nil {
		_, err := db.Exec("create table SAMPLE(ID varchar(20),NAME varchar(20),LOCATION varchar(20),POSITION varchar(20))")
		if err != nil {
			return err
		}
	} else {
		_, err := db.Exec("create table SAMPLE(ID varchar(20),NAME varchar(20),LOCATION varchar(20),POSITION varchar(20))")
		if err != nil {
			return err
		}
	}
	fmt.Println("TABLE CREATED")
	return nil
}

func display(db *sql.DB) error {
	st, err := db.Prepare("select * from SAMPLE")
	if err != nil {
		return err
	}
	err = execquery(st)
	if err != nil {
		return err
	}
	return nil
}

func execquery(st *sql.Stmt) error {
	rows, err := st.Query()
	if err != nil {
		return err
	}
	cols, _ := rows.Columns()
	fmt.Printf("%s    %s   %s    %s\n", cols[0], cols[1], cols[2], cols[3])
	fmt.Println("-------------------------------------")
	defer rows.Close()
	for rows.Next() {
		var t, x, m, n string
		err = rows.Scan(&t, &x, &m, &n)
		if err != nil {
			return err
		}
		fmt.Printf("%v  %v   %v         %v\n", t, x, m, n)
	}
	return nil
}
```

fatal error: checkptr: pointer arithmetic computed bad pointer value

goroutine 1 [running, locked to thread]:
runtime.throw(0x43b4661, 0x37)
        /usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc00012fd78 sp=0xc00012fd48 pc=0x403acf2
runtime.checkptrArithmetic(0x3, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.15.8/libexec/src/runtime/checkptr.go:26 +0xd7 fp=0xc00012fda8 sp=0xc00012fd78 pc=0x400acf7
github.com/ibmdb/go_ibm_db.initDriver(0x0, 0x0)
        /Users/anujsain/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/driver.go:37 +0x136 fp=0xc00012fe68 sp=0xc00012fda8 pc=0x41eb956
github.com/ibmdb/go_ibm_db.init.0()
        /Users/anujsain/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/driver.go:62 +0x70 fp=0xc00012fef8 sp=0xc00012fe68 pc=0x41ebcb0
runtime.doInit(0x453e2a0)
        /usr/local/Cellar/go/1.15.8/libexec/src/runtime/proc.go:5652 +0x8a fp=0xc00012ff28 sp=0xc00012fef8 pc=0x404a94a
runtime.doInit(0x453b840)
        /usr/local/Cellar/go/1.15.8/libexec/src/runtime/proc.go:5647 +0x57 fp=0xc00012ff58 sp=0xc00012ff28 pc=0x404a917
runtime.doInit(0x453ba40)
        /usr/local/Cellar/go/1.15.8/libexec/src/runtime/proc.go:5647 +0x57 fp=0xc00012ff88 sp=0xc00012ff58 pc=0x404a917
runtime.main()
        /usr/local/Cellar/go/1.15.8/libexec/src/runtime/proc.go:191 +0x1c5 fp=0xc00012ffe0 sp=0xc00012ff88 pc=0x403d465
runtime.goexit()
        /usr/local/Cellar/go/1.15.8/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00012ffe8 sp=0xc00012ffe0 pc=0x4073ba1

**Comment by akhilravuri1** [comment]
Hi @iamsainianuj 

Sorry for the late reply.

I will try to reproduce the issue.

Thanks,
Akhil

**Comment by kushaal-veijay** [comment]
I am also trying to run the race test on my go project and I am also getting the same error. Any update on this?

**Comment by vmathur12** [comment]
I am able to reproduce the issue. I am working on it.

**Comment by vmathur12** [comment]
To test this fix, run
go test -race -gcflags=all=-d=checkptr=0

**Comment by bimalkjha** [comment]
@iamsainianuj @kushaal-veijay To avoid the panic due to use of `-race` option, we need to use `-gcflags` option as in above update. Thanks.
