### ISSUE TITLE
Library not loaded: libdb2.dylib ; on Mac again....

### ISSUE THREAD

**Issue by xSeaGull** [ibmdb/go_ibm_db#139]
I am having issues installing the DB2 driver for go. 

go run setup.go
```
clidriver is already present in this path /Users/<userid>/go/src/github.com/ibmdb/clidriver
Please set CGO_CFLAGS, CGO_LDFLAGS and LD_LIBRARY_PATH or DYLD_LIBRARY_PATH environment variables
exit status 1
```

os Version: macOS Bigsur 11.4
go Version: 1.16.6
go env Output:

$ go env
`CGO_ENABLED="1"`

Steps to Reproduce:

This is how my env variables are set:
```
export DB2HOME=/Users/<userid>/go/src/github.com/ibmdb/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Users/<userid>/go/src/github.com/ibmdb/clidriver/lib
```

This is the error message when trying to load the library

```
dyld: Library not loaded: libdb2.dylib
  Referenced from: /var/folders/v0/6jy19pf150dg67rbby3gxd3r0000gn/T/go-build1274994964/b001/exe/main
  Reason: image not found
signal: abort trap
```

**Comment by akhilravuri1** [comment]
Hi @xSeaGull 

Can you please cd to this ```/Users/<userid>/go/src/github.com/ibmdb/clidriver``` and runs ls cmd and paste the output.

Thanks,
Akhil

**Comment by xSeaGull** [comment]
ls output:
clidriver ➤ ls
bin        bnd        cfg        cfgcache   conv       db2dump    include    lib        license    msg        security64

**Comment by xSeaGull** [comment]
ls output:

```shell
clidriver ➤ ls
bin bnd cfg cfgcache conv db2dump include lib license msg security64
```

**Comment by vmathur12** [comment]
@xSeaGull Are you still facing this issue by using the latest code of go ibm_db driver?

**Comment by vmathur12** [comment]
@xSeaGull   I am closing this issue. Let me know if you are facing this issue again. Thanks

**Comment by xSeaGull** [comment]
@vmathur12  It works,thanks 
Sorry for the late reply 🤝
