### ISSUE TITLE
clidriver install path in travis.

### ISSUE THREAD

**Issue by jinzihuang** [ibmdb/go_ibm_db#14]
Hi team, 
In Travis I need to run `sudo go run setup.go` to install Cli.
The clidriver was installed in the root level src directory: 
`/src/github.com/ibmdb/go_ibm_db/installer`
instead of 
`/gopath/src/github.com/ibmdb/go_ibm_db/installer`

Please advice. Thank you.

**Comment by akhilravuri1** [comment]
Hi
Can you paste you go env output?

Thanks.

**Comment by akhilravuri1** [comment]
Hi @jinzihuang

I have done the Travis setup and downloaded the driver from Github and  CLI driver by running the setup.go file without sudo command. Maybe you have to just check your Access Rights.

Thanks.

**Comment by jinzihuang** [comment]
Hi Akhil , thanks for you replay.
In my local machine
After run `go get -d github.com/ibmdb/go_ibm_db`
go_ibm_db was downloaded into **2** locations:
1,  `gopath/src/github.com/ibmdb/go_ibm_db/...`
2,  `gopath/pkg/mod/github.com/ibmdb/go_ibm_db/...`
If I use path `gopath/src/github.com/ibmdb/go_ibm_db/...` to run setup. there is no issue.
If I use path`gopath/pkg/mod/github.com/ibmdb/go_ibm_db/...`to run setup, there is a persmision issue.
```Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz
Error while downloading file: open macos64_odbc_cli.tar.gz: permission denied
exit status 1


ls -al
-r--r--r--   1 user  staff  5279 Apr  1 09:39 setup.go
```

However, in Travis, 
After run `go get -d github.com/ibmdb/go_ibm_db`
go_ibm_db was downloaded into only **1** locations:
`gopath/pkg/mod/github.com/ibmdb/go_ibm_db/...`
So if I want to run setup, I have to use sudo

The following are my go env

```
go version go1.12 linux/amd64

GOARCH="amd64"

GOBIN=""

GOCACHE="/home/travis/.cache/go-build"

GOEXE=""

GOFLAGS=""

GOHOSTARCH="amd64"

GOHOSTOS="linux"

GOOS="linux"

GOPATH="/home/travis/gopath"

GOPROXY=""

GORACE=""

GOROOT="/home/travis/.gimme/versions/go1.12.linux.amd64"

GOTMPDIR=""

GOTOOLDIR="/home/travis/.gimme/versions/go1.12.linux.amd64/pkg/tool/linux_amd64"

GCCGO="gccgo"

CC="gcc"

CXX="g++"

CGO_ENABLED="1"

CGO_CFLAGS="-I/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include"

CGO_CPPFLAGS=""

CGO_CXXFLAGS="-g -O2"

CGO_FFLAGS="-g -O2"

CGO_LDFLAGS="-L/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib"

PKG_CONFIG="pkg-config"

GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build933651362=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by akhilravuri1** [comment]
Hi @jinzihuang 

```go
language: go

go:
    - "1.11"

before_install:
    - go get -d github.com/ibmdb/go_ibm_db
    - cd $GOPATH/src/github.com/ibmdb/go_ibm_db/installer
    - go run setup.go
    - ls
    - cd clidriver
    - export DB2HOME=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver
    - export CGO_CFLAGS=-I$DB2HOME/include
    - export CGO_LDFLAGS=-L$DB2HOME/lib
    - export LD_LIBRARY_PATH=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
    - cd $GOPATH/src/github.com/akhilravuri1/TravisTest
    - echo $DB2HOME
    - echo $PATH
script:
    - go run testing.go
```
I used this yml script and it installed me in gopath/src and i was able to run the setup.go file without sudo. Can you share me the build link of your project in travis .

**Comment by smuda** [comment]
@akhilravuri1 are using go 1.11 and @jinzihuang are using go 1.12.

There are differences between go 1.11 and go 1.12 how dependencies are handled. (They were introduced in 1.11 but were opt-in). Have a look at [modules](https://github.com/golang/go/wiki/Modules).

In my case I use a modified "setup.go" to extract the files where I want them.

**Comment by akhilravuri1** [comment]
@smuda  I tested with1.12 now It's working fine as you said modules were introduced in 1.11 so It doesn't change much I think.
If he downloads the driver using go get he will get the master branch which has updated "setup.go".

Thanks.

**Comment by jinzihuang** [comment]
@smuda and @akhilravuri1 
Thank you for your replies.

Yes I am using go 1.12. 
Does go_ibm_db@v0.0.0-20190401124318-6c640a02c8b9 include the updated setup.go?
This is the one I get from using go get.

**Comment by akhilravuri1** [comment]
Yes, v0.0.0 -6c640a02c8b9 is the latest commit and you will have updated setup.go.

This is my build link (https://travis-ci.com/akhilravuri1/TravisTest/builds/107366193) and I am able to do all the operations without permission issue.

Can you share the build link in Travis? So that I can look into that error.

**Comment by jinzihuang** [comment]
Thanks @akhilravuri1
Sorry i cannot share my Travis build :(
I do see your build was past. But I don't see setup.go was updated in the master branch.
![Screen Shot 2019-04-11 at 9 46 40 AM](https://user-images.githubusercontent.com/23530242/55962423-d141f800-5c3e-11e9-82ac-a3ca316a68b2.png)

**Comment by akhilravuri1** [comment]
Hi @jinzihuang 

The Build which shared was the latest build(4 days ago). And it was build with existing setup.go in the master branch.

You download our driver using go get or from go.mod file?

**Comment by jinzihuang** [comment]
I used go get

**Comment by akhilravuri1** [comment]
Hi @jinzihuang 

I have updated the setup.go once again. Hoping that you will get the updated one.
There are no much changes in it. while running the go run command you can pass the destination path like go run setup.go C:\Go\programs 
(or) 
go run setup.go which will download the file in the default location(where the driver is downloaded).

Pull the latest code and try using new setup.go. 

Update me whether it is working or not.

Thanks.
Akhil

**Comment by jinzih** [comment]
Hi Akhil,
I see bimdb was downloaded under src dir now!

Thank you very much!
