### ISSUE TITLE
Add script to set environment variables

### ISSUE THREAD

**Issue by data-henrik** [ibmdb/go_ibm_db#140]
**Is your feature request related to a problem? Please describe.**
In your install section, you describe several commands to be executed. They are needed to set up the environment by setting variables. It is a manual process.

**Describe the solution you'd like**
Provide scripts to be run.

**Describe alternatives you've considered**
Yes, each user could copy the setup steps into a script and run them. But a script would be more user-friendly.

**Comment by akhilravuri1** [comment]
Hi @data-henrik 

We will look into this.

Thanks,
Akhil

**Comment by vmathur12** [comment]
@data-henrik Added setevn.sh script to set environment variables for non-Windows platform
To run the script go to installer folder and execute command "source setenv.sh"

cd .../go_ibm_db/installer
source setenv.sh

**Comment by data-henrik** [comment]
Where is it documented?
