### ISSUE TITLE
fatal error: 'sqlcli1.h' file not found

### ISSUE THREAD

**Issue by alexcocia** [ibmdb/go_ibm_db#142]
I know this issue is repeated, but tried everything and still not working

- os Version: macOS BigSur 11.5.2
- cli-driver Version:  go_ibm_db@v0.4.1
- go Version: go1.16.6 darwin/amd64
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env

```
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-I/Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/lib"
```
</pre></details>

ENV variables
```
DB2HOME=/Users/uname/go/pkg/mod/github.com/ibmdb/clidriver
CGO_CFLAGS=-I/Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/include
CGO_LDFLAGS=-L/Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/lib
```

```
$ echo $DYLD_LIBRARY_PATH
:/Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/lib
```

Steps to Reproduce:

1. go test code involving the DB2 call.

Error reported:
```
go test -v ././cmd/...
# github.com/ibmdb/go_ibm_db/api
../../../go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/api/api_unix.go:13:11: fatal error: 'sqlcli1.h' file not found
 #include <sqlcli1.h>
          ^~~~~~~~~~~
1 error generated.
```

Found the headers in 
```
$ ls $DB2HOME/include
sql.h      sqlca.h    sqlcli.h   sqlcli1.h  sqlda.h    sqlenv.h   sqlext.h   sqlstate.h sqlsystm.h sqltypes.h sqlucode.h sqlunx.h
```

Only changed my user name for the "uname" string 
I was used to this driver in my linux.. but changed to mac and this is the only problem I've found so far

**Comment by akhilravuri1** [comment]
Hi @alexcocia 

Sorry for the late reply.

Are you facing this issue now?

I will try to reproduce the issue.

Thanks,
Akhil

**Comment by UmarDafedarProgrammer** [comment]
I am facing an issue w.r.to sqlcli1.h. Can you please help me here

**Comment by wkpuy** [comment]
I have problem 

os Version: macOS Monterey version 12.2
cli-driver Version: go_ibm_db@v0.4.5
go Version: go version go1.19.1 darwin/amd64

`CGO_CFLAGS="-I/Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/lib"
`

echo $DYLD_LIBRARY_PATH
/Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/lib:/Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/lib

uname -a >>Darwin HQT212736.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

**Comment by bimalkjha** [comment]
@wkpuy Please share output of below commands from terminal:
```
ls /Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/
echo $IBM_DB_HOME
echo $PATH
db2level
```
Thanks.
