### ISSUE TITLE
How to insert an empty value in slice

### ISSUE THREAD

**Issue by travelliu** [ibmdb/go_ibm_db#148]
- os Version: macOS
- cli-driver Version: 11.5
- Db2 Server Version: 11.5
- go Version:
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/travel/Library/Caches/go-build"
GOENV="/Users/travel/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/travel/Documents/Code/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/travel/Documents/Code/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-I/Users/travel/Oracle_tools/db2client/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/Users/travel/Oracle_tools/db2client/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k1/vqmqkz_s4gg5c0775rlv4g000000gn/T/go-build2837241574=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

Steps to Reproduce:

1.
```
				if err = m.ConnectDatabase(ctx); err != nil {
					t.Error(err)
					return
				}
				defer m.DB.Close()
				m.DB.Exec("drop table test1")
				m.DB.Exec(
					"create table test1(id bigint,col1 varchar(40)," +
						"col2 varchar(40),col3 varchar(40),col4 bigint,col5 varchar(40))",
				)
				var (
					args []interface{}
					sql  = "insert into test1(id,col1,col2,col3,col4,col5) values (?,?,?,?,?,?)"
					// sql  = "insert into test1(col1,col2,col3,col5) values (?,?,?,?)"
				)
				stat, err := m.DB.PrepareContext(ctx, sql)
				if err != nil {
					t.Error(err)
					return
				}
				defer stat.Close()
				var (
					ids                 []int64
					col4s               []int64
					col1s               []*string
					col2s, col3s, col5s []string
				)
				for i := 0; i < 10; i++ {
					ids = append(ids, utils.GenerateID())
					if i == 5 {
						col1s = append(col1s, nil)
						col2s = append(col2s, uuid.New().String())
						col3s = append(col3s, uuid.New().String())
						col4s = append(col4s, utils.GenerateID())
						col5s = append(col5s, uuid.New().String())
					} else {
						a := uuid.New().String()
						col1s = append(col1s, &a)
						col2s = append(col2s, uuid.New().String())
						col3s = append(col3s, uuid.New().String())
						col4s = append(col4s, utils.GenerateID())
						col5s = append(col5s, uuid.New().String())
					}
	
				}
				args = append(args, ids, col1s, col2s, col3s, col4s, col5s)
				// args = append(args, col1s,col2s,col3s,col5s)
				_, err = stat.Exec(args...)
				if err != nil {
					t.Error(err)
					return
				}
```
2. 
```
sql: converting argument $2 type: unsupported type []*string, a slice of ptr
```

**Comment by vmathur12** [comment]
@travelliu 
   _, err := db.Exec("DROP table VMSAMPLE")
        if err != nil {
            _, err := db.Exec("create table VMSAMPLE(col1 varchar(40), col2 varchar(40), col3 varchar(40), col4 varchar(40))")
            if err != nil {
                fmt.Println(err)
            }
        } else {
            _, err := db.Exec("create table VMSAMPLE(col1 varchar(40), col2 varchar(40), col3 varchar(40), col4 varchar(40))")
            if err != nil {
                fmt.Println(err)
            }
        }

        var (
                args []interface{}
                sql = "Insert into VMSAMPLE(col1, col2, col3, col4) values(?, ?, ?, ?)"
        )

        stat, err := db.Prepare(sql)
        if err != nil {
                fmt.Println(err)
        }

        var (
                col1s  []string
                col2s []*string
                col3s []string
                col4s []string
        )
        a := uuid.New().String()

        col1s = append(col1s, uuid.New().String())
        col2s = append(col2s, &a)
        col3s = append(col3s, uuid.New().String())
        col4s = append(col4s, uuid.New().String())

        args = append(args, col1s, *col2s[0], col3s, col4s)

        _, err = stat.Exec(args...)
        if err != nil {
               fmt.Println(err)
        }
