### ISSUE TITLE
Regarding connecting to db2 database 

### ISSUE THREAD

**Issue by krishnayeddula** [ibmdb/go_ibm_db#149]
- os Version: Ubuntu 18.04.6 LTS
- cli-driver Version: Not sure
- Db2 Server Version:  11.5.6.0
- go Version: go version go1.17.3 linux/amd64

Summary of the Issue:

I installed db2 community edition on Ubuntu 18.04. Installation was successful and i can able to connect to db2 via commandline tools provided.

Whereas, I tried to connect it using the go lang program provided ( in the example section )
I used the default values for the connection instead of the db2 database details (the real information related to hostname, database, port, uid and pwd) . I kept the con string as it is(literally) which is provided in the example.
**con := "HOSTNAME=host;DATABASE=name;PORT=number;UID=username;PWD=password**
but still the output of the program returned **connected instead of erroring out**.

I am new to both db2 and go lang so pardon me if i am missing anything basic here. Guidance will be most appreciated

Steps to Reproduce:

db2inst1@db2:~/go_projects/src$ cat example_1.go
package main

import (
        "database/sql"
        "fmt"
        _ "github.com/ibmdb/go_ibm_db"
)

func main() {
        con := "HOSTNAME=host;DATABASE=name;PORT=number;UID=username;PWD=password"
        db, err := sql.Open("go_ibm_db", con)
        if err != nil {
                fmt.Println(err)
        }else {
                fmt.Println("Connected!")
       }
        db.Close()
}
db2inst1@db2:~/go_projects/src$ go run example_1.go
Connected!

**Comment by maddogxx** [comment]
Insert this:
	err = db.Ping()
	if err == nil {
		fmt.Println("CONNECTION SUCCESS")
	} else {
		fmt.Println(err)
	}

**Comment by bimalkjha** [comment]
@krishnayeddula Your code should be as below:
```
if err != nil {
fmt.Println("Connected!")
}else {
fmt.Println(err)
}
```
