### ISSUE TITLE
Get more than one row with SELECT * ...

### ISSUE THREAD

**Issue by pbabka** [ibmdb/go_ibm_db#151]
- os Version: Ubuntu 20.04LTS
- cli-driver Version: 11.5.5.0
- Db2 Server Version: 11.5.6.0
- go Version: 1.16.2
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/peter/.cache/go-build"
GOENV="/home/peter/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/peter/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/peter/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1428623998=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

This sample program is working, but it returns only one record with "Select * ..." although there are approx. 20 records in the table.

Steps to Reproduce:

1.
<pre>
package main

import (
    "database/sql"
    "fmt"
    _ "github.com/ibmdb/go_ibm_db"
)

var (
    id   int
    name string
)

func main() {
    con := "HOSTNAME=xxx;DATABASE=SAMPLE;PORT=xxx;UID=xxx;PWD=xxx"
    db, err := sql.Open("go_ibm_db", con)
    if err != nil {
        fmt.Println(err)
    }
    defer db.Close()

    st, err := db.Prepare("select empno,firstnme from employee")
    if err != nil {
        fmt.Println(err)
    }

    rows, err := st.Query()
    if err != nil {
        fmt.Println(err)
    }

	defer rows.Close()

    if rows.Next() {

        err = rows.Scan(&id, &name)
        fmt.Println(id, name)

    }
    err = rows.Err()
    if err != nil {
        fmt.Println(err)
    }
}
</pre>

**Comment by bimalkjha** [comment]
@pbabka `rows.Next()` returns only one row at a time. So, you need to call `rows.Next()` repeatedly to get more rows as shown in below code:
```
	defer rows.Close()
	for rows.Next() {
		var t, x, m, n string
		err = rows.Scan(&t, &x, &m, &n)
		if err != nil {
			return err
		}
		fmt.Printf("%v  %v   %v         %v\n", t, x, m, n)
	}
```
Thanks.

**Comment by pbabka** [comment]
Hello,
I'm very ashamed of myself because that's a basic thing, I don't even understand how I could have made this mistake ...
Thanks.
