### ISSUE TITLE
DB2 ACR work only once

### ISSUE THREAD

**Issue by ugatkal** [ibmdb/go_ibm_db#152]
- os Version: Ubuntu 20.04.3 LTS \n \l
- cli-driver Version: 
- Db2 Server Version:  DB2/LINUXX8664 11.5.6.0
- go Version:  go1.17.2 

I have configured DB2 ACR. Here are the details from primary DB (172.17.0.3).
<pre>
[db2inst1@64d275d5d7ad ~]$ db2 list db directory

 System Database Directory

 Number of entries in the directory = 1

Database 1 entry:

 Database alias                       = GOVDB
 Database name                        = GOVDB
 Local database directory             = /database/data
 Database release level               = 15.00
 Comment                              =
 Directory entry type                 = Indirect
 Catalog database partition number    = 0
 Alternate server hostname            = 172.17.0.5
 Alternate server port number         = 50000

[db2inst1@64d275d5d7ad ~]$ 
</pre>
Here are the details from secondary DB (172.17.0.5)
<pre>
[db2inst1@66716d09b534 ~]$ db2 list db directory

 System Database Directory

 Number of entries in the directory = 1

Database 1 entry:

 Database alias                       = GOVDB
 Database name                        = GOVDB
 Local database directory             = /database/data
 Database release level               = 15.00
 Comment                              =
 Directory entry type                 = Indirect
 Catalog database partition number    = 0
 Alternate server hostname            = 172.17.0.3
 Alternate server port number         = 50000

[db2inst1@66716d09b534 ~]$ 

</pre>

On my client machine (from where I run my GO code), validation results are as follows:
<pre>
root@bc209786c47c:~/abac-compute/internal/main# /root/go/pkg/mod/github.com/ibmdb/clidriver/bin/db2cli validate -DSN govdb

===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.5.5.0 (s2011011400/64-bit)
Client Platform           : Linux/X8664
Install/Instance Path     : /root/go/pkg/mod/github.com/ibmdb/clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : /root/go/pkg/mod/github.com/ibmdb/clidriver/cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : /root/go/pkg/mod/github.com/ibmdb/clidriver/cfg/db2cli.ini
db2diag.log Path          : /root/go/pkg/mod/github.com/ibmdb/clidriver/db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Success: The system db2dsdriver.cfg schema validation completed successfully without any errors.

===============================================================================
db2cli.ini validation for data source name "govdb":
===============================================================================

Note: The validation utility could not find the configuration file db2cli.ini. 
The file is searched at 
"/root/go/pkg/mod/github.com/ibmdb/clidriver/cfg/db2cli.ini".

===============================================================================
db2dsdriver.cfg validation for data source name "govdb":
===============================================================================

[ Parameters used for the connection ]

Keywords                  Valid For     Value
---------------------------------------------------------------------------
DATABASE                  CLI,.NET,ESQL govdb
HOSTNAME                  CLI,.NET,ESQL 172.17.0.3
PORT                      CLI,.NET,ESQL 50000
KEEPALIVETIMEOUT          CLI,.NET,ESQL 20
CONNECTIONTIMEOUT         CLI,.NET,ESQL 10
MEMBERCONNECTTIMEOUT      CLI,.NET,ESQL 1

[ Parameters used for ACR ]

Parameter                 Value
---------------------------------------------------------------------------
enableAcr                 true
maxAcrRetries             30
acrRetryInterval          2
enableSeamlessACR         true
enableAlternateServerListFirstConnect true
affinityFailbackInterval  2

alternate server list:

name:govdb  hostname:172.17.0.5  port:50000  

===============================================================================
The validation is completed.
===============================================================================
</pre> 

Here are the contents of file db2dsdriver.cfg.
```
root@bc209786c47c:~/abac-compute/internal/main# cat /root/go/pkg/mod/github.com/ibmdb/clidriver/cfg/db2dsdriver.cfg
 <configuration>
     <dsncollection>
         <dsn alias="govdb" name="govdb" host="172.17.0.3" port="50000"></dsn>
     </dsncollection>
     <databases>
         <database name="govdb" host="172.17.0.3" port="50000">
<parameter name="KeepAliveTimeout" value="20"/>
         <parameter name="ConnectionTimeout" value="10"/>
         <parameter name="MemberConnectTimeout" value="1"/>
             <acr>
                 <parameter name="enableAcr" value="true"></parameter>
                 <parameter name="maxAcrRetries" value="30"></parameter>
                 <parameter name="acrRetryInterval" value="2"></parameter>
                 <parameter name="enableSeamlessACR" value="true"></parameter>
                 <parameter name="enableAlternateServerListFirstConnect" value="true"></parameter>
<parameter name="affinityFailbackInterval" value="2"/>
                 <alternateserverlist>
                     <server hostname="172.17.0.5" port="50000" name="govdb"></server>
                 </alternateserverlist>
             </acr>
         </database>
     </databases>
 </configuration>
root@bc209786c47c:~/abac-compute/internal/main# 
```

Here is the GO code I am using to connect to DB2
```
package main

import (
	"database/sql"
	"fmt"
	"time"

	_ "github.com/ibmdb/go_ibm_db"
)

const (
	dbName = "govdb"
	dbUID  = "db2inst"
	dbPWD  = "password"
)

func dbConnect() (*sql.DB, error) {
	connStr := fmt.Sprintf("DSN=%s;UID=%s;PWD=%s", dbName, dbUID, dbPWD)

	db, err := sql.Open("go_ibm_db", connStr)
	if err != nil {
		fmt.Println("dbConnect:Error:", err)
		return nil, err
	}

	return db, nil
}

func execDBSelect() error {
	xdb, err := dbConnect()
	if err != nil {
		fmt.Println("execDBSelect:Error:", err)
		return err
	}
	defer xdb.Close()

	fmt.Println("execDBSelect:Got Connection.")

	if err := xdb.Ping(); err != nil {
		fmt.Println("execDBSelect:Unable to reach database", err)
		return err
	} else {
		fmt.Println("execDBSelect:Database is reachable")
		return nil
	}
}

func testDBConnection() {
	fmt.Println("================= SQL START ================")

	if err := execDBSelect(); err != nil {
		fmt.Println("FAIL")
	} else {
		fmt.Println("SUCCESS")
	}

	fmt.Println("================= SQL END ================")
}

func main() {
	testDBConnection()
	time.Sleep(20 * time.Second)
	testDBConnection()
	time.Sleep(20 * time.Second)
	testDBConnection()
}
```

If both primary and secondary DB are running, everything works fine and my go code output is as follows:
<pre>
root@bc209786c47c:~/abac-compute/internal/main# go run db2.go
================= SQL START ================
execDBSelect:Got Connection.
execDBSelect:Database is reachable
SUCCESS
================= SQL END ================
================= SQL START ================
execDBSelect:Got Connection.
execDBSelect:Database is reachable
SUCCESS
================= SQL END ================
================= SQL START ================
execDBSelect:Got Connection.
execDBSelect:Database is reachable
SUCCESS
================= SQL END ================
root@bc209786c47c:~/abac-compute/internal/main# 
</pre>

But if I shutdown my primary DB after first connection is successful, my second connection succeeds (it is expected as it must have connected to secondary DB) but surprisingly my third connection fails. In this case my go program output is as follows:
<pre>
root@bc209786c47c:~/abac-compute/internal/main# go run db2.go
================= SQL START ================
execDBSelect:Got Connection.
execDBSelect:Database is reachable
SUCCESS
================= SQL END ================
================= SQL START ================
execDBSelect:Got Connection.
execDBSelect:Database is reachable
SUCCESS
================= SQL END ================
================= SQL START ================
execDBSelect:Got Connection.
execDBSelect:Unable to reach database SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.17.0.3".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001

FAIL
================= SQL END ================
root@bc209786c47c:~/abac-compute/internal/main# 
</pre>

Now If I keep my primary DB stopped and secondary running before I run my GO program, Only first connection is successful, other two fails. In this case my go program output is as follows:
<pre>
root@bc209786c47c:~/abac-compute/internal/main# go run db2.go
================= SQL START ================
execDBSelect:Got Connection.
execDBSelect:Database is reachable
SUCCESS
================= SQL END ================
================= SQL START ================
execDBSelect:Got Connection.
execDBSelect:Unable to reach database SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.17.0.3".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001

FAIL
================= SQL END ================
================= SQL START ================
execDBSelect:Got Connection.
execDBSelect:Unable to reach database SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.17.0.3".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001

FAIL
================= SQL END ================
root@bc209786c47c:~/abac-compute/internal/main# 
</pre>

The issue is why does only one connection succeeds after primary is shutdown. I expect all subsequent connections should also be successful as secondary DB is still up and running.

**Comment by bimalkjha** [comment]
@ugatkal You need to remove `enableAlternateServerListFirstConnect` parameter from your cfg file. Thanks.

**Comment by ugatkal** [comment]
Thanks for the suggestion @bimalkjha. I removed the line enableAlternateServerListFirstConnect from db2dsdriver.cfg. Now it doesn't even connect once after I shut down primary. I want all the subsequent connections to succeed as secondary DB is still up and running. So is there anything else that I can try to resolve this issue?

**Comment by bimalkjha** [comment]
@ugatkal Use below db2dsdriver.cfg file and try:
```
 <configuration>
     <dsncollection>
         <dsn alias="govdb" name="govdb" host="172.17.0.3" port="50000"></dsn>
     </dsncollection>
     <databases>
         <database name="govdb" host="172.17.0.3" port="50000">
         <parameter name="KeepAliveTimeout" value="60"/>
         <parameter name="ConnectionTimeout" value="20"/>
         <parameter name="userid" value="dbusername"/>
         <parameter name="password" value="dbpassword"/>
         <acr>
             <parameter name="enableAcr" value="true"/>
             <parameter name="maxAcrRetries" value="30"/>
             <parameter name="acrRetryInterval" value="5"/>
             <parameter name="enableSeamlessACR" value="true"/>
             <parameter name="affinityFailbackInterval" value="2"/>
             <alternateserverlist>
                 <server name="Server1" hostname="172.17.0.5" port="50000"/>
                 <server name="Server2" hostname="172.17.0.3" port="50000"/>
             </alternateserverlist>
            <affinitylist>
                <list name="list" serverorder="Server1,Server2"/>
            </affinitylist>
            <clientaffinitydefined>
                <client name="client1" hostname="localhost" listname="list"/>
            </clientaffinitydefined>
          </acr>
    </database>
  </databases>
</configuration>
```
