### ISSUE TITLE
Support for Golang version 1.17

### ISSUE THREAD

**Issue by kush-elastic** [ibmdb/go_ibm_db#153]
**Can we have official support for golang version 1.17?**

As we already have golang 1.17 released in August.

**Comment by bimalkjha** [comment]
@kush-elastic Have you tried using golang 1.17 and facing any issue? We expect it should work without any issue and corrected the documentation about it. Thanks.

**Comment by vmathur12** [comment]
@kush-elastic We have updated the document with support for GoLang version 1.17.X. Thanks

**Comment by kush-elastic** [comment]
Thanks a lot, @bimalkjha, and @vmathur12.
I did check with 1.17. but just wanted confirmation from officials.
