### ISSUE TITLE
Can this project be used to connect to "db2 on cloud" in IBMs public cloud

### ISSUE THREAD

**Issue by carstenmichel** [ibmdb/go_ibm_db#156]
**Is your feature request related to a problem? Please describe.**
it is a question

**Describe the solution you'd like**
I am looking for a package that allows to connect to public clouds "db2 on cloud" offering

**Describe alternatives you've considered**
alternative would be another rdbms
**Additional context**

**Comment by carstenmichel** [comment]
got it working, thanks!

**Comment by vallabhsl** [comment]
Hi @carstenmichel 

Considering you have closed the issue, I believe you are able to connect to IBMCloud's DB2 instance. I am able to connect to it too but I am facing an issue.

I have created a ticket for the same but haven't received any response. Can you please check if you have faced this same issue? 

https://github.com/ibmdb/go_ibm_db/issues/181

**Comment by carstenmichel** [comment]
> Hi @carstenmichel
> 
> Considering you have closed the issue, I believe you are able to connect to IBMCloud's DB2 instance. I am able to connect to it too but I am facing an issue.
> 
> I have created a ticket for the same but haven't received any response. Can you please check if you have faced this same issue?
> 
> #181

hey, in my case I just mixed up some of the connection parameters. I was using "only" one DB2 and I deployed the binary directly on the ibm cloud as well. So I was not facing your problem, I am sorry.
