### ISSUE TITLE
Boolean parameters don't work on macOS

### ISSUE THREAD

**Issue by BenJuan26** [ibmdb/go_ibm_db#16]
Using booleans as query parameters on macOS always gives the error:

```
[IBM][CLI Driver] CLI0100E  Wrong number of parameters. SQLSTATE=07001
```

This does not happen on Linux. To reproduce, create a table like this:

```sql
CREATE TABLE booltest(
    id varchar(100) not null primary key,
    active boolean
)
```

Attempt to run this on macOS and observe the failure:

```go
package main

import (
	"database/sql"

	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	db, err := sql.Open("go_ibm_db", "<dsn>")
	if err != nil {
		panic(err)
	}

	_, err = db.Exec(
		`INSERT INTO booltest VALUES(?, ?)`,
		"test", true)
	if err != nil {
		panic(err)
	}
}
```

Run the same code on Linux and observe that the insert is performed correctly.

Note that changing the boolean values in the Go code to integers fixes the issue, but this should not be necessary.

**Comment by akhilravuri1** [comment]
Hi @BenJuan26 
It's Strange that it works in Linux and not in Mac. We use the same code for mac and Linux. We are looking into it. 
Thanks.

**Comment by akhilravuri1** [comment]
Hi @BenJuan26 

This issue is not only on mac but on all platforms. I have updated the code. Please pull the latest code and try it. Let me know if you face any problem.

Thanks.

**Comment by BenJuan26** [comment]
It works with the new changes. Thanks for the quick response.
