### ISSUE TITLE
go get -d can not use anymore in the docker file

### ISSUE THREAD

**Issue by ZacZelner** [ibmdb/go_ibm_db#163]
go version@ latest

Now, when we use this command to download go_ibm_db get this error:
RUN go get -d github.com/ibmdb/go_ibm_db@v0.4.1          
------
 > [ 6/17] RUN go get -d github.com/ibmdb/go_ibm_db@v0.4.1:
#9 0.240 go: go.mod file not found in current directory or any parent directory.
#9 0.240 	'go get' is no longer supported outside a module.
#9 0.240 	To build and install a command, use 'go install' with a version,
#9 0.240 	like 'go install example.com/cmd@latest'
#9 0.240 	For more information, see https://golang.org/doc/go-get-install-deprecation
#9 0.240 	or run 'go help get' or 'go help install'.

If we change the command to be:
RUN go install github.com/ibmdb/go_ibm_db@latest        
------
 > [ 7/17] RUN go install github.com/ibmdb/go_ibm_db@latest:
#10 1.703 go: downloading github.com/ibmdb/go_ibm_db v0.4.1
#10 1.767 package github.com/ibmdb/go_ibm_db is not a main package
------
@bimalkjha

**Comment by vmathur12** [comment]
@ZacZelner  Can you please run go get -d github.com/ibmdb/go_ibm_db it will download the version 1.15.14.

**Comment by ZacZelner** [comment]
Hi @vmathur12,  I just tried RUN go install github.com/ibmdb/go_ibm_db@v0.4.1         

We still got this error when we try to download it in our dockerfile.
------
 > [ 7/17] RUN go install github.com/ibmdb/go_ibm_db@v0.4.1:
#10 1.748 go: downloading github.com/ibmdb/go_ibm_db v0.4.1
#10 2.359 package github.com/ibmdb/go_ibm_db is not a main package
------
executor failed running [/bin/sh -c go install github.com/ibmdb/go_ibm_db@v0.4.1]: exit code: 1

Our docker file:

FROM golang:latest

RUN sed -i s@/deb.debian.org/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN apt-get clean
RUN apt-get update -y && apt-get install libxml2 -y


RUN CGO_ENABLED=0 go install -a std

ENV GOPROXY https://goproxy.cn,direct
#Env setting
ENV GOPATH /go
ENV GOBIN /go/bin
ENV PATH $PATH:$GOBIN:/go/bin

RUN go install github.com/tools/godep@latest
RUN go install github.com/ibmdb/go_ibm_db@v0.4.1

**Comment by nishchaysk98** [comment]
@ZacZelner even i faced the same issue, if we see error message, it is asking for main package, so main func is present in installer folder, so i tried this: and it's working for me 
http://github.com/ibmdb/go_ibm_db/installer@v0.4.1
Hope it will be helpful

**Comment by ZacZelner** [comment]
Thanks! @nishchaysk98 , it works! problem solved.
