### ISSUE TITLE
build db_exporter undefined reference to SqloCosClient::SqloCosClient_toString(unsigned long, char*)

### ISSUE THREAD

**Issue by yangliyl** [ibmdb/go_ibm_db#165]
- os Version: CentOS Linux release 7.9.2009 (Core)
- cli-driver Version: v11.5.7
- Db2 Server Version:
- go Version: go 1.17
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.8"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/db2_exporter/go.mod"
CGO_CFLAGS="-I/root/db2_exporter/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/root/db2_exporter/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build59432829=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

<pre>
echo $LD_LIBRARY_PATH
/root/m8dmp-db2-exporter/clidriver/lib
</pre>

Steps to Reproduce:

1.  go build
<pre>
go build
# github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: warning: libxml2.so.2, needed by /root/db2_exporter/clidriver/lib/libdb2.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /root/db2_exporter/clidriver/lib/libdb2.so: undefined reference to `SqloCosClient::SqloCosClient_toString(unsigned long, char*)'
collect2: error: ld returned 1 exit status
</pre>

**Comment by dorudumitru-hh** [comment]
Do you mind sharing your solution?
