### ISSUE TITLE
Connection being opened outside go_ibm_db control

### ISSUE THREAD

**Issue by kushaal-veijay** [ibmdb/go_ibm_db#166]
I was debugging an issue where in my database query were taking a long time. I am using connection pool defined for 100 connection. While debugging using pprof, I found that the connection is being opened directly in sql.go without the invocation of pool.Open. 

```
12 @ 0x40953b 0xa4d727 0xa4ec26 0xa4e65c 0xa517eb 0x7a4713 0x797044 0x79a146 0x799e54 0x7b4c30 0x7b42ee 0xbcf9ca 0xbcf90f 0xbdceef 0xdde998 0x477801
#	0xa4d726	github.com/ibmdb/go_ibm_db/api._Cfunc_SQLDriverConnectW+0x46						_cgo_gotypes.go:362
#	0xa4ec25	github.com/ibmdb/go_ibm_db/api.SQLDriverConnect.func1+0xa5						/workdir/.build/golib/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/api/zapi_unix.go:59
#	0xa4e65b	github.com/ibmdb/go_ibm_db/api.SQLDriverConnect+0x7b							/workdir/.build/golib/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/api/zapi_unix.go:59
#	0xa517ea	github.com/ibmdb/go_ibm_db.(*Driver).Open+0x1aa								/workdir/.build/golib/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/conn.go:29
#	0x7a4712	database/sql.dsnConnector.Connect+0x52									/usr/lib/golang/src/database/sql/sql.go:707
#	0x797043	database/sql.(*DB).conn+0x183										/usr/lib/golang/src/database/sql/sql.go:1301
#	0x79a145	database/sql.(*DB).query+0x65										/usr/lib/golang/src/database/sql/sql.go:1623
#	0x799e53	database/sql.(*DB).QueryContext+0xd3									/usr/lib/golang/src/database/sql/sql.go:1605
#	0x7b4c2f	github.com/jmoiron/sqlx.(*DB).QueryxContext+0x8f							/workdir/.build/golib/pkg/mod/github.com/jmoiron/sqlx@v1.3.4/sqlx_context.go:161
#	0x7b42ed	github.com/jmoiron/sqlx.SelectContext+0xad								/workdir/.build/golib/pkg/mod/github.com/jmoiron/sqlx@v1.3.4/sqlx_context.go:55
#	0xbcf9c9	github.com/jmoiron/sqlx.(*DB).SelectContext+0x389							/workdir/.build/golib/pkg/mod/github.com/jmoiron/sqlx@v1.3.4/sqlx_context.go:140
#	0xbcf90e	github.ibm.com/sec-ci/abac-compute/internal/dao.DBSelect+0x2ce						/workdir/internal/dao/dao_utils.go:202
#	0xbdceee	github.ibm.com/sec-ci/abac-compute/internal/dao.(*ABACEntitlementDAO).GetEntitlement+0x22e		/workdir/internal/dao/entitlement_dao.go:79
#	0xdde997	github.ibm.com/sec-ci/abac-compute/internal/executor/operations.UserOperations.publishAssgnEvent+0x97	/workdir/internal/executor/operations/user.go:76
```

I was trying to trace this down to understand why this could happen and that's when I found this code flow https://github.com/golang/go/blob/0e08b02ac54c9232759704812f41a5836f920cff/src/database/sql/sql.go#L1704. Looks like if there is a bad connection then sql.go would go ahead and create a new connection and go_ibm_db pool(https://github.com/ibmdb/go_ibm_db/blob/0de330886fa63cee922e08933ff7a25b0b1d6842/pooling.go#L20) will have no knowledge of this connection. I exepected that connection would be opened only pool.Open which is not the case. Is my understanding correct? If so, how do I fix this issue?

**Comment by vmathur12** [comment]
@kushaal-veijay 
When the number of connections go beyond PoolSize and a new connection is created directly using sql.open instead of pool.Open and this connection is will not be kept in used pool. This connection will close once the application completes a transaction and return to user.
Could please share the go code.
 Thanks

**Comment by kushaal-veijay** [comment]
@vmathur12 I am not talking about the connection that are being opened when the we have exhausted the pool limit. I am talking about the case where in if db/sql.go receives a stale connection in this block https://github.com/golang/go/blob/61fc5df6897544d8ecf8efd5b39648a6bd121ec8/src/database/sql/sql.go#L1703, it will create a new connection, using this call https://github.com/golang/go/blob/61fc5df6897544d8ecf8efd5b39648a6bd121ec8/src/database/sql/sql.go#L1058

**Comment by vmathur12** [comment]
@kushaal-veijay Can you please use the latest version go_ibm_db v0.4.2 and check whether you are still facing the problem. We have set the maximum number of connections impose a limit on the number of open connections and the new database connection will wait for an existing operation to finish. Thanks
