### ISSUE TITLE
Connection failed with error GSKit Error: 408

### ISSUE THREAD

**Issue by idaZKG** [ibmdb/go_ibm_db#170]
Hello,

We tried to connect to db2 using ssl on a Windows machine with following **connection string format**:
```
"HOSTNAME=xxx;DATABASE=xxx;PORT=<sslportnumber>;UID=xxx;PWD=xxx;SECURITY=SSL;SSLSERVERCERTIFICATE=xxx.arm"
```
but we get this **error**:
```
SQLDriverConnect: {42724} [IBM][CLI Driver] SQL1109N The command was not processed because the database manager failed to load the following DLL: "GSKit Error: 408". SQLSTATE=42724\r\n
```
We also verify that we could successfully connect to the database using the same port from the Windows client Db2 Command Window.

How can we resolve this issue?

**Comment by bimalkjha** [comment]
@idaZKG Make sure you are passing the path of SSLServerCertificate correctly. If path has space, enclose it between quotes. This gskit error tells about some permission issue. Run the process as administrator.
If still fails, find the `ibmdb/clidriver/bin/db2trc` file and collect trace files for test program as below:
```
cd .../github.com/ibmdb/clidriver/bin
db2trc on -f 1.trc
go run testfile.go
db2trc off
db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
```
zip all 1.* files and share here. Thanks.

**Comment by bimalkjha** [comment]
Closing the issue due to inactivity. Once you share the trace files here, we can look into that. Thanks.
