### ISSUE TITLE
No error when passing invalid credentials and facing error while executing queries with valid credentials.

### ISSUE THREAD

**Issue by anantha1999** [ibmdb/go_ibm_db#172]
When executing the code from example2.go in the documentation, queries are taking way too long to execute and ends up giving the below error - 
```
Error dropping the table :SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "158.175.131.250".  Communication function detecting the error: "recv".  Protocol specific error code(s): "104", "*", "0".  SQLSTATE=08001

SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "158.176.91.122".  Communication function detecting the error: "recv".  Protocol specific error code(s): "104", "*", "0".  SQLSTATE=08001
```

Also the code doesn't throw any error on passing wrong credentials in the connection string. Any idea on what is happening? And how do I fix this issue?

**Comment by bimalkjha** [comment]
@anantha1999 On Linux system if you are getting Protocol specific error code 104, means your firewall is blocking connection. Check details and how to resolve it here under error code 104: https://www.ibm.com/docs/en/db2/11.5?topic=errors-sql30081n-tcpip-communication

A connected partner closes the connection.
Check any timeout limit on partner side, such as firewall, application, Db2 CLI layer.

If the error is reported on a client application that uses ibm_db to connect to the Db2 server, complete the following steps:
Disable the Db2 CLI timeout.
Add QUERYTIMEOUTINTERVAL=0 to connection string.
Check whether a firewall exists between the client and the server.

Note: Error SQL30081 can occur when you are connecting to a database by using a TCPIP connection. If the database connection is local and is cataloged by using a different alias name than the database name, the error can occur. If you get the SQL30081 error, make sure that the database is not cataloged by using a different alias name than the name of the database on the server.
