### ISSUE TITLE
SQLDriverConnect: {HY000} [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3".

### ISSUE THREAD

**Issue by DaisyYangl** [ibmdb/go_ibm_db#179]
hello team,
I run go test command, and met the following error:
SQLDriverConnect: {HY000} [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3".

These are what I did : (Mac Monterey 12.4)
1. Go to installer folder  (/Users/xxx/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.1/installer) and  run setup.go file
2. go env -w CGO_CFLAGS=-I/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/include
    go env -w CGO_LDFLAGS=-L/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/lib
3.  In /Users/xxx/.bash_profile  add the following paths:
export DB2HOME=/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$DB2HOME/lib
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib

Could you please give some suggestion?   Thanks so much!

**Comment by vmathur12** [comment]
Hi @DaisyYangl 
Could you please paste the output of 
for env in $DB2HOME $CGO_CFLAGS $CGO_LDFLAGS $DYLD_LIBRARY_PATH; do echo $env; done
go env
Thanks

**Comment by DaisyYangl** [comment]
echo $DB2HOME
/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver

echo $DYLD_LIBRARY_PATH
:/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/lib:/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/lib:/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/lib

echo $CGO_CFLAGS
-I/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/include

echo $CGO_LDFLAGS
-L/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/lib

This is the output I ran 'go env'

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxx/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io/,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-I/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ym/k190cgtj1yvd177vp07_bfmh0000gn/T/go-build895877693=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by DaisyYangl** [comment]
Hello, I changed my golang version to 1.16.5,  the same error.

**Comment by vmathur12** [comment]
@DaisyYangl 
Sorry for the delay in response. Could you please check the permission to run the test case and also check symbolic link for libdb2.dylib library (Refer https://github.com/ibmdb/go_ibm_db/issues/139)
Thanks

**Comment by bimalkjha** [comment]
@DaisyYangl SQL10007N error comes if you have already a Db2 client/server installed in your system with different permission. You have set most of the environment variables correctly but you have not set the PATH environment variable. Please set PATH using command `export PATH=/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/bin:/Users/xxx/go/pkg/mod/github.com/ibmdb/clidriver/lib:$PATH`  and run your test program. It should work fine. Let us know the status. Thanks.

**Comment by bimalkjha** [comment]
If it does not work, please share the output of `db2level` and `db2cli validate` commands. Thanks.

**Comment by bimalkjha** [comment]
Closing the issue due to lack of response. Once you share the requested info, we can reopen it. Thanks.
