### ISSUE TITLE
unsupported column type -99

### ISSUE THREAD

**Issue by freezingsun** [ibmdb/go_ibm_db#18]
err := db.Query("select itsdout from xxx")
itsdout column is clob

**Comment by akhilravuri1** [comment]
Hi @freezingsun 
As of now, CLOB (-99) is not supported in our driver we are trying to support that datatype in the next release. 
Thanks,
AKhil

**Comment by akhilravuri1** [comment]
Hi @freezingsun 
CLOB datatype has been added. Pull the latest code and use it.
Thanks,
Akhil
