### ISSUE TITLE
Not able to connect to a new DB2 instance as soon as previous connection is closed

### ISSUE THREAD

**Issue by vallabhsl** [ibmdb/go_ibm_db#181]
I have created 2 DB2 instances on ibmcloud. I am trying to connect to each of the databases one by one. When one connection is established and data is received we are closing the database connection. Immediately, I am changing the host, credentials and port in the script file and when I am building it using go build and running it with the 2nd DB2 instance details, it gets stuck on db.QueryContext() and later gives the following error.

`SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "141.125.88.202". Communication function detecting the error: "recv". Protocol specific error code(s): "104", "*", "0". SQLSTATE=08001`

Surprisingly, if I run the script again without go build (same binary with 2nd DB details), the script runs.

I have confirmed there is no firewall issue. If the script runs for 1st DB2 instance, it should run for the other too.

Steps to Reproduce:

1. Enter details of 1st DB2 instance. Run "go build -o main" followed by "./main". You will get response from the query.
2. Immediately, update the details of 2nd DB2 instance, run "go build -o main" followed by "./main". The flow gets stuck on db.QueryContext() and gives the above mentioned error after sometime.
3. Now run ./main again without making any changes and any new build. The script runs perfectly again.

I am wondering why is the script not running immediately after the detail updates? Is it caching the 1st DB details somewhere? If yes, how do I stop caching?

Note: 
1. We are removing the config file always in code at earlier stages to always have new configuration.
2. For both the DB2 instances the database is same i.e bludb (default DB name in IBMCloud) but as we are deleting the earlier DB2 configurations, I believe it shouldn't create any issue.

Script:
[main.zip](https://github.com/ibmdb/go_ibm_db/files/9683291/main.zip)

**Comment by vallabhsl** [comment]
I created a ticket on IBM cloud as well and they have confirmed there is no issue from their end. Seems like some caching is done on the previous connection and that is why it is getting timed out during the subsequent request.

**Comment by vmathur12** [comment]
@vallabhsl 
I am unable to reproduce the issue. I have attached my scripts please check and let me know if any discrepancy. If you are still facing the issue, please provide the db2 traces.
Run the following db2 trace commands and share all the generated files
db2trc on -t -f trc.dmp
script.sh
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -cli trc.dmp trc.cli
db2trc fmt -c trc.dmp trc.drda
Thanks

[main.zip](https://github.com/ibmdb/go_ibm_db/files/9927364/main.zip)

**Comment by bimalkjha** [comment]
@vallabhsl Could you please share the requested info so that we can progress on this issue? Thanks.

**Comment by vallabhsl** [comment]
@bimalkjha Sure, I will check and let you know.

**Comment by vallabhsl** [comment]
Hi @bimalkjha. I was using the query function directly which was caching somethings I feel because one of my DB connection needed SSL and the other did not.
I updated my code with the prepared statement like you did in yours and it is not caching the older data. So I am not getting the issue.

Closing the issue as I am not getting the issue with above mentioned change.
Thanks for the help.
