### ISSUE TITLE
Context with timeout will not prevent long running queries

### ISSUE THREAD

**Issue by drognisep** [ibmdb/go_ibm_db#182]
- os Version: Windows 10
- cli-driver Version: latest
- Db2 Server Version: iSeries, not sure which version
- go Version: 1.18
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\user\AppData\Local\go-build
set GOENV=C:\Users\user\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\user\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\user\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\user\AppData\Local\Temp\go-build226566691=/tmp/go-build -gno-record-gcc-switches

</pre></details>

Steps to Reproduce:

1. Create a context.WithTimeout
2. Pass that context to ExecContext which is running a long running query
3. Observe that the long running query will run beyond the lifetime of the context

**Comment by cvigo** [comment]
ExecContext should start a goroutine that issues a `SQLCancel` to the statement handle when the context is done

**Comment by drognisep** [comment]
I did some further investigation on this. It turns out to be an issue unrelated to context or even the Go code. I was evaluating Go interacting with iSeries, assuming that we have the licensing required to do so. It turns out that we don't, but that underlying issue seems to manifest itself as just hanging. We've replicated the exact same behavior using the db2cli driver directly, so it's not even about the Go code.

That being the case, this doesn't seem to be an issue with the Go wrapper, but rather a problem with db2cli not reporting an error - just sitting there - when the required licensing isn't in place. I'll go ahead and close this issue.

**Comment by cvigo** [comment]
The DB2 cli is not aware of any Go Context obviously. But the Go Driver can call SQLClose when the Context is done (therefore no one is waiting for que query/transaction anymore any there is no point on keeping the thread waiting maybe forever).

**Comment by nwsm** [comment]
@cvigo Regardless of the DB2 cli knowing that the context timeout has been exceeded (and therefore not cancelling the query on the DB2 side), I'm not seeing ExecContext exit early.

In my case:

```
	ctx, cancel := context.WithTimeout(ctx, time.Second*time.Duration(30))
        defer cancel()
	query := 'long running query'
	_, err := conn.ExecContext(ctx, query)
	select {
	// should trigger when cancel is called or context times out
	case <-ctx.Done():
		// context.Canceled if canceled, context.DeadlineExceeded if timed out
		log.Info(ctx.Err().Error())
	default:
		log.Info("Call finished")
	}
```

If the long running query takes 1 minute, the code hangs for the full minute, and then tells me the context deadline exceeded, even though the timeout was 30 seconds. Am I doing something wrong or is this the state of the project?

My hunch is that this blocking call is the culprit? https://github.com/ibmdb/go_ibm_db/blob/master/stmt.go#L111

**Comment by cvigo** [comment]
@nwsm I would say your code is doing as expected.
`conn.ExecContext` does not
take any cancelling action when the passed context cancels. As this is quite different for each DBM, the Go Library delegates this responsibility to the driver.
