### ISSUE TITLE
Installer setup program fails.

### ISSUE THREAD

**Issue by nwsm** [ibmdb/go_ibm_db#186]
The installer setup program fails when the DB2 HOME environment variable is set.

- os Version: macOS Monterey 12.6
- cli-driver Version: v0.4.1
- Db2 Server Version: NA
- go Version: 1.18.7 darwin/amd64
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ericnewsom/Library/Caches/go-build"
GOENV="/Users/ericnewsom/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ericnewsom/go/pkg/mod"
GONOPROXY="github.ibm.com"
GONOSUMDB="github.ibm.com"
GOOS="darwin"
GOPATH="/Users/ericnewsom/go"
GOPRIVATE="github.ibm.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.7"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kx/kc2jwzb50xv8l661p5fx9ns00000gn/T/go-build2967435925=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

Steps to Reproduce:

1. Set the `IBM_DB2_HOME` (or `DB2HOME` depending on version) environment variable.
2. Run `go run installer/setup.go`.

Output:

`clidriver is already present in this path `

**Comment by nwsm** [comment]
https://github.com/ibmdb/go_ibm_db/pull/185

**Comment by vmathur12** [comment]
@nwsm 
Thanks for the pull request. Merged the pull request.
