### ISSUE TITLE
error while loading shared libraries: libcrypt.so.1

### ISSUE THREAD

**Issue by WTaoGitHub** [ibmdb/go_ibm_db#196]
- os Version: red hat 9.0
- cli-driver Version: v11.5.5
- Db2 Server Version: 
- go Version: 1.18.8
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="s390x"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_s390x"
GOVCS=""
GOVERSION="go1.18.8"
GCCGO="gccgo"
AR="ar"
CC="s390x-linux-gnu-gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3939994960=/tmp/go-build -gno-record-gcc-switches"</pre></details>

Steps to Reproduce:

1. On an vm server of IBM Z system,  red hat v9.0.
2. download and setup the clidriver
    https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/v11.5.5/s390x64_odbc_cli.tar.gz
3. execute the command of db2cli inside the package. it gives an error 
    [root@ssss bin]# ./db2cli
./db2cli: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

**Comment by bimalkjha** [comment]
@WTaoGitHub Your system has missing package, hence error. Similar issue is discussed here: https://unix.stackexchange.com/questions/283607/libraries-libcrypto-so-1-0-0-cannot-open-shared-object-file-no-such-file-or-d

You need to install libssl1.0.0 and libssl-dev on your system. Thanks.

**Comment by WTaoGitHub** [comment]
@bimalkjha
hi, error says `libcrypt.so.1`, but `libcrypto.so.1.0.0`, I think they are not the same.

And i tried to install ` libssl1.0.0` and `libssl1.0-dev` with yum, it didn't find either.

My server is a Red hat 9.0 on IBM Z system.

**Comment by bimalkjha** [comment]
@WTaoGitHub libcrypto.so.1.0.0, libcrypto.so.1.0, libcrypto.so.1, libcrypto.so - all are same. If any one is present, create soft link for others pointing to the existing one.
You need to find the right libssl package for RHEL9.0 and install in the system. libcrypto is system library which comes with Operating System and not with ibm_db. If you can not find way to install it, contact your system admin or contact RHEL support. Thanks.
