### ISSUE TITLE
ibmdb/go_ibm_db pooling vs database/sql pooling

### ISSUE THREAD

**Issue by juguhan** [ibmdb/go_ibm_db#198]
According to https://pkg.go.dev/database/sql#Open, database/sql already maintains its own pool: `The returned DB is safe for concurrent use by multiple goroutines and maintains its own pool of idle connections. Thus, the Open function should be called just once.`

May I know the purpose / advantage of ibmdb/go_ibm_db pool?  
Is there going to be any issue if I just use database/sql pool?

**Comment by vmathur12** [comment]
@juguhan With ibmdb/go_ibm_db pool, set the maximum number of open connections SetMaxOpenConns imposes a limit on the number of open connections.  Past this limit, new database operations will wait for an existing operation to finish. The connection pool implementation also has thread-safe to protect against race conditions resulted from concurrent requests and achieve thread-safe by using mutex. Any issue with go_ibm_db pool we will give support. 
You can use database/sql pool, but any issue in this we cannot help you.
Thanks

**Comment by juguhan** [comment]
> @juguhan With ibmdb/go_ibm_db pool, set the maximum number of open connections SetMaxOpenConns imposes a limit on the number of open connections. Past this limit, new database operations will wait for an existing operation to finish. The connection pool implementation also has thread-safe to protect against race conditions resulted from concurrent requests and achieve thread-safe by using mutex. Any issue with go_ibm_db pool we will give support. You can use database/sql pool, but any issue in this we cannot help you. Thanks

Thanks

**Comment by juguhan** [comment]
@vmathur12 I have some more questions regarding ibmdb/go_ibm_db pool.

database/sql pool has similar feature: https://pkg.go.dev/database/sql#DB.SetMaxOpenConns, and it's also thread safe according to https://go.dev/doc/database/manage-connections. 

In ibmdb/go_ibm_db pool code, it seems a "pool connection" is opened using database/sql's `sql.Open` 
https://github.com/ibmdb/go_ibm_db/blob/e3f0baa1c935ee5c33087e3dfcb9023a509df710/pooling.go#L107
However, database/sql's `sql.Open` returns an object maintains its own "pool" https://pkg.go.dev/database/sql#Open.
So that each "connection" created by `ibmdb/go_ibm_db pool` is actually a `database/sql pool`, and an `ibmdb/go_ibm_db pool` is a pool of `database/sql pool`.  
Also, according to `database/sql pool` [doc](https://pkg.go.dev/database/sql#Open) , database/sql's `sql.Open` function should be called just once. 
However, `ibmdb/go_ibm_db pool` calls database/sql's `sql.Open` function whenever a new `ibmdb/go_ibm_db pool connection` is created.  
This does not look correct to me.
May I know if this is intended, and the reason behind this?

I also have run quick performance comparison between ibmdb/go_ibm_db pool and ibmdb/go_ibm_db pool
Query to run:
```sql
INSERT INTO DMAP_ENTRIES(DMAP_KEY, DMAP_PARTITION, DMAP_VALUE, DMAP_EXPIRY) VALUES (?, ?, ?, ?)
```
ibmdb/go_ibm_db pool: ~6.5 sec to insert 1000 records.
database/sql managed pool: ~750 ms to insert 1000 records.  
It seems the database/sql managed pool has better performance.  

FYI, there is a postgres golang library pgx, which also implements its own pool: pgxpool, https://github.com/jackc/pgx.  
pgx can be either used [through database/sql](https://github.com/jackc/pgx/wiki/Getting-started-with-pgx-through-database-sql) or [pxgpool](https://github.com/jackc/pgx/wiki/Getting-started-with-pgx#using-a-connection-pool).  
The pgxpool opens new connections using its own dialer function instead of using  database/sql's `sql.Open`.  
This is the correct way to implement the pool according to my understanding.

**Comment by vmathur12** [comment]
@juguhan We have introduce the connection pool concept in ibmdb/go_ibm_db when database/sql  was not supporting connection pool. So, we have added the code for connection pool in  ibmdb/go_ibm_db. Now database/sql support connection pool, you can use database/sql pool also. Thanks

**Comment by juguhan** [comment]
> @juguhan We have introduce the connection pool concept in ibmdb/go_ibm_db when database/sql was not supporting connection pool. So, we have added the code for connection pool in ibmdb/go_ibm_db. Now database/sql support connection pool, you can use database/sql pool also. Thanks

Thanks.
But it seems database/sql supports pool since go1 (the earliest version I can find) https://pkg.go.dev/database/sql@go1#DB

**Comment by vmathur12** [comment]
@juguhan I have run quick performance on ibmdb/go_ibm pool to insert 1000 records in my environment. It took ~2.6 sec to insert 1000 records. Readme.md has sample example for limit on the number of connections and pool.Init function create connection in advance with N number of connections. You can use database/sql pool also. I am closing this issue. Thanks
