### ISSUE TITLE
SP call exception - index out of range

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#20]
Hi team, 
Got one exception 'index out of range'. Can you please have a check?

Code sample:
```
sql := "call user666.setValue('DESCRIPTION', '" + nodeDesc + "', '" + nodeName + "', ?, ?);"

	var numUpdated int
	var diags string
	_, err = db.Exec(sql, numUpdated, diags)
	if err != nil {
		return "error", err
	}
```

Got exception in runtime,
```
2019/05/29 05:15:15 http: panic serving 127.0.0.1:33442: runtime error: index out of range
goroutine 32 [running]:
net/http.(*conn).serve.func1(0xc0000c4c80)
        /opt/go/src/net/http/server.go:1746 +0xd0
panic(0xa259a0, 0x1196eb0)
        /opt/go/src/runtime/panic.go:513 +0x1b9
github.com/ibmdb/go_ibm_db.(*Parameter).BindValue(0xc0000c28e8, 0xc000010001, 0x1, 0x9e9a00, 0x1202d60, 0x0, 0x0)
        /opt/gospace/src/github.com/ibmdb/go_ibm_db/param.go:56 +0x8f7
github.com/ibmdb/go_ibm_db.(*ODBCStmt).Exec(0xc0000c2910, 0xc0003cc6e0, 0x2, 0x2, 0x2, 0x9e9a00)
        /opt/gospace/src/github.com/ibmdb/go_ibm_db/odbcstmt.go:105 +0xb5
github.com/ibmdb/go_ibm_db.(*Stmt).Exec(0xc0001f6b10, 0xc0003cc6e0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
        /opt/gospace/src/github.com/ibmdb/go_ibm_db/stmt.go:62 +0xc9
database/sql.ctxDriverStmtExec(0xb9c1c0, 0xc00002e0b0, 0xb9c480, 0xc0001f6b10, 0xc0000c2960, 0x2, 0x2, 0x2, 0x2, 0x0, ...)
        /opt/go/src/database/sql/ctxutil.go:77 +0x16b
database/sql.resultFromStatement(0xb9c1c0, 0xc00002e0b0, 0xb9ad80, 0xc000562550, 0xc00065f420, 0xc00065f760, 0x2, 0x2, 0x0, 0x0, ...)
        /opt/go/src/database/sql/sql.go:2342 +0x13e
database/sql.(*DB).execDC(0xc000468180, 0xb9c1c0, 0xc00002e0b0, 0xc0003c8900, 0xc00065f598, 0xc0004ea4e0, 0x5c, 0xc00065f760, 0x2, 0x2, ...)
        /opt/go/src/database/sql/sql.go:1487 +0x2df
database/sql.(*DB).exec(0xc000468180, 0xb9c1c0, 0xc00002e0b0, 0xc0004ea4e0, 0x5c, 0xc00065f760, 0x2, 0x2, 0xad4f01, 0x9, ...)
        /opt/go/src/database/sql/sql.go:1448 +0x139

```

It seems that the fields in the statement were parsed incorrectly.
It happens in the current code level in master("ccf5f6964a2a66adeca163cd6a224f860fc23a41"),  but the SP works well in commit "65246ebaf88e37ea97ba64aebc919e1c9fd1a06e".

Thank you.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 
All the columns present in the Stored procedure are IN type?
Thanks,
Akhil

**Comment by maxatcn** [comment]
No, the last two are OUT returned from BigSQL .  I defined two variables to accept them(numUpdated, and diags).
Thanks

**Comment by akhilravuri1** [comment]
Hi @maxatcn 
can you check the same code with this commit("65246ebaf88e37ea97ba64aebc919e1c9fd1a06e") in bigsql. 
And update me.
Thanks,
Akhil

**Comment by maxatcn** [comment]
@akhilravuri1 , as tested, the issue occurred since commit ("b86d7e630ee4dceca04df4be24508592c1906d1f"),   --String termination modified

Before this, work fine. 

Thanks.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 
can you execute the queries without ";" at the end in BigSQL at this 65246ebaf88e37ea97ba64aebc919e1c9fd1a06e ?

Sorry, As you know I don't have BigSQL setup. So you have to do it for me.

Thanks,
Akhil

**Comment by maxatcn** [comment]
Hi  @akhilravuri1 , 
as tested, without ';',  at commit `65246eb`, it works fine, without any error.

Also, without ";", the query failed in current commit, with same error.

Thanks.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 
Sorry for the delay.
I have updated the code and tested it, But not with BigSQL Database. So can you please clone the changes and test it with your application.
If there are any issues please update me.

Thanks,
Akhil

**Comment by maxatcn** [comment]
Verified. It works fine now.  Thank you @akhilravuri1 . Let me close it.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 
Can u try create schema  query now?

**Comment by maxatcn** [comment]
Sorry for the late reply.  @akhilravuri1 .
Creating Schema also works at the moment. 

Thanks.
