### ISSUE TITLE
index out of range [2021] with length 2021 

### ISSUE THREAD

**Issue by freeman983** [ibmdb/go_ibm_db#200]
Hello, I will get this error after querying after writing a lot of Chinese in the CLOB type field of the table. Had the same problem on DBCLOB type.

```
package main

import (
	"context"
	"database/sql"
	_ "github.com/ibmdb/go_ibm_db"

	"fmt"
)

func main() {

	dsn := fmt.Sprintf("HOSTNAME=%s;PORT=%s;PROTOCOL=TCPIP;UID=%s;PWD=%s;DATABASE=%s", "172.19.33.115", "50000", "db2inst1", "123456", "testdb")

	fmt.Println("u.FormatDSN():", dsn)
	db, err := sql.Open("go_ibm_db", dsn)
	if err != nil {
		fmt.Sprintf("Error on open: %s", err)
		return
	}

	defer db.Close()

	ctx := context.Background()
	test_conn, test_err := db.Conn(ctx)
	if test_err != nil {
		fmt.Sprintf("Error on connect: %s", test_err)
		return
	}

	if test_conn != nil {
		test_conn.Close()
	}

	/****
	CREATE TABLE TEST
	(
	    Id VARCHAR(256),
	    A CLOB(10485760),
		AAA DBCLOB(90485760)
	)

	INSERT INTO  TEST ( ID,A,AAA ) values ( '1','ASDF','
	ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfddojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口跨境电商呢是否色我任务二温热一u混改规格及一大是大非spot体育透露出是看比是地工位侮辱wit进行逆向靠行政村 年付科技你防洪纪念塔回头换件她娘家人可接受的你记得捡对酒当歌加拿大籍电脑管家ojhgfdd阿迪发的那个点击那个都到缴纳不放家能飞机杯那附近半技能书而毫无然后文件那么一入口
	' );


			****/

	queryTypes := "select * from TEST;"

	rows, err := db.Query(queryTypes)
	if err != nil {
		fmt.Println("Error on query:", err)
		panic(err)
	}

	//get columns name
	colsName, err := rows.Columns()
	if err != nil {
		fmt.Println("Error on Columns:", err)

		panic(err)
	}

	//total columns
	totalColumns := len(colsName)

	// create a slice of interface{}'s to represent each column,
	// and a second slice to contain pointers to each item in the columns slice
	columns := make([]interface{}, totalColumns)
	recordPointers := make([]interface{}, totalColumns)
	for i := range columns {
		recordPointers[i] = &columns[i]
	}

	//record destination

	for rows.Next() {

		// Scan the result into the record pointers...
		if err := rows.Scan(recordPointers...); err != nil {
			fmt.Sprintf("err:%v", err)
			panic(err)
		}

	}

}


```

`
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/chengyong/Work/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/8w/l425tlz104x_7xjd7jwp9pgr0000gn/T/GoLand/___48go_build_shuaninfo_com_test_imb shuaninfo.com/test/imb #gosetup
/private/var/folders/8w/l425tlz104x_7xjd7jwp9pgr0000gn/T/GoLand/___48go_build_shuaninfo_com_test_imb
u.FormatDSN(): HOSTNAME=172.19.33.115;PORT=50000;PROTOCOL=TCPIP;UID=db2inst1;PWD=sqldev_test123;DATABASE=testdb
panic: runtime error: index out of range [2023] with length 2023

goroutine 1 [running]:
github.com/ibmdb/go_ibm_db.removeNulls(...)
        /Users/chengyong/Work/go/src/shuaninfo.com/test/vendor/github.com/ibmdb/go_ibm_db/utf16.go:64
github.com/ibmdb/go_ibm_db.(*BaseColumn).Value(0xc00005bc70?, {0xc000d00000?, 0xfce, 0xc00005bca8?})
        /Users/chengyong/Work/go/src/shuaninfo.com/test/vendor/github.com/ibmdb/go_ibm_db/column.go:183 +0x453
github.com/ibmdb/go_ibm_db.(*BindableColumn).Value(0xc000b8c000, 0x10001?, 0x0?)
        /Users/chengyong/Work/go/src/shuaninfo.com/test/vendor/github.com/ibmdb/go_ibm_db/column.go:292 +0xbf
github.com/ibmdb/go_ibm_db.(*Rows).Next(0xc000b8e000, {0xc000b920c0, 0x3, 0x203000?})
        /Users/chengyong/Work/go/src/shuaninfo.com/test/vendor/github.com/ibmdb/go_ibm_db/rows.go:116 +0x102
database/sql.(*Rows).nextLocked(0xc000b90000)
        /usr/local/go/src/database/sql/sql.go:3008 +0x111
database/sql.(*Rows).Next.func1()
        /usr/local/go/src/database/sql/sql.go:2986 +0x2f
database/sql.withLock({0x4105158, 0xc000b90030}, 0xc00005bdd0)
        /usr/local/go/src/database/sql/sql.go:3437 +0x8c
database/sql.(*Rows).Next(0xc000b90000)
        /usr/local/go/src/database/sql/sql.go:2985 +0x6f
main.main()
        /Users/chengyong/Work/go/src/shuaninfo.com/test/imb/main.go:79 +0x3cf

Process finished with the exit code 2

`

- os Version: mac OS  10.15.7
- cli-driver Version: v0.4.2
- Db2 Server Version:
- go Version: 1.18
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/chengyong/Library/Caches/go-build"
GOENV="/Users/chengyong/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/chengyong/Work/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/chengyong/Work/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/chengyong/Work/go/src/shuaninfo.com/sqldev/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8w/l425tlz104x_7xjd7jwp9pgr0000gn/T/go-build463281501=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

Steps to Reproduce:

1.
2.

**Comment by vmathur12** [comment]
@freeman983 Pushed the fix. Please test it and let me know if  you face the issue. Thanks

**Comment by vmathur12** [comment]
@freeman983 Closing the issue. Let me know if you are facing this issue again. Thanks

**Comment by freeman983** [comment]
@vmathur12 I tested it and there is no error, thank you very much!
