### ISSUE TITLE
../../go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.2/api/api_unix.go:13:11: fatal error: sqlcli1.h: No such file or directory

### ISSUE THREAD

**Issue by dartagnanli** [ibmdb/go_ibm_db#202]
Hi,I am newer,now occur a problem.
this is my code
```go
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	con := "HOSTNAME=host;DATABASE=name;PORT=number;UID=username;PWD=password"
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)
	}
	db.Close()
}

```
when i run the command `CGO_ENABLED=1 GOOS=linux go build app.go`,i got this
```console
# github.com/ibmdb/go_ibm_db/api
../../go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.2/api/api_unix.go:13:11: fatal error: sqlcli1.h: No such file or directory
   13 | // #include <sqlcli1.h>
      |           ^~~~~~~~~~~
compilation terminated.
```
what can i do? Thanks!

**Comment by vmathur12** [comment]
@dartagnanli, 
This error occurs when environment variables are not set properly or when some files are missing.
Could you please paste the output of the following commands:
for env in $IBM_DB_HOME $CGO_CFLAGS $CGO_LDFLAGS $DYLD_LIBRARY_PATH; do echo $env; done
go env
ls $IBM_DB_HOME/include
ls $IBM_DB_HOME/lib
uname -a
Thanks

**Comment by dartagnanli** [comment]
> @dartagnanli, This error occurs when environment variables are not set properly or when some files are missing. Could you please paste the output of the following commands: for env in $IBM_DB_HOME $CGO_CFLAGS $CGO_LDFLAGS $DYLD_LIBRARY_PATH; do echo $env; done go env ls $IBM_DB_HOME/include ls $IBM_DB_HOME/lib uname -a Thanks

I got it ,thanks
