### ISSUE TITLE
After connecting to db2 successfully, Chinese character display exception in the query result

### ISSUE THREAD

**Issue by xSeaGull** [ibmdb/go_ibm_db#205]
- os Version: Win11 22H2 22621.1344 
- cli-driver Version: ntx64_odbc_cli.zip   28-Jan-2023 01:00 ; the latest
- go_ibm_db Version:0.4.2 ; the latest
- Db2 codepage:
```
$ db2 get db cfg |grep code

 Database code page                                      = 1208
 Database code set                                       = UTF-8
 Database country/region code                            = 1
```
- Db2 Server Version:
```
$ db2licm -l

Product name:                     "DB2 Express-C"
License type:                     "Unwarranted"
Expiry date:                      "Permanent"
Product identifier:               "db2expc"
Version information:              "11.1"
Max number of CPUs:               "2"
Max amount of memory (GB):        "16"
Max number of cores:              "2"
Enforcement policy:               "Soft Stop"
```
- go Version:  go1.19.7 windows/amd64
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
```
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\LDNSH\AppData\Local\go-build
set GOENV=C:\Users\LDNSH\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\awk\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\awk\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.7
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\LDNSH\AppData\Local\Temp\go-build56592434=/tmp/go-build -gno-record-gcc-switches
```
</pre></details>
Steps to Reproduce:

1. key code
```golang
import (
	"database/sql"
	_ "github.com/ibmdb/go_ibm_db"
	"fmt"
)
func main() {
con := "HOSTNAME=xx;DATABASE=SAMPLE;PORT=50000;UID=db2inst1;PWD=db2inst1;PROTOCOL=TCPIP;QueryTimeout=0"
db, err := sql.Open("go_ibm_db", con)

rows, err := db.Query("select * from gsb.qydcbg")
if err != nil {
		xxx
}
columns, _ := rows.Columns()
scanArgs := make([]any, len(columns))
values := make([]sql.RawBytes, len(columns))
for i := range values {
	scanArgs[i] = &values[i]
}
results := make(map[int]map[string]string)
i := 0
for rows.Next() {
	err = rows.Scan(scanArgs...)
	if err != nil {
		xxx
	}
	row := make(map[string]string)
	for k, v := range values {
		key := columns[k]
		row[key] = string(v)
	}
	results[i] = row
	i++
}

fmt.Println(results[0]["企业名称"])
}
```
2. print result
```
PS D:\awk\go\src\zsygj.ini\db2_connect> .\db2_connect.exe
map[0:map[ACG_DT:1899-12-31T00:00:00+08:00 企业名称:�������� 企业类型:�������� 企业规模:��������                                       次数:5]]
��������
string
��������
��������
```
3. result in DBeaver :

![dbshow](https://user-images.githubusercontent.com/43143262/225004040-023d5df3-2498-423d-95cc-0beb1f2165d9.png)

**Comment by f2xb** [comment]
@xSeaGull 解决了吗？都是同样的问题

**Comment by xSeaGull** [comment]
> @xSeaGull 解决了吗？都是同样的问题

没呢 你也碰到了吗

**Comment by f2xb** [comment]
是的，数据库中是utf8，但是这个库查询出来编码就变gbk了，只能再转成utf8

**Comment by xSeaGull** [comment]
> 是的，数据库中是utf8，但是这个库查询出来编码就变gbk了，只能再转成utf8

那转成utf8解决了吗？ 能否参考下你的代码

**Comment by f2xb** [comment]
@xSeaGull 骚等

**Comment by f2xb** [comment]
@xSeaGull 
```golang
row[key] = toUtf8(v)

func toUtf8(b []byte) string {
	if utf8.Valid(b) {
		return string(b)
	}
	reader := transform.NewReader(bytes.NewReader(b), simplifiedchinese.GB18030.NewDecoder())
	if bts, err := ioutil.ReadAll(reader); err == nil {
		return string(bts)
	}
	return string(b)
}
```

**Comment by xSeaGull** [comment]
> 

:), 感谢分享。 我这边害这个库跨平台编译貌似过不去，你

**Comment by f2xb** [comment]
编译之前配置好db2的环境变量
`CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build`

**Comment by f2xb** [comment]
```golang
if utf8.Valid(b) {
	return string(b)
}
```
这段代码可以不加，今天发现的问题，它如果验证通过但还是会出现乱码，索性都转一次

**Comment by xSeaGull** [comment]
编译时，我在linux上和macos上都碰到的gcc编译器 报错               
![5a47dce5be9ab7ed058ce9c4e5a5253](https://user-images.githubusercontent.com/43143262/230843099-82949c69-c283-464e-a9aa-5063790d4bc5.png)

**Comment by xSeaGull** [comment]
> ```go
> if utf8.Valid(b) {
> 	return string(b)
> }
> ```
> 
> 这段代码可以不加，今天发现的问题，它如果验证通过但还是会出现乱码，索性都转一次

好的

**Comment by f2xb** [comment]
db2环境变量怎么配置的？

**Comment by xSeaGull** [comment]
path添加 :  D:\awk\go\src\github.com\ibmdb\clidriver\bin

**Comment by f2xb** [comment]
```sh
export IBM_DB_HOME=/home/uname/clidriver
export CGO_CFLAGS=-I$IBM_DB_HOME/include
export CGO_LDFLAGS=-L$IBM_DB_HOME/lib 
export LD_LIBRARY_PATH=$IBM_DB_HOME/lib
export PATH=$PATH:$IBM_DB_HOME/bin
```
windows没搞过，这是Linux上的配置

**Comment by xSeaGull** [comment]
> ```sh
> 
> export IBM_DB_HOME=/home/uname/clidriver
> 
> export CGO_CFLAGS=-I$IBM_DB_HOME/include
> 
> export CGO_LDFLAGS=-L$IBM_DB_HOME/lib 
> 
> export LD_LIBRARY_PATH=$IBM_DB_HOME/lib
> 
> export PATH=$PATH:$IBM_DB_HOME/bin
> 
> ```
> 
> windows没搞过，这是Linux上的配置

好👌 感谢大佬热心解答

**Comment by ZhengweiHou** [comment]
db2 的odbc驱动会根据当前环境LANG等判断codepage，也许你的运行时编码为GBK，你的这个情况可以尝试指定环境变量DB2CODEPAGE=1208 ，之后odbc驱动就会使用utf8编码从库中取出字符
codepage和编码的映射关系可以参考 https://www.ibm.com/docs/en/db2/11.1?topic=support-supported-territory-codes-code-pages

**Comment by vmathur12** [comment]
@xSeaGull  Can we close this issue. Thanks

**Comment by bimalkjha** [comment]
@xSeaGull To fix this problem, set the system level environment variable DB2CODEPAGE=1208 in your Windows system and then run go program. Alternatively, on the windows command prompt, you can run `set DB2CODEPAGE=1208` and then run the go text program.
You can also set this environment variable in go programmatically using `os.Setenv("DB2CODEPAGE, 1208)` statement.
This issue is related to the codepage only and by setting correct codepage should fix the issue. 1208 is for unicode characters. For specific language, check code page value in the Db2 knowledgecenter link shared in previous post by ZhengweiHou and apply accordingly. Closing this issue now. If you need any more info, you can always post here. Thanks.
