### ISSUE TITLE
Stored procedures support array-based input parameters

### ISSUE THREAD

**Issue by danws2020** [ibmdb/go_ibm_db#206]
This issue was logged some time ago: https://github.com/ibmdb/go_ibm_db/issues/35 and was closed.

When will the Db2 GO driver support array-based input parameters for stored procedures. This is an often-requested feature from our customers.

**Comment by vmathur12** [comment]
@danws2020 Db2 Go driver supports array-based input parameters for stored procedures. Following in a sample program. 

sp1.go :

package main
import (
            "database/sql"
            "fmt"
          _ "github.com/ibmdb/go_ibm_db"
       )

func main() {
        con := "HOSTNAME=<hostname>;PORT=<port>;DATABASE=<database>;UID=<user>;PWD=<password>"
        db, err := sql.Open("go_ibm_db", con)
        if err != nil {
                fmt.Println("Error:  ", err)
                return
        }

        var arr1 = []int{10, 20, 30, 40, 50}
        var arr2 = []string{"Row 10", "Row 20", "Row 30", "Row 40", "Row 50"}

         _, err = db.Exec("Drop table TT")
        if err != nil {
                fmt.Println("Error: ", err)
        }

         _, err = db.Exec("create table TT(C1 INTEGER NOT NULL, C2 VARCHAR(10))");
        if err != nil {
                fmt.Println("Error: ", err)
                return
        }

        st, err := db.Prepare("create procedure sp1(in arr1 integer, in arr2 VARCHAR(10)) LANGUAGE SQL BEGIN  INSERT INTO TT VALUES(arr1, arr2); END")
        if err != nil {
                fmt.Println("Error: ", err)
                return
        }
        st.Query()

        _, err = db.Exec("CALL sp1(?,?)", arr1, arr2)
        if err != nil {
                fmt.Println("Error: ", err)
                return
        }

        queryTypes := "select * from TT;"

        rows, err := db.Query(queryTypes)
        if err != nil {
                fmt.Println("Error:", err)
                return
        }

       for rows.Next() {
                var c1 int
                var c2 string
                err = rows.Scan(&c1, &c2)
                if err != nil {
                        fmt.Println("Error:", err)
                }
                fmt.Printf("C1=: %v\t C2: %v\n", c1, c2)
        }
}

"go run sp1.go" Output: 
C1=: 10  C2: Row 10
C1=: 20  C2: Row 20
C1=: 30  C2: Row 30
C1=: 40  C2: Row 40
C1=: 50  C2: Row 50

Please check this and let me know if you face any problem.
Thanks

**Comment by vmathur12** [comment]
@danws2020 Closing the issue. Let me know if you face any problem. Thanks
