### ISSUE TITLE
[help]how to debug the cost breakdown

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#209]
Dear team,

Recently we are facing an issue which the same sql is running JDBC(Java code) and go_ibm_db(ODBC Go code),  but the go code run slower than Java code.   Is there any way to debug in go_ibm_db,  to measure the cost breakdown, for example, how long it takes in driver, how long in network, and how long in db2 specifically? Thanks.

**Comment by bimalkjha** [comment]
@maxatcn You can do it using `db2trc` command that comes with clidriver. I can share the steps that you need to run, but those steps are Operating System specific. So, please share the name of operating system on which you have installed go_ibm_db.
Also, share the full path of clidriver in your system which should be something like `go\src\github.com\ibmdb\clidriver`. The value of environment variable IBM_DB_HOME if you have set and value of PATH environment variable. Thanks.

**Comment by vmathur12** [comment]
@maxatcn 
Closing the issue as there is no reply. Once you share the requested info, we can reopen it. Thanks.
