### ISSUE TITLE
 fatal error: sqlcli1.h: No such file or directory

### ISSUE THREAD

**Issue by firewaternottogther** [ibmdb/go_ibm_db#21]
./pandabi/src/github.com/ibmdb/go_ibm_db/api/api_unix.go:12:22: fatal error: sqlcli1.h: No such file or directory
 // #include <sqlcli1.h>

**Comment by akhilravuri1** [comment]
Hi
Can you paste output of go version and go env ?

Have you followed the steps in the readme?

You have to download the driver using go -d github.com/ibmdb/go_ibm_db command in non-windows.

Thanks,
Akhil.

**Comment by firewaternottogther** [comment]
@akhilravuri1 
I followed the steps and download the driver using go -d github.com/ibmdb/go_ibm_db command in non-windows.
go version go1.10 linux/amd64
go env:
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mnt/hgfs/xu/pandabi/:/mnt/hgfs/xu/gopath:/mnt/hgfs/xu/gopath_ds:/mnt/hgfs/xu/danastudio/"
GORACE=""
GOROOT="/mnt/hgfs/xu/go"
GOTMPDIR=""
GOTOOLDIR="/mnt/hgfs/xu/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build282436901=/tmp/go-build -gno-record-gcc-switches"

**Comment by akhilravuri1** [comment]
I see that CFLAGS and LDFLAGS are not set. As our driver internally uses clidriver, please follow the steps below...

```
go to installer folder where go_ibm_db is downloaded in your system (Example: /home/uname/go/src/github.com/ibmdb/go_ibm_db/installer) and run setup.go file (go run setup.go)
where uname is the username

Above command will download clidriver.

Set the below envronment variables with the path of the clidriver downloaded

export DB2HOME=/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
Linux:
export LD_LIBRARY_PATH=/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
Mac:
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
```

Here the above command means go run setup.go

**Comment by firewaternottogther** [comment]
@akhilravuri1 
sorry！ I've done these steps, but they've been changed.I'll do it again later.But I think maybe that's the problem
If you do not have a clidriver available in your system
go to installer folder where go_ibm_db is downloaded in your system (Example: /home/uname/go/src/github.com/ibmdb/go_ibm_db/installer) and run setup.go file (go run setup.go)
where uname is the username
![image](https://user-images.githubusercontent.com/39817883/58973243-107d6700-87f2-11e9-957e-d8487a91f7cc.png)

**Comment by firewaternottogther** [comment]
@akhilravuri1  
I'll do it again，and still the result of the same mistake。
my steps:
[root@localhost cli]# export DB2HOME=/mnt/hgfs/xu/pandabi/src/github.com/ibmdb/go_ibm_db/installer/clidriver
[root@localhost cli]# export CGO_CFLAGS=-I$DB2HOME/include
[root@localhost cli]# export CGO_LDFLAGS=-L$DB2HOME/lib
[root@localhost cli]# export LD_LIBRARY_PATH=/mnt/hgfs/xu/pandabi/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

go env:
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mnt/hgfs/xu/pandabi/:/mnt/hgfs/xu/gopath:/mnt/hgfs/xu/gopath_ds:/mnt/hgfs/xu/danastudio/"
GORACE=""
GOROOT="/mnt/hgfs/xu/go"
GOTMPDIR=""
GOTOOLDIR="/mnt/hgfs/xu/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-I/mnt/hgfs/xu/pandabi/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/mnt/hgfs/xu/pandabi/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build962957051=/tmp/go-build -gno-record-gcc-switches"

**Comment by akhilravuri1** [comment]
so clidriver is download then the next step is to set the path of the clidriver.
Set this env variables it will work... (I have given the path by seeing the image if the path is different give that path)
export DB2HOME=mnt/hgfs/xu/pandabi/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
export LD_LIBRARY_PATH=mnt/hgfs/xu/pandabi/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

Thanks,
Akhil

**Comment by firewaternottogther** [comment]
@akhilravuri1 
I'm sorry to bother you again,I tried, but I still got the same error.I think it could be a clidrive problem, like the version.Can you give me the clidrive download site that you passed the test?
Thanks,
Xu

**Comment by akhilravuri1** [comment]
Hi @firewaternottogther 

It's not about clidriver.

can you please answer these questions:-

1)  Go to the installer folder and check whether clidriver is downloaded or not?

2)  If downloaded then go to the clidriver/include folder and check for sqlcli.h and sqlcli1.h files.

3) If these files are also present then check $PATH,$DB2HOME,$CGO_CFLAGS,$CGO_LDFLAGS,$LD_LIBRARY_PATH variableS and compare it with the above path.


Thanks,
Akhil.

**Comment by firewaternottogther** [comment]
@akhilravuri1 
so sorry for my fault.You are right.But a new problem has arisen.
 I got this error .
/vendor/github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: cannot find -ldb2
/usr/bin/ld: cannot find -ldb2
collect2: error: ld returned 1 exit status

Like Error /usr/bin/ld: cannot find -ldb2 #6.Although this task has been shut down, no solution has been given. i have gone to /go/src/github.com/ibmdb/go_ibm_db/installer directory and checked for clidriver folder.
Thanks,
Xu

**Comment by akhilravuri1** [comment]
Hi @firewaternottogther 

Are you using Mac OS or Linux?

All these issues are related to the environment variables.

In Linux:- 
export DB2HOME=mnt/hgfs/xu/pandabi/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
set LD_LIBRARY_PATH.

If Mac the steps are different You have set LD_LIBRARY_PATH.


Thanks,
Akhil

**Comment by firewaternottogther** [comment]
@akhilravuri1 
linux
I think it's probably not environmental variables
![image](https://user-images.githubusercontent.com/39817883/59184560-f56b7800-8ba0-11e9-80e0-26b785a123a3.png)

**Comment by akhilravuri1** [comment]
Ok..let me install the driver in Linux environment and test it.

Thanks,
Akhil.

**Comment by firewaternottogther** [comment]
@akhilravuri1 
My download address:
wget ftp://public.dhe.ibm.com/software/server/POWER/Linux/rte/xlcpp/le/ubuntu/dists/trusty/main/binary-ppc64el/*

The relevant address:
https://www.ibm.com/support/knowledgecenter/zh/SS6NHC/com.ibm.swg.im.dashdb.doc/connecting/connect_driver_package_install.html

**Comment by akhilravuri1** [comment]
> @akhilravuri1
> My download address:
> wget ftp://public.dhe.ibm.com/software/server/POWER/Linux/rte/xlcpp/le/ubuntu/dists/trusty/main/binary-ppc64el/*
> 
> The relevant address:
> https://www.ibm.com/support/knowledgecenter/zh/SS6NHC/com.ibm.swg.im.dashdb.doc/connecting/connect_driver_package_install.html

Sorry,  I don't get why you have sent this.

I asked you whether you are installing the driver(Go driver) in docker

**Comment by ZhengweiHou** [comment]
The driver I was using was `github.com/ibmdb/go_ibm_db`, and I ended up solving the problem as follows:

import _ github.com/ibmdb/go_ibm_db

- go mod tidy
- go mod download
- cd $GOPATH/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.2/installer
- sh setup.go
  This script will download db2cli to the `$GOPATH/pkg/mod/github.com/ibmdb` directory by default
- sh setenv.sh
  This script sets environment variables based on the current scenario

**Comment by gilsegment** [comment]
I am running this
```
installer go run setup.go

os = darwin , processor = arm64
Please set IBM_DB_HOME, CGO_CFLAGS, CGO_LDFLAGS and DYLD_LIBRARY_PATH environment variables after clidriver installation
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macarm64_odbc_cli.tar.gz
download successful
Extracting with tar -xzf macarm64_odbc_cli.tar.gz -C /Users/gomer/dev/pkg/mod/github.com/ibmdb

clidriver path = /Users/gomer/dev/pkg/mod/github.com/ibmdb/clidriver
Now run below commands:
export IBM_DB_HOME=/Users/gomer/dev/pkg/mod/github.com/ibmdb/clidriver
source /Users/gomer/dev/pkg/mod/github.com/ibmdb/go_ibm_db@v0.5.2/installer/setenv.sh
➜  installer sh setenv.sh
NOTE: Environment variable DB2HOME name is changed to IBM_DB_HOME.
```

But still getting that error:
```
../../dev/pkg/mod/github.com/ibmdb/go_ibm_db@v0.5.2/api/zapi_unix.go:22:11: fatal error: 'sqlcli1.h' file not found
 #include <sqlcli1.h>
          ^~~~~~~~~~~
1 error generated.
```
