### ISSUE TITLE
SQL_DECIMAL type uses comma as separator, not period, so it can't convert to float64

### ISSUE THREAD

**Issue by the-goodies** [ibmdb/go_ibm_db#217]
I get this error when trying to map DECIMAL(7,2) (or other DECIMAL) type to float64:
(sql: Scan error on column index 2, name "LALA": converting driver.Value type []uint8 ("0,0") to a float64: invalid syntax)

This commit introduced this problem: https://github.com/ibmdb/go_ibm_db/commit/bb056f95d5ed1167cb2dc661b73fd725ab7588be
On my end at least, for whatever reason, DECIMAL type uses a comma and not a period, so it can't be converted to a float64.

I have made a change to column.go BaseColumn.Value and it works correctly now, but I'm not sure if it's the right fix:

```go
func (c *BaseColumn) Value(buf []byte) (driver.Value, error) {
	var p unsafe.Pointer
	if len(buf) > 0 {
		p = unsafe.Pointer(&buf[0])
	}
	switch c.CType {
	case api.SQL_C_BIT:
		return buf[0] != 0, nil
	case api.SQL_C_LONG:
		return *((*int32)(p)), nil
	case api.SQL_C_SBIGINT:
		return *((*int64)(p)), nil
	case api.SQL_C_DOUBLE:
		return *((*float64)(p)), nil
	case api.SQL_C_CHAR:
               //  ------- CHANGE HERE ------
		if c.SType == api.SQL_DECIMAL {
			return bytes.Replace(buf, []byte(","), []byte("."), 1), nil
		}
             // ----------------------------------
		return buf, nil
	case api.SQL_C_WCHAR:
```

- os Version: Windows 10
- go Version: 1.20

**Comment by vmathur12** [comment]
@the-goodies  Please share the GoLang program. Thanks.

**Comment by the-goodies** [comment]
I installed IBM Db2 database locally and tested things – everything works well. However, on the real PROD database, this problem exists. Here is the query from real DB:
```
db2 => SELECT TOTAL FROM DBA.LALA WHERE RECNO_ = 34500

TOTAL
-----------------
        102898,84

  1 record(s) selected.
```

The culprit I think is here:
```
db2 => get db cfg for PROD

       Database Configuration for Database PROD

 Database configuration release level                    = 0x1000
 Database release level                                  = 0x1000

 Database territory                                      = LT
 Database code page                                      = 1257
 Database code set                                       = 1257
 ...
```

Database territory is LT and probably that's why it uses comma, because LT decimal separator is a comma and not a period. There is no way I can change PROD database territory, so the only thing I can do is transform the returned result, somehow changing comma to a period.

**Comment by vmathur12** [comment]
@the-goodies 
My Database territory is US and decimal separator is a period. 
Using the following sample program to test. Let me know if there are any discrepancies.

package main
import (
            "database/sql"
            "fmt"
          _ "github.com/ibmdb/go_ibm_db"
       )

func main() {
        con := "HOSTNAME=<hostname>;PORT=<port>;DATABASE=vmtest;UID=<user>;PWD=<password>"
        
        db, err1 := sql.Open("go_ibm_db", con)
        if err1 != nil {
                fmt.Println(err1)
        }

      _, err2 := db.Exec("create table TT(Total DECIMAL(10,2))");
        if err2 != nil {
                fmt.Println(err2)
                return
        }

        st1, err3 := db.Prepare("Insert into TT(Total) values (102898.84)")
        if err3  != nil {
                fmt.Printf(err3)
                return
        }
        st1.Query()

        queryTypes := "select * from TT;"
        rows, err4 := db.Query(queryTypes)
        if err != nil {
                fmt.Println(err4)
		return
        }
        for rows.Next() {
                var total  float64
                err = rows.Scan(&total)
                if err != nil {
                        fmt.Println("Error", err)
                }
                fmt.Printf("Total: %v\n", total)
        }
}

 
Also created a database with territory as lt and tested.  LT  decimal separator is a period not a comma.

Command to create DB and territory as lt:
> db2 "CREATE DB vmtest using codeset UTF-8 territory lt"


> db2 get db cfg for vmtest | grep Database
       Database Configuration for Database vmtest
 Database configuration release level                    = 0x1500
 Database release level                                  = 0x1500
 Database territory                                      = lt
 Database code page                                      = 1208
 Database code set                                       = UTF-8
 ...

> db2 "select * from TT"

TOTAL
------------
   102898.84

  1 record(s) selected.

$ go run test.go
Total: 102898.84

**Comment by the-goodies** [comment]
> Also created a database with territory as lt and tested. LT decimal separator is a period not a comma.

You are right, same here. Turns out territory setting has nothing to do with this, but the issue is still locale related.

When connecting to locally installed IBM2 DB, I'm using my own main PC, but when connecting to real PROD database (where the problem lies), I'm using work PC, which has **Lithuanian** region setting:
![image](https://github.com/ibmdb/go_ibm_db/assets/22452788/417b4705-b193-44dc-af33-df19912a451e)

My own PC has **English (United States)** region setting, but changing it to **Lithuanian**, I managed to reproduce this problem when querying from local DB. Try to change region to **Lithuanian** (requires PC restart) and you will see that comma is being used regardless of DB territory setting.

**Comment by vmathur12** [comment]
@the-goodies  
Able to reproduce the issue in my PC when I have change region to Lithuanian. Made the code changes to column.go and it works correctly. Merged the code changes(https://github.com/ibmdb/go_ibm_db/pull/219). Hence closing the issue. Thanks
