### ISSUE TITLE
[CRITICAL] - double byte characters are truncated for CHAR columns

### ISSUE THREAD

**Issue by tkolanko** [ibmdb/go_ibm_db#218]
This was fixed in this PR https://github.com/ibmdb/go_ibm_db/pull/213 and I manually made the fix and verified it solved our testcase. Is it possible to get a new release of the driver? Is there anything holding back the driver release?

**Comment by vmathur12** [comment]
@tkolanko 
New release v0.4.4 is available now.
Thanks
