### ISSUE TITLE
fatal error: 'sqlcli1.h' file not found

### ISSUE THREAD

**Issue by rohithravin** [ibmdb/go_ibm_db#22]
Hi, 

I seem to be having this issue. I noticed that someone else also had this issue and I tried to do what you guys suggested in the comments but that did not help. I followed the steps in the readme as well.

Any help is greatly appreciated! 

<img width="1214" alt="Screen Shot 2019-06-10 at 4 28 25 PM" src="https://user-images.githubusercontent.com/26936421/59233316-c81ccb00-8b9c-11e9-8a2c-9c8f0823011a.png">

**Comment by akhilravuri1** [comment]
Hi @rohithravin 

Have you installed the using go get -d github.com/ibmdb/go_ibm_db? 
In Non-Windows -d is important. If clidriver is already in your path then -d can be left but If clidriver is not in your path you have to use -d or else it produces error sqlcli1.h file is not found.
 
Thanks,
Akhil

**Comment by rohithravin** [comment]
Yes, I used the -d 

<img width="1116" alt="Screen Shot 2019-06-11 at 9 51 41 AM" src="https://user-images.githubusercontent.com/26936421/59290919-8dfc0980-8c2e-11e9-9444-d6df1bb9069e.png">
