### ISSUE TITLE
Adding Dynamic Cursor Functionalities

### ISSUE THREAD

**Issue by Karancse** [ibmdb/go_ibm_db#227]
I want to make a pull request to this repo by adding dynamic scrollable cursor functionalities. This is part of an internal IBM project.

I have forked this repository to [https://github.com/Karancse/go_ibm_db_fork](https://github.com/Karancse/go_ibm_db_fork).
I updated the code and added SQLSetStmtAttr(), SQLGetStmtAttr(), and SQLSetPos(). They are all working fine except for the below mentioned step.

I used SQLSetStmtAttr() to set the SQL_ATTR_CURSOR_TYPE to SQL_CURSOR_DYNAMIC. It returns 0 ( SQL_SUCCESS ). 

But, when I use SQLGetStmtAttr() to get the value of SQL_ATTR_CURSOR_TYPE, it still returns 0 ( SQL_CURSOR_FORWARD_ONLY ).

Similarly, when I use SQLSetPos() with Operation as SQL_UPDATE, it returns the following error:
[IBM][CLI Driver] SQL0510N   UPDATE or DELETE is not allowed against the specified cursor.   SQLSTATE=42828

I added detailed steps with comments inside the function definition "func (c *Conn) Query"  inside the conn.go file in the forked repo [https://github.com/Karancse/go_ibm_db_fork](https://github.com/Karancse/go_ibm_db_fork).

If you can help me fix the step setting the cursor type to dynamic, I will add test cases and push to this repo.

**Comment by bimalkjha** [comment]
@Karancse Please check doc about SQL_ATTR_CURSOR_TYPE here: https://www.ibm.com/docs/en/db2/11.5?topic=attributes-statement-list
It seems, SQL_ATTR_CURSOR_TYPE get affected by the value of SQL_ATTR_CONCURRENCY and cursor should not be in open state.
> If the specified cursor type is not supported by the data source, CLI substitutes a different cursor type and returns SQLSTATE 01S02 (Option value changed). For a mixed or dynamic cursor, CLI substitutes, in order, a keyset-driven or static cursor. 
> If the SQL_ATTR_CURSOR_TYPE Attribute is changed to a type that does not support the current value of SQL_ATTR_CONCURRENCY, the value of SQL_ATTR_CONCURRENCY is changed at execution time, and a warning issued when SQLExecDirect() or SQLPrepare() is called.

Also, share your go test program that you run to verify value of attribute.
Thanks.
