### ISSUE TITLE
SQLDriverConnect: {HY000} [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3".

### ISSUE THREAD

**Issue by firewaternottogther** [ibmdb/go_ibm_db#23]
Run successfully in a normal directory such as home.But run the successful binaries in a Shared folder and report an error.
SQLDriverConnect: {HY000} [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3".
SQLDriverConnect: {HY000} [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3".

SQLDriverConnect: {HY000} [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3".

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a6a30]

**Comment by akhilravuri1** [comment]
Can you paste the sample program which produced you this error?

Give me some information about the error like:
What were you trying to do?
was the connection successful?

Thanks,
Akhil.

**Comment by firewaternottogther** [comment]
@akhilravuri1 
Error recurrence step:
1、Download go_ibm_db and configure the environment variable in the home path. Run the demo successfully and go build.I will get binary file.
2、Linux creates Shared folders with Windows
3、Put the binaries in a Shared folder and execute.You will get this error.
Thanks.

**Comment by akhilravuri1** [comment]
Hi @firewaternottogther 

Are you executing the binary file in windows?

Thanks,
Akhil

**Comment by firewaternottogther** [comment]
@akhilravuri1 
No. I  execute the binary file in linux.
Thanks

**Comment by akhilravuri1** [comment]
@firewaternottogther In step 1, you are configuring the environment variables in the home path. I assume you have updated PATH, INCLUDE, and LD_LIBRARY_PATH env vars. Now, in step 3, you are moving the binary to a different folder. Have you updated the environment variables as per this new folder? 

To make it working, please add the `.../clidriver/bin:.../clidriver/lib` in your PATH and LD_LIBRARY_PATH system environment variable. Then it should work. Thanks.

**Comment by firewaternottogther** [comment]
@akhilravuri1 
sorry,I disagree.I only change the binary file location, the program reads the location is still the same.Where is the location of the clidriver read in your code and I want to see its logic.
 Thanks.

**Comment by akhilravuri1** [comment]
@firewaternottogther I have created a shared folder using samba and copied the binary to the shared folder and executed it. It was working fine. 

Try to add the clidriver/lib in the $PATH variable and execute the file once again.

Under github.com/ibmdb/go_ibm_db/api folder in each Unix file, we use LDFLAGS linking based on the environment variables. These env vars(CGO_CFLAGS, CGO_LDFLAGS) will have the path to the clidriver.

Thanks,
Akhil

**Comment by firewaternottogther** [comment]
@akhilravuri1 
I'm so sorry. I tried  to add the clidriver/lib in the $PATH variable and execute the file once again.Error is still.
Since this scenario cannot be reproduced, we can change the scenario and put this binary on another host without go environment to run.How do we set the environment variables
Thanks

**Comment by akhilravuri1** [comment]
@firewaternottogther 

you can put the binary in any system with same os and architecture ( go lang is platform dependent in case of binaries) but clidriver should be present in that system.
Env's to be set:-
export DB2HOME=/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
export LD_LIBRARY_PATH=/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

Thanks,
Akhil.

**Comment by firewaternottogther** [comment]
@akhilravuri1 
This is the location of the clidrive.
![image](https://user-images.githubusercontent.com/39817883/59408557-df4ef900-8de6-11e9-8e54-908f04f809fa.png)
Env's to be set:
![image](https://user-images.githubusercontent.com/39817883/59408393-897a5100-8de6-11e9-98e7-693143f657e2.png)
but error are still there.I'm sorry, I really hope you can answer.
![image](https://user-images.githubusercontent.com/39817883/59408776-58e6e700-8de7-11e9-932d-1d742f344ab1.png)
Thanks.

**Comment by akhilravuri1** [comment]
@firewaternottogther 

The driver is under root if you don't have the permissions you can't read the data. Try to place the driver in another folder or change the permission by 
sudo chmod -R 777 foldername

Thanks,
AKhil

**Comment by firewaternottogther** [comment]
@akhilravuri1
After adding permissions, error is still reported.Can we contact each other by email? 
![image](https://user-images.githubusercontent.com/39817883/59410050-694c9100-8dea-11e9-837c-c0f3b292cd7e.png)
Thanks

**Comment by akhilravuri1** [comment]
@firewaternottogther 
can you collect db2 and cli traces

db2trc on -f trc.dmp
run your application
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files with us to assist you further.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
@firewaternottogther 
Have you collected the traces?

Thanks,
Akhil

**Comment by firewaternottogther** [comment]
@akhilravuri1 
Sorry for the late reply!
![image](https://user-images.githubusercontent.com/39817883/60427975-72cb5b00-9c2a-11e9-8939-4fab7a6d6b0b.png)
Thanks,
Xu

**Comment by akhilravuri1** [comment]
@firewaternottogther 
share the files, not the Image.
Thanks,
Akhil

**Comment by firewaternottogther** [comment]
@akhilravuri1 
[info.zip](https://github.com/ibmdb/go_ibm_db/files/3345781/info.zip)
Thanks,
Xu

**Comment by akhilravuri1** [comment]
Hi @firewaternottogther 
There is no data in the file. Can you run the application again when the trace is on and share the files.

Thanks,
Akhil

**Comment by firewaternottogther** [comment]
@akhilravuri1 
Probably because of my Linux environment.Every time I report this error,even if there is a configuration in the configuration file, I will source /etc/profile and it's ok.I'll look around.
thanks a lot,
xu

**Comment by Prathyusha6** [comment]
Hi, 

I'm facing the same issue, is this problem resolved ?

**Comment by akhilravuri1** [comment]
The problem is because of the user environment issues.

Thanks,
Akhil

**Comment by Prathyusha6** [comment]
Thanks for the quick response @akhilravuri1. 
Sorry for the late reply. 
Here are the environment variables i have set in my LINUX environment.:
export DB2HOME=/home/db2inst2/db2_cli_odbc_driver/odbc_cli/clidriver (PATH TO CLIDRIVER)
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
export LD_LIBRARY_PATH=/home/db2inst2/db2_cli_odbc_driver/odbc_cli/clidriver/lib

but still am facing this error in the GUI of hammerdb
![image](https://user-images.githubusercontent.com/12022780/95346333-5ca25500-08d9-11eb-963f-b3f09ad2e4ff.png)

What am I doing wrong here? Please guide me, I'm really stuck with this for so long.

**Comment by akhilravuri1** [comment]
Hi @Prathyusha6 

Can you please set the env variables to the clidriver downloaded by the go_ibm_db driver?

Just wanted to check later we will replace it with the values you are using.
If you haven't download the clidriver using go_ibm_db please follow the below steps.

```
go to the installer folder where go_ibm_db is downloaded in your system (Example: /home/uname/go/src/github.com/ibmdb/go_ibm_db/installer) and run setup.go file (go run setup.go)
where uname is the username

The above command will download the clidriver.

Set the below environment variables with the path of the clidriver downloaded

export DB2HOME=/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
export LD_LIBRARY_PATH=/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
```

**Comment by Prathyusha6** [comment]
Thanks @akhilravuri1 .
Have downloaded go_ibm_driver and set the environments as:
export DB2HOME=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
export LD_LIBRARY_PATH=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

but still the error remained same

![image](https://user-images.githubusercontent.com/12022780/95355376-1d790180-08e3-11eb-9a6c-db47fbf85259.png)

**Comment by Prathyusha6** [comment]
I logged in as root. Still i changed my directory to home/user :
change env vars to :
```
export DB2HOME=/home/user/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
export LD_LIBRARY_PATH=/home/user/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
```
db2level output

![image](https://user-images.githubusercontent.com/12022780/95359712-143e6380-08e8-11eb-8e98-8a6e0f803445.png)

same result:

![image](https://user-images.githubusercontent.com/12022780/95360992-c62a5f80-08e9-11eb-9e4c-1f90776cbfe2.png)

**Comment by akhilravuri1** [comment]
Hi @Prathyusha6 

Does your PATH contain multiple dsdriver?

Please paste the output of PATH and LD_LIBRARY_PATH.

Thanks,
Akhil

**Comment by Prathyusha6** [comment]
I think no, can you plz guide me where to get it ?
Here are the env vars:

![image](https://user-images.githubusercontent.com/12022780/95425887-a1be9980-0962-11eb-8982-3dc1bb1ac429.png)

**Comment by akhilravuri1** [comment]
Hi @Prathyusha6 

Are you running go application?

Can you please run this sample go application and paste the output?
```
package main

import (
    _ "github.com/ibmdb/go_ibm_db"
    "database/sql"
    "fmt"
)

func main(){
    con:="HOSTNAME=host;DATABASE=name;PORT=number;UID=username;PWD=password"
    db, err:=sql.Open("go_ibm_db", con)
    if err != nil{
		fmt.Println(err)
    }
    err = db.Ping()
    if err != nil {
	fmt.Println(err)
    } else {
	 fmt.Println("CONNECTION SUCCESS")
    }
    db.Close()
}
```

Thanks,
Akhil

**Comment by Prathyusha6** [comment]
Hi @akhilravuri1 
![image](https://user-images.githubusercontent.com/12022780/95434026-60cc8200-096e-11eb-8506-4ba05d68d23c.png)


i have set 

```
GOROOT=/usr/local/go/
GOPATH=/home/user/go/src
PATH = $PATH:/usr/local/go/bin
```

GOROOT and GOPATH are set wrong here ?

Thanks,
Prathyusha

**Comment by akhilravuri1** [comment]
Go PATH has to home/user/go please src.

If you see the image...it checks in /home/user/go/src/src/github.com/ibmdb/go_ibm_db path.

Thanks,
Akhil

**Comment by Prathyusha6** [comment]
Oh sry. Thanks

Got the success result and tried running hammerdb again but still popping up the same error.. 
![image](https://user-images.githubusercontent.com/12022780/95437644-db979c00-0972-11eb-85e0-bd5b38de44d8.png)

**Comment by Prathyusha6** [comment]
Hi Akhil Ravuri,

Can we please take forward the conversation through email?


Thanks and Best Regards,
Prathyusha.

**Comment by akhilravuri1** [comment]
Hi @Prathyusha6 

Sorry for the late reply...I was trying to install HammerDb

yes..we can talk about this in email.

But just for conformation...Does this do anything with go driver?

Because the Go application runs fine in this your previous comment.

Thanks,
Akhil

**Comment by DaisyYangl** [comment]
The same issue here, how to solve this please
