### ISSUE TITLE
fatal error: 'sqlcli1.h' file not found on macOS

### ISSUE THREAD

**Issue by wkpui14** [ibmdb/go_ibm_db#232]
- os Version: macOS Monterey version 12.2
- cli-driver Version: go_ibm_db@v0.4.5
- Db2 Server Version: 
![messageImage_1704876347025](https://github.com/ibmdb/go_ibm_db/assets/156276598/ebd22422-020d-4c60-b8da-e3a6ae9c84dc)

- go Version: go1.19.1 darwin/amd64
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mtb730773/Library/Caches/go-build"
GOENV="/Users/mtb730773/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mtb730773/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mtb730773/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.19.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19.1/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-I/Users/mtb730773/go/pkg/mod/github.com/ibmdb/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/Users/mtb730773/go/pkg/mod/github.com/ibmdb/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w5/7wv92n5s13j7k08y5jv7k9sshmzld4/T/go-build2554364588=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

Steps to Reproduce:

1. go test code involving the DB2 call.
`show error
github.com/ibmdb/go_ibm_db/api ../../../go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.5/api/api_unix.go:13:11: fatal error: 'sqlcli1.h' file not found  #include <sqlcli1.h> ^~~~~~~~~~~ 1 error generated.`

**Comment by bimalkjha** [comment]
@wkpuy Please share output of below commands from terminal:
```
ls /Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/
ls /Users/uname/go/pkg/mod/github.com/ibmdb/clidriver/include
echo $IBM_DB_HOME
echo $PATH
echo $GOHOME
db2level
```
Thanks.

**Comment by bimalkjha** [comment]
Closing due to lack of response. Thanks.
