### ISSUE TITLE
Golang DB2 driver issue

### ISSUE THREAD

**Issue by jacoville** [ibmdb/go_ibm_db#234]
Hi team, please your help:

We use the golang DB2 driver https://github.com/ibmdb/go_ibm_db.  We don't have control of the exact version of the CLI driver it picks up during install time.  The driver installation code picks up the driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/.  There is only one copy and it is not versioned so the application will pick up the latest driver at the installation time.  There is no mechanism to match the server and the driver version.
Here are the behavior of different builds of the drivers on the golang driver page:

DB21085I This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11058" with level identifier "0609010F".
Informational tokens are "DB2 v11.5.8.0", "special_26260",
"DYN2301190517AMD64_26260", and Fix Pack "0".
No GSKit error

DB21085I This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11058" with level identifier "0609010F".
Informational tokens are "DB2 v11.5.8.0", "special_36444",
"DYN2310200440AMD64_36444", and Fix Pack "0".
Intermittent GSKit error SQLDriverConnect: {42724} [IBM][CLI Driver] SQL10013N  The specified library \"GSKit Error: 106\" could not be loaded.  SQLSTATE=42724
DB21085I  This instance or install (instance name, where applicable: "*") uses 
"64" bits and DB2 code release "SQL11059" with level identifier "060A010F".
Informational tokens are "DB2 v11.5.9.0", "special_36648", 
"DYN2311160803AMD64_36648", and Fix Pack "0".

Very frequent GSKit error SQLDriverConnect: {42724} [IBM][CLI Driver] SQL10013N  The specified library \"GSKit Error: 106\" could not be loaded.  SQLSTATE=42724
If I manually download the driver from Fix Central like [https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~Information%2BMa[…]dbc_cli-11.5.9.0-FP000%3A559528138754597504&includeSupersedes=0](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=All&platform=All&function=fixId&fixids=special_37108_398223_DSClients-linuxx64-odbc_cli-11.5.9.0-FP000%3A559528138754597504&includeSupersedes=0) and replace the clidriver I get errors like "Could not connect to Db2.  Exiting.  Error: SQLDriverConnect: {HY000} [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004".  It seems like there is something special about the drivers on the golang download page

**Comment by bimalkjha** [comment]
@jacoville The clidrivers available at `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/` is the minimized version of dsdriver from Fix Central or some special build. We always keeps latest tested version of clidriver for open source drivers.
If you want older clidriver, then you can see old project directories under https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ that contains older clidriver.
If you have need of some specific version of driver and not the one available at https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/, then you should download `IBM Data Server Driver Package` of that version & level from fix central and install it. Post install, set a system level environment variable `IBM_DB_HOME=<install dir of dsdriver>` and then install go driver.
The link from fix central that you shared is of odbc_cli driver. Please download dsdriver and use it.

We have updated the default clidriver at https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ to special build of v11.5.9 now. So, if you go for fresh installation or download and replace your existing clidriver of v1158, it should work fine.
Let us know if you face any issue by using v1159 clidriver from https://public.dhe.ibm.com/ site too. Thanks.
