### ISSUE TITLE
Column type VARBINAR with invalid utf-8 characters

### ISSUE THREAD

**Issue by NateMoeller** [ibmdb/go_ibm_db#25]
Hi,

I am trying to run a query which is selecting a uuid from a VARBINAR type column. I am reading the data into a byte slice and then converting it to a string. The issue is that some of the rows contain invalid utf-8 characters, so converting to a string returns a garbage result. See below: 

![Screen Shot 2019-07-01 at 10 51 38 AM](https://user-images.githubusercontent.com/4491271/60456503-45f95280-9bee-11e9-9078-4d7082123d50.png)

Converting the byte slice to a uuid looks like it returns a correct result: 
![Screen Shot 2019-07-01 at 11 02 54 AM](https://user-images.githubusercontent.com/4491271/60457025-d1271800-9bef-11e9-81f2-99eac4b7bc37.png)

So my application needs to know the type of the column so it can convert it to a uuid. I am calling the [ScanType()](https://golang.org/pkg/database/sql/#ColumnType.ScanType) function, but it is always returning an empty interface. 

Is this something that can be fixed at the driver level or is there a workaround for reading a uuid?

Thank you

**Comment by akhilravuri1** [comment]
Hi @NateMoeller 

So, you are getting the data from database and calling a ScanType() function on that data to know the datatype to convert it.
To store the data in a variable you have to declare a variable with the datatype. So ScanType() should work and give the type.
Can you create a sample program on how you are reading the data from the database and paste it?

Thanks,
Akhil.

**Comment by NateMoeller** [comment]
The problem is that my application allows the user to select the table they are selecting from and the columns that they are selecting. Since I do not know the columns they may select, I have to initialize the variables as an empty interface. Here is some code:

```
joinQuery := <User generated query>
objects := make([]map[string]interface{}, 0)
rows, err := db.Query(joinQuery)
defer rows.Close()
columns, err := rows.ColumnTypes()
values := make([]interface{}, len(columns))
valuePtrs := make([]interface{}, len(columns))
for rows.Next() {
		object := make(map[string]interface{}, len(columns))

		for i := 0; i < len(columns); i++ {
			valuePtrs[i] = &values[i]
		}
		rows.Scan(valuePtrs...)

		for i, col := range columns {
			fmt.Println(col.ScanType())
			var v interface{}
			val := values[i]
			b, hasBytes := val.([]byte)

			if hasBytes {
				v = string(b)
			} else {
				v = val
			}
			object[col.Name()] = v
		}
		objects = append(objects, object)
	}
```

**Comment by NateMoeller** [comment]
@akhilravuri1 Let me know if anything is confusing and I can try and explain further.

**Comment by akhilravuri1** [comment]
Hi @NateMoeller 

I have created a table with column type varbinary.
```
        st,err:=db.Prepare("Insert into VARBIR values(?)")
	aa:=[]byte("akhil123")
	st.Query(aa)

	var a []byte
	err = db.QueryRow("select * from varbir").Scan(&a)
	fmt.Println(string(a)) 
```
It's working fine.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
closing the issue has user did not respond.
