### ISSUE TITLE
Is there Datalake table support?

### ISSUE THREAD

**Issue by josephhlwang** [ibmdb/go_ibm_db#255]
- os Version: MacOS 15.0(M1) and RedHat 9.4
- cli-driver Version: 0.5.0
- Db2 Server Version: 11.9.0
- go Version: go version go1.22.7 darwin/amd64
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/joseph/Library/Caches/go-build'
GOENV='/Users/joseph/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/joseph/go/pkg/mod'
GONOPROXY='github.ibm.com'
GONOSUMDB='github.ibm.com'
GOOS='darwin'
GOPATH='/Users/joseph/go'
GOPRIVATE='github.ibm.com'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/joseph/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.7.darwin-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/joseph/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.7.darwin-amd64/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.22.7'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/joseph/work/pipeline-config1/pipeline-config/go.mod'
GOWORK=''
CGO_CFLAGS='-I/Users/joseph/go/pkg/mod/github.com/ibmdb/clidriver/include'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-L/Users/joseph/go/pkg/mod/github.com/ibmdb/clidriver/lib'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/s1/ltdpw08x473d93tx067xg7b80000gn/T/go-build3713260971=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre></details>

Steps to Reproduce:

1. Run create Datalake table query using db.Exec()
2. Get `SQLExecute: {55023} [IBM][CLI Driver][DB2/LINUXX8664] SQL0471N  Invocation of routine "BigSQL DDL Processor" failed due to reason "".  SQLSTATE=55023`

Comment:

1. Running the same query works on DBeaver and also with db.Query()
2. DBeaver returns no error, query returns successful but with no row results error

<details><summary><code>example query</code> query:</summary><br><pre>
CREATE DATALAKE TABLE "TESTSCHEMA1"."TABLE_COLD" ("sss" DECIMAL(20) NOT NULL,
"aaaa" TIMESTAMP(6),
"sss" TIMESTAMP(6),
"dddd" FLOAT,
"ffff" VARCHAR(50) NOT NULL,
"ggggg" SMALLINT,
"hhhh" TIMESTAMP(0),
"jjjj" VARCHAR(40),
"kkk" VARCHAR(255),
"llll" VARCHAR(50),
"zzz" VARCHAR(100),
"xxx" VARCHAR(30),
"cccc" VARCHAR(20),
"vvvvv" VARCHAR(30),
PRIMARY KEY ("sss",
"ffff") NOT ENFORCED)
LOCATION 'DB2REMOTE://TESTSCHEMA1/TABLE_COLD'
STORED BY ICEBERG TBLPROPERTIES ('external.table.purge' = 'true');
</pre></details>

**Comment by bimalkjha** [comment]
@josephhlwang BigSQL do not support Prepare + Execute kind of statement but direct execution. It is limitation with BigSQL server and not with go_ibm_db client.
Try using Query API as shown here: https://github.com/ibmdb/go_ibm_db/blob/master/testdata/queryinsertselect_test.go
It should work, otherwise share your test program. Thanks.
