### ISSUE TITLE
How to set library list and use UTF8 encoding

### ISSUE THREAD

**Issue by sbildl** [ibmdb/go_ibm_db#256]
I have a list of different libraries that i want to go through when not qualifying schema in a select statement.

in JDBC you can specify the system i librarylist (editlibl) directly in the connection string.

How to specify the Library-List here?

Also I want to be able to read columns with ccsid 1208.
It works when I use the DB2CODEPAGE environment variable. But is there a better way so I don't need to set a environment variable?

Thank you.

**Comment by bimalkjha** [comment]
@sbildl you can use the SchemaList keyword in connection string as documented here: https://www.ibm.com/support/knowledgecenter/SSEPGG_12.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008810.html
For Db2 for IBM® i servers, if you specify the *USRLIBL value, the ibm_db driver searches the current libraries of the server job. The *USRLIBL value that is retrieved from the server, on the first catalog function call, is cached by default. The same *USRLIBL value is used for all subsequent catalog function calls in the same connection handle. You can change the caching behavior of the user library list by using CacheUsrLibL keyword in connection string. Please read knowledgecenter link for more details.

DB2CODEPAGE should be an enviornment variable only. There are different ways to set it. You can set it in your .profile file, or .bashrc/.kshrc or in your Go application using `os.Setenv("DB2CODEPAGE", "1208")`. Thanks.

**Comment by bimalkjha** [comment]
@sbildl Hope above update has addressed your issues. Can we close this issue now? Thanks.
