### ISSUE TITLE
Requiring the newest go compiler causes problems for products that need to be FIPS compliant

### ISSUE THREAD

**Issue by abecher22** [ibmdb/go_ibm_db#257]
I use this driver in a product that must meet FIPS requirements.  In order to be FIPS-compliant, only certain encryption libraries are allowed and the default encryption library in the standard go compiler is not among them.  So, our OS vendor builds a version of the go compiler that is FIPS compliant.  However, that compiler is always a minor version behind.  That means that I cannot use go v1.23.1 but I can use v1.22.  When the go.mod contains "go 1.23.1", I am unable to use that version of the driver.  My question is: does the go version actually require 1.23.1?

**Comment by vmathur12** [comment]
@abecher22 
Please set the environment variables <$PATH> to Go v1.22 . Go can be any directory on the system. Add the path to environment variable to <$PATH>.
Create a <test> directory for your Go module source code
Run the "go mod init <directory name>" command . The go mod init command creates a go.mod files to track your codes supports. This will also set to the Go lang version present in the system.
Run the "go mod tidy" command. This command creates go.sum file ensures that the go.mod file matches the source code in the directory.
Thanks

**Comment by bimalkjha** [comment]
>> My question is: does the go version actually require 1.23.1?

@abecher22 No, it can be any version as per your convenience. thanks.

**Comment by bimalkjha** [comment]
@abecher22 go_ibm_db@0.5.2 has restored the go version to 1.22.1 in go.mod file. Please install latest version and check. Closing the issue now. Thanks.
