### ISSUE TITLE
Error querying DB2 11.01.5 for z/OS

### ISSUE THREAD

**Issue by thigaz** [ibmdb/go_ibm_db#26]
I can't execute any query and receive the following error:

> SQLExecute: {42601} [IBM][CLI Driver][DB2] SQL0104N  An unexpected token " " was found following "".  Expected tokens may include:  ". <IDENTIFIER> JOIN INNER LEFT RIGHT FULL CROSS , HAVING GROUP".  SQLSTATE=42601

When using direct ODBC (github.com/alexbrainman/odbc), the query is executed as expected.

The sample program I'm trying to execute is this:
`package main

import (
	"database/sql"
	"fmt"

	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	var text string
	db, err := connectDB()
	if err != nil {
		println("Connect Error:\n" + err.Error())
		return
	}
	if err = db.Ping(); err != nil {
		println("Ping Error:\n" + err.Error())
		return
	}
	err = db.QueryRow("SELECT GETVARIABLE('SYSIBM.VERSION') FROM SYSIBM.SYSDUMMY1").Scan(&text)
	if err != nil {
		println("Query Error:\n" + err.Error())
		return
	}
	println(text)
	db.Close()
}

func connectDB() (banco *sql.DB, err error) {
	var driver, connection string
	driver = "go_ibm_db"
	connection = fmt.Sprintf("DATABASE=%s;HOSTNAME=%s;PORT=%d;PROTOCOL=TCPIP;UID=%s;PWD=%s", "host", "ip", port, "user", "password")
	return sql.Open(driver, connection)
}`

**Comment by akhilravuri1** [comment]
Hi @thigaz 

please add ";" at the end of the query. It will work.
query:-"SELECT GETVARIABLE('SYSIBM.VERSION') FROM SYSIBM.SYSDUMMY1;"

Meanwhile, we will investigate why it is not working without ";"

Thanks,
Akhil

**Comment by thigaz** [comment]
Thank you, it worked!

**Comment by dlopes7** [comment]
@akhilravuri1 were you able to investigate this? Faced the same issue.

**Comment by akhilravuri1** [comment]
@dlopes7 I have fixed this issue and I have checked it now. The driver works fine with or without ";".
Please download the latest driver and give a try.

Thanks,
Akhil

**Comment by cvigo** [comment]
Same issue here... but latest tagged version is previous to this fix, right?

**Comment by akhilravuri1** [comment]
Hi @cvigo 

Are you facing this issue with the latest version?

Thanks,
Akhil

**Comment by cvigo** [comment]
Hi @akhilravuri1 

The latest version solves the issue. I messed up with the dates as your lastest comment here was after the release of v0.2.0

Thanks

**Comment by akhilravuri1** [comment]
Thanks @cvigo
