### ISSUE TITLE
Supporting different connection security mechanism

### ISSUE THREAD

**Issue by annfengcn** [ibmdb/go_ibm_db#27]
1. SSL 
2.API Key 
3. Kerbos

**Comment by akhilravuri1** [comment]
can you give us more information about the issue?

Thanks,
Akhil

**Comment by litaocdl** [comment]
@akhilravuri1 
More description for connection support.
1. SSL support.   go client going to talk with the db2 ssl port by adding a new flag like sslConnection=true, by enable this flag, the communication between go client and db2 server a secure connections which is encrypted. if the db2 server is configured with CA signed certification, there is no extra need for go client configuration. if db2 server side is configured with self-signed certification, the go client side need to configure the truststore. 

2. APIKey support. besides the username and password as credentials. API Key support means the go client can configure to use public cloud APIKey to communicate with DB2, while this DB2 is configured to authenticated with IAM server GSS Plugin. the securityMechanism for this APIKey support is 15. 

3. Kerbos support means go client configure to use securityMechanism 11 to talk with DB2 which is using kerberos authentication. the username and password send to db2 will first send to kerbos server to generate the kerberos ticket and then using this ticket to send to db2 server for authentication .

let me know if we need more information.

**Comment by akhilravuri1** [comment]
Hi @annfengcn 
Have you tried to make a connection using Kerberos?
If yes in which platform.

**Comment by annfengcn** [comment]
We have connection to Linux kerberos with jdbc, but there's no example in the go driver how to connect to kerbos. so we are looking for go example.
@litaocdl we can share jdbc example

**Comment by akhilravuri1** [comment]
Hi @annfengcn 
our clidriver(downloaded by go) on Linux does not support Kerberos. Do you have a special build of clidriver for Linux which supports Kerberos?

Thanks,
Akhil

**Comment by qi-min** [comment]
@akhilravuri1 Current we only use JDBC for Kerberos. But from this doc, cli driver should also support kerberos.

**Comment by akhilravuri1** [comment]
Hi @qi-min 
Yes, cli driver supports Kerberos. But there is a small defect in that and we have delivered the fix through this APR-IT28444(we delivered it to v11.1.4.5) but it is not released. So If you give us the information like on which platform and what version of odbc-cli you are using we will give you the special build.
Thanks,
Akhil

**Comment by qi-min** [comment]
@akhilravuri1 Do you mean you can help to provide a special cli driver build if we can provide the version and platform of cli driver?

**Comment by akhilravuri1** [comment]
Yes.

**Comment by maxatcn** [comment]
> Hi @qi-min
> Yes, cli driver supports Kerberos. But there is a small defect in that and we have delivered the fix through this APR-IT28444(we delivered it to v11.1.4.5) but it is not released. So If you give us the information like on which platform and what version of odbc-cli you are using we will give you the special build.
> Thanks,
> Akhil

Hi Akhil,

The cli driver download link:  https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
As I checked, 
IBM Data Server Driver for ODBC and CLI v11.1.4.4

I am not sure how often the driver updated in the link above.
If there is the link to download the latest one, please let us know. 

Thanks.

**Comment by akhilravuri1** [comment]
Hi @maxatcn

Since the new version is not released. I think it will not be available to the public links. If you give us the platform and odbc-cli which you are using we will give you the special build.

Thanks,
Akhil

**Comment by maxatcn** [comment]
@akhilravuri1 ,  https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz   this is what we are using in formal build.  This is included in the deployment script,  download->unzip->install,  Linux, x86_64.

Thanks,
Max

**Comment by akhilravuri1** [comment]
@maxatcn so you are using v11.1.4.4.
Give us some time we will give you a special build.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Please download the cli driver special build from this link
http://www-933.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=All&platform=All&function=fixId&fixids=special_38551_DSClients-linuxx64-odbc_cli-11.1.4.4-FP004%3A568934929884115648&includeSupersedes=0
Thanks,
Akhil
