### ISSUE TITLE
Supporting Stored procedure with parameter and multi resultset

### ISSUE THREAD

**Issue by annfengcn** [ibmdb/go_ibm_db#28]
Call a stored procedure with input, out parameter
Some stored procedure will return multi-resultset

**Comment by maxatcn** [comment]
Same issue to me,  output always empty when calling a SP, 
for example,   call  sampleSP(var1,var2,var3,?,?,?)
The 3 output parameters always return empty.
Can you please have a check and advise?
Thank you.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 
all three variables are input variables?

Thanks
Akhil

**Comment by maxatcn** [comment]
Hi @akhilravuri1 
In my sample,  var1, var2 and var3 are input parameters.  The rest 3 ?  are output parameters.
Let me give more details, 

 ```
     sql := "call sampleSP(var1,var2,var3,?,?);"
       var sampleID string
	var diags string
	_, err = db.Exec(sql, sampleID, diags)
	if err != nil {
		return "error", err
	}
```
While,  sampleID and diags did not get the expected values(always empty).
Thanks.

**Comment by akhilravuri1** [comment]
@maxatcn  so only in params are working, out params are not working, right?

**Comment by maxatcn** [comment]
Correct @akhilravuri1 . In parameters works well, out parameter does not.

**Comment by akhilravuri1** [comment]
Thanks, @maxatcn once it is done we will get back to you.

**Comment by sedouard05** [comment]
I am having the same issue. Could you please inform me when this issue is resolved?

**Comment by maxatcn** [comment]
@akhilravuri1 ， sorry,  may I know a rough ETA for the fix?
For now, I have tasks rely on the fix.  Will need to make a schedule and put it into proper milestones.
Sorry for that.

**Comment by akhilravuri1** [comment]
@maxatcn and @sedouard05 
Last time when I tried to support Out Params the database/sql(go package) was not able to store the data returned by the driver in out variables so we dropped that feature. But let me check if there is any way to store the value. By Monday I will update you about this. 

If you have any seen any driver which supports Out params in Stored Procedures using database/sql Package, please paste the links.

Thanks,
Akhil

**Comment by sedouard05** [comment]
@akhilravuri1,

I found these drivers which have support for out parameters:
https://github.com/rana/ora
https://github.com/denisenkom/go-mssqldb

**Comment by guobinzhao** [comment]
@akhilravuri1 I meet the same issue - out parameter can not get back the data, I rate this issue for high prirority, please help to fix. thanks.

**Comment by akhilravuri1** [comment]
Hi @sedouard05 
https://github.com/rana/ora In this package stored procedure calls do not go through database/sql. Like pooling in our driver.
And https://github.com/denisenkom/go-mssqldb this is a native go driver package.
@guobinzhao we are trying to fill this gap. we will update you by the end of Tuesday

**Comment by akhilravuri1** [comment]
Hi @guobinzhao 
we are planning to add support for Out parameter in next release. As you said it is a high priority issue for you once we develop this feature we will create a new branch for this support.

Thanks,
Akhil

**Comment by guobinzhao** [comment]
@akhilravuri1 thanks for your support, is there any planned target date for next release?

**Comment by akhilravuri1** [comment]
As of now, we are planning to release in September. But If we finish Out parameter we will create a new branch and update you.

Thanks,
Akhil

**Comment by sedouard05** [comment]
@akhilravuri1,

Please inform me if you when you finish Out parameter.

**Comment by akhilravuri1** [comment]
Hi @ThuanQBui 
By Sept 4th  will support the OUT parameter but not INOUT parameter.
Thanks,
Akhil

**Comment by maxatcn** [comment]
@akhilravuri1,  I found a commit for this issue. Does that mean the fix work done and we may go ahead with a try?  
Thanks,
Max

**Comment by akhilravuri1** [comment]
Yes @maxatcn

**Comment by maxatcn** [comment]
@akhilravuri1,  I pulled the latest code and tried, but the OUT parameter are still empty.
Here is the sample code, can you please help check if anything wrong here? 

```
 sql := "call sampleSP(var1,var2,var3,?,?,?);"
   var sampleID string
   var sampleDesc string
   var diags string
   _, err = db.Exec(sql, sampleID, sampleDesc, diags)
   if err != nil {
   	return "error", err
   }
   fmt.Println(sampleID)
  fmt.Println(sampleDesc)
  fmt.Println(diags)
```
In the case above, it printed empty for all the 3 parameters.

Thanks,
Max

**Comment by akhilravuri1** [comment]
```
package main

import (
	"database/sql"
	"fmt"
	"time"

	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	con := "HOSTNAME=localhost;PORT=50000;DATABASE=go;UID=**;PWD=**"
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)
	}
	var (
        snapTime   time.Time
        dbsize     int64
        dbcapacity int64
        )
	fmt.Printf("snapshot time: %v, dbsize: %d, dbcapacity: %d\n", snapTime, dbsize, dbcapacity)
    procStmt := "call sysproc.get_dbsize_info(?, ?, ?,0)"
    _,err = db.Exec(procStmt,sql.Out{Dest: &snapTime},sql.Out{Dest: &dbsize},sql.Out{Dest: &dbcapacity})
    if err != nil {
        fmt.Println(err)
    }
    fmt.Printf("snapshot time: %v, dbsize: %d, dbcapacity: %d\n", snapTime, dbsize, dbcapacity)
}
```
please try to run this program and check whether you are getting output or not.

If you get the data then see how I have passed the variables to the SP and pass it in that way. I will update the readme on how to use SP with example once INOUT is also supported.

Thanks,
Akhil

**Comment by maxatcn** [comment]
@akhilravuri1,   seems something wrong with the sample code. 

```
[yabinma@oc7623857447 hellp]$ go run ./hello.go 
snapshot time: 0001-01-01 00:00:00 +0000 UTC, dbsize: 0, dbcapacity: 0
SQLExecute: {38553} [IBM][CLI Driver][DB2/LINUXX8664] SQL0443N  Routine "*IZE_INFO" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL1092 Token:USER999                                      ".  SQLSTATE=38553

snapshot time: 0001-01-01 00:00:00 +0000 UTC, dbsize: 0, dbcapacity: 0
```
I will try as your sample in my code. Thanks.

**Comment by akhilravuri1** [comment]
@maxatcn 
```SQL0443N Routine "*IZE_INFO" (specific name "") has returned an error```
this error will be thrown when a user has  SYSMON privilege. Please try to update your code according to my example and try it. Let me know if you face any issues.

Thanks,
Akhil

**Comment by maxatcn** [comment]
@akhilravuri1,   yes, I got the OUT values with the way sql.Out{Dest: &snapTime}.
For now, only one issue, the OUT values with extra bad code,
for example, 
```
a9b90b7b-8f40-4a3a-87cc-7c522ee19e1e^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```
Which a9b90b7b-8f40-4a3a-87cc-7c522ee19e1e is the expected return value(string type). We will need to remove the following meaningless characters '^@...'

This is my code for now,
```
var inceID string
var configHash string
var diags string
_, err = db.Exec(sqlString, sql.Out{Dest: &inceID}, sql.Out{Dest: &configHash}, sql.Out{Dest: &diags})
```
Thanks,
Max

**Comment by akhilravuri1** [comment]
@maxatcn 
column size is more than the value stored? like varchar(30) but stored "a"

Thanks,
Akhil

**Comment by maxatcn** [comment]
@akhilravuri1,  yes, the returned value size is smaller than the defined size.
For example, 
```
OUTPUT instanceID VARCHAR(128)
OUTPUT ConfigHash VARCHAR(32768)
```
Eventually, the defined size is more than the real returned value size.
How to deal with situation?

Thanks,
Max

**Comment by akhilravuri1** [comment]
@maxatcn  I am looking at it.

**Comment by akhilravuri1** [comment]
@maxatcn 
```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	con := "HOSTNAME=localhost;PORT=45050;DATABASE=go;UID=rakhil;PWD=Pranu134##"
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)
	}
	//st,err := db.Prepare("create procedure sp2(in var1 integer, in var2 integer, in var3 integer, out var4 integer) LANGUAGE SQL BEGIN   DECLARE V1 integer; SET V1 = var1 + var2 + var3; SET var4 = V1; END")
	st,err := db.Prepare("create or replace procedure sp(in var1 varchar(180), out var4 varchar(180)) LANGUAGE SQL BEGIN   DECLARE V1 varchar(180); SET V1 = var1; SET var4 = V1; END")
	if err != nil {
		fmt.Println(err)
	}
	res,err := st.Query();
	if err != nil {
		fmt.Println(err)
	}
	//var akhil int64;
	var akhil string
	//_,err = db.Exec("CALL sp2(1,2,3,?)", sql.Out{Dest: &akhil});
	_,err = db.Exec("CALL sp('AKHIL',?)", sql.Out{Dest: &akhil});
	if err != nil {
		fmt.Println(err)
	}
	st.Close();
	db.Close();
	fmt.Println(res);
	fmt.Print("THIS IS VALUE ",akhil);
}
```
Try this I was unable to reproduce the issue.

Thanks,
Akhil

**Comment by maxatcn** [comment]
@akhilravuri1,  the result for the code above,
```
[yabinma@oc7623857447 hellp]$ go run ./hello.go 
Stmt did not create a result set
<nil>
THIS IS VALUE AKHIL
```
The same as before, this is a BigSQL server.

Regards,
Max

**Comment by akhilravuri1** [comment]
@maxatcn this is only produced when the server is BigSql?

**Comment by akhilravuri1** [comment]
@maxatcn  I have changed the code please check it now and update me.

Are you facing the same problem while retrieving string data from the table?

Thanks
Akhil

**Comment by maxatcn** [comment]
Thanks @akhilravuri1,   tested with the new code,  no more characters, looks great.

Answers for the question:
1. this is only produced when the server is BigSql?
NO, there are many SP calls, but not every SP returns multiple OUT parameters.
2.  Are you facing the same problem while retrieving string data from the table?
NO, selecting from table looks fine until now.

Thanks & Regards,
Max

**Comment by sedouard05** [comment]
@akhilravuri1, 

When will the issue be in a release build?

**Comment by akhilravuri1** [comment]
@sedouard05 stored procedure support is already released. 
You can do go get -d github.com/ibmdb/go_ibm_db

Thanks,
Akhil
