### ISSUE TITLE
Got error when connecting db2

### ISSUE THREAD

**Issue by ZacZelner** [ibmdb/go_ibm_db#29]
I got one error when I am following the readme instructions:

zac$ go run db2connect1.go
# runtime/cgo
clang: error: -l/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include: 'linker' input unused [-Werror,-Wunused-command-line-argument]

How can I fix it?

------------
db2connect1.go:

package main

import (
    _ "github.com/ibmdb/go_ibm_db"
    "database/sql"
    "fmt"
)

func main(){
    con:="HOSTNAME=dashdb.services.eu-gb.bluemix.net;DATABASE=BLUDB;PORT=50000;UID=username;PWD=password"
 db, err:=sql.Open("go_ibm_db", con)
    if err != nil{
        
		fmt.Println(err)
	}
	db.Close()
}

--------I am using Mac, and here is the go env:

ruihuaz-MacBook-Pro:src zac$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zac/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zac/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-l/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hx/0bd3dc5j2f95jy7lxjf51w5c0000gn/T/go-build020472211=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

Did you set LDLIBRARYPATH?

**Comment by ZacZelner** [comment]
I just follow the readme, which value should I set to the LDLIBRARYPATH

**Comment by akhilravuri1** [comment]
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

**Comment by ZacZelner** [comment]
yes, I set.
export DB2HOME=/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-l$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

**Comment by akhilravuri1** [comment]
which version of go are you using?

**Comment by ZacZelner** [comment]
go version go1.12.6 darwin/amd64

**Comment by akhilravuri1** [comment]
Ok..let me check. I will try to install it in my system.
Can you uninstall the driver and install it again.

**Comment by ZacZelner** [comment]
mm...strange, I remove the driver and try to setep it again. However I got the error again when I am running setup.go:

ruihuaz-MacBook-Pro:installer zac$ go run setup.go
# runtime/cgo
clang: error: -l/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include: 'linker' input unused [-Werror,-Wunused-command-line-argument]

However, the first time I run this, do no have this error and successfully setup the driver

**Comment by akhilravuri1** [comment]
export CGO_CFLAGS=-i$DB2HOME/include
go run connect.go 
# runtime/cgo
clang: error: unknown argument: '-i/Users/amukherjee/sublime_sftp/open_source_new/GO_REPRO/GO_1/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver//include'
-------------
Set this env's:-(CFLAGS should be I not i)
export CGO_CFLAGS=-I$DB2HOME/include
export DYLD_LIBRARY_PATH=$DB2HOME/lib
export CGO_LDFLAGS=-L$DB2HOME/lib
go run connect.go 
CONNECTION SUCCESS

**Comment by ZacZelner** [comment]
my Mac version is 10.14.5
I just uninstall go, and re-setup it. I can now run setup.go but still got the same error when I run db2connect

-------------------------------
ruihuaz-MacBook-Pro:installer zac$ go run setup.go
darwin
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz
download successful
Extracting with tar -xvzf macos64_odbc_cli.tar.gz -C ./

ruihuaz-MacBook-Pro:installer zac$ export DB2HOME=/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ruihuaz-MacBook-Pro:installer zac$ export CGO_CFLAGS=-l$DB2HOME/include
ruihuaz-MacBook-Pro:installer zac$ export CGO_LDFLAGS=-L$DB2HOME/lib
ruihuaz-MacBook-Pro:installer zac$ export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
ruihuaz-MacBook-Pro:installer zac$ 
ruihuaz-MacBook-Pro:src zac$ go run db2connect.go
# runtime/cgo
clang: error: -l/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include: 'linker' input unused [-Werror,-Wunused-command-line-argument]

**Comment by akhilravuri1** [comment]
CGO_CFLAGS = -I(captial i) but you are typing -l(small L).

**Comment by ZacZelner** [comment]
ruihuaz-MacBook-Pro:go zac$ cd src
ruihuaz-MacBook-Pro:src zac$ export DB2HOME=/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ruihuaz-MacBook-Pro:src zac$ export CGO_CFLAGS=-I$DB2HOME/include
ruihuaz-MacBook-Pro:src zac$ export DYLD_LIBRARY_PATH=$DB2HOME/lib
ruihuaz-MacBook-Pro:src zac$ export CGO_LDFLAGS=-L$DB2HOME/lib
ruihuaz-MacBook-Pro:src zac$ go run db2connect.go
# github.com/ibmdb/go_ibm_db/api
github.com/ibmdb/go_ibm_db/api/api_unix.go:12:11: fatal error: 'sqlcli1.h' file not found
 #include <sqlcli1.h>
          ^~~~~~~~~~~
1 error generated.

ruihuaz-MacBook-Pro:src zac$ echo $CGO_CFLAGS
-I/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include

this file is in the $CGO_CFLAGS, but still go error

**Comment by akhilravuri1** [comment]
This is a different error.
This is because of sqlcli1.h file is not picked up by the CGO_LDFLAGS. 
Please check whether sqlcli1.h file is there in the lib or not. If present please set the env variables again.
please paste echo of $CGO_CFLAGS

**Comment by ZacZelner** [comment]
The file is in the /clidriver/include folder, I double checked.

Here are the settings:


ruihuaz-MacBook-Pro:src zac$ echo $CGO_CFLAGS
-I/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include
ruihuaz-MacBook-Pro:src zac$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zac/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zac/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hx/0bd3dc5j2f95jy7lxjf51w5c0000gn/T/go-build186033659=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by akhilravuri1** [comment]
I was able to reproduce the error that is because If you don't set the CGO_LDFLAGS. As I told you earlier the solution is set this env.

But you have set the env, please let me check is there any other way to reproduce the error.

Can you please confirm that you are checking the folder path where the clidriver is download by setup.go because you have downloaded one more clidriver using the link.

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Thanks!
 I DO use setup.go to install clidriver.

ruihuaz-MacBook-Pro:installer zac$ go run setup.go
darwin
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz
download successful
Extracting with tar -xvzf macos64_odbc_cli.tar.gz -C ./

I met this error before, that's the same reason with yours. I had not set the CGO_LDFLAGS correctly. But when I set the parameter correctly, It fixed. Then have the 

clang: error: -l/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include: 'linker' input unused [-Werror,-Wunused-command-line-argument]

**Comment by ZacZelner** [comment]
![go](https://user-images.githubusercontent.com/23731647/62778404-e8a4cb00-bae2-11e9-98c0-143d49ea6175.jpg)

**Comment by ZacZelner** [comment]
I change the CGO_CFLAGS = -I(small l), 
show error: 
clang: error: -l/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include: 'linker' input unused [-Werror,-Wunused-command-line-argument]

I change the CGO_CFLAGS = -I(BIG i), 
show error:
github.com/ibmdb/go_ibm_db/api/api_unix.go:12:11: fatal error: 'sqlcli1.h' file not found
#include <sqlcli1.h>
^~~~~~~~~~~
1 error generated.

**Comment by akhilravuri1** [comment]
There are 4 env's to be set:-
1) export DB2HOME=/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
2) export CGO_CFLAGS=-l$DB2HOME/include (here I is capital i, not small L ).
if you set small L you will get clang error.
3) export CGO_LDFLAGS=-L$DB2HOME/lib 
(If you don't set this after LDFLAGS you will get sqlcli1.h file not found).
4) export DYLD_LIBRARY_PATH=$DB2HOME/lib 
(If you don't set this you will get libdb2.lib not found or something like this) .

You have set all this env's.
 Please try this if you again face this error please uninstall and install it again and follow the same steps. 

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

Are able to connect to db2 server using our driver?
Can I close this issue?

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi,

I have tried to remove and re-setup the driver several times in the weekend, but still can not fix it.
Same error:
# github.com/ibmdb/go_ibm_db/api
github.com/ibmdb/go_ibm_db/api/api_unix.go:12:11: fatal error: 'sqlcli1.h' file not found
 #include <sqlcli1.h>
          ^~~~~~~~~~~
1 error generated.

**Comment by ZacZelner** [comment]
Sometime when I was running setup.go. it gave some warnings:

ruihuaz-MacBook-Pro:installer zac$ go run setup.go
# net
ld: warning: directory not found for option '-L/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib'
# crypto/x509
ld: warning: directory not found for option '-L/home/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib'
darwin
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz
download successful
Extracting with tar -xvzf macos64_odbc_cli.tar.gz -C ./

ruihuaz-MacBook-Pro:installer zac$

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

I have tried installing multiple times in my system I have never faced any issue. In setting up the driver. I think you are missing something while setting up the env's.

I will try to reproduce the issue which you are facing while running setup.go

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Thanks, I DO Thank you.

However, I have tried several times remove/re-install GO/ibmdb/Clidriver, but still have the issue. Really frustrated. :(

**Comment by ZacZelner** [comment]
Hi, 
I have fixed the issue. 
The folder should be /Users/zac in MAC, not /home/zac.

export DB2HOME=**/Users/**zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export DYLD_LIBRARY_PATH=$DB2HOME/lib
export CGO_LDFLAGS=-L$DB2HOME/lib

Thanks.
