### ISSUE TITLE
Got error while running example #1

### ISSUE THREAD

**Issue by tianhw2006** [ibmdb/go_ibm_db#31]
Hi,

I’m a newbie for golang. I followed the doc to install windows version. When I ran the first example, I got the error below. Could you please help me? Thank you very much.

```panic: SQLGetDiagRec failed: ret=-2
goroutine 1 [running]:
github.com/ibmdb/go_ibm_db.NewError(0x4ee1c5, 0xe, 0x4c3c20, 0x5c6fe0, 0xc00005a780, 0xc00007bf58)
                C:/gospace/src/github.com/ibmdb/go_ibm_db/error.go:58 +0x54b
github.com/ibmdb/go_ibm_db.initDriver(0x0, 0x0)
                C:/gospace/src/github.com/ibmdb/go_ibm_db/driver.go:29 +0x1f9
github.com/ibmdb/go_ibm_db.init.0()
                C:/gospace/src/github.com/ibmdb/go_ibm_db/driver.go:53 +0x29
Process finished with exit code 2
```

**Comment by akhilravuri1** [comment]
Hi 

Could you please give us the information of you golang and go env.

Have you copied the same example on the github( excluding the connection string)?

Thanks,
Akhil

**Comment by tianhw2006** [comment]
Sorry for late reply. I just run the program under cmd in admin permission, then it passed. Do you know why I have to run it in admin permission to connect database? Thanks

**Comment by akhilravuri1** [comment]
Hi @tianhw2006 
If you have permissions to read the data where go driver is installed then try to run the program once again under cmd in user permission?
If you don't have the permission to read the data of a driver where it is installed then it's behavior is right.

Thanks,
Akhil

**Comment by tianhw2006** [comment]
Is go driver installed under {GOPATH}\src\github.com\ibmdb\go_ibm_db\installer\clidriver\bin? Under this folder on my local, I saw a lot of dell and exe files, e.g. db2cli.exe

**Comment by akhilravuri1** [comment]
Yes, Go driver is installed in thatpath.

**Comment by tianhw2006** [comment]
Which file is the driver? I grant full controls of that folder to all users. But still not working. When I installed it, I didn’t use admin permission.

**Comment by akhilravuri1** [comment]
Please specify the platform which you are using?

**Comment by tianhw2006** [comment]
Windows 10. Go version: 1.12.8 windows/ amd64

**Comment by akhilravuri1** [comment]
{GOPATH}\src\github.com\ibmdb folder is the go driver folder, As it is in your go path it has access to read it. 

Add the below path your PATH env variable. Before adding just check bin folder is there in the below path or not.
```
{GOPATH}\src\github.com\ibmdb\go_ibm_db\installer\clidriver\bin
```

Thanks
Akhil

**Comment by akhilravuri1** [comment]
closing the issue as the user does not respond.
