### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by firewaternottogther** [ibmdb/go_ibm_db#32]
HI
Query most tables did not report errors, one of the tables reported errors.
![image](https://user-images.githubusercontent.com/39817883/64140121-e6a9ff80-ce35-11e9-8275-f196933e1690.png)

**Comment by akhilravuri1** [comment]
Hi @firewaternottogther 
could you please give us the table definition which caused the error.

Thanks,
Akhil

**Comment by firewaternottogther** [comment]
Hi @firewaternottogther 
This is someone else's data. I haven't reproduced it yet.As soon as it reappears, I'll give it to you.
Thanks,
Demond

**Comment by akhilravuri1** [comment]
closing the issue as there is no reply from the customer.
