### ISSUE TITLE
Some field of resultset is '\u0000' rather than the value from database

### ISSUE THREAD

**Issue by xnxuen** [ibmdb/go_ibm_db#33]
When we developed API with go_ibm_db, we found the result in API was different from the value read from the database. Here is what we found.

The result from API is shown as the following. The field `is_docker` is '\u0000'
```
[
    {
        "agent_class": "F",
        "dscount": "0",
        "hostname": "dv-0.dv.zen.svc.cluster.local",
        "is_docker": "\u0000",
        "node_description": "Not specified",
        "node_name": "AdminNode",
        "os_user": "bigsql",
        "port": "6414"
    },
]
```

However, the value read from database directly should be the following.
![image](https://user-images.githubusercontent.com/52769722/64340651-4280ae00-d019-11e9-8c0e-f08501728b6b.png)
The value of `IS_DOCKER` is 'N'

**Comment by akhilravuri1** [comment]
Hi @xnxuen 
what is the datatype of IS_DOCKER?

Thanks,
Akhil

**Comment by xnxuen** [comment]
Here is the datatype of `IS_DOCKER`
![image](https://user-images.githubusercontent.com/52769722/64341993-24687d00-d01c-11e9-8b27-0deb1e70dfa4.png)

And here is the datatype of `NODE_NAME`
![image](https://user-images.githubusercontent.com/52769722/64342199-96d95d00-d01c-11e9-892d-a0c704b6418f.png)

**Comment by akhilravuri1** [comment]
Hi @xnxuen 
I am able to reproduce the issue.
I am working on it.
Thanks,
Akhil

**Comment by xnxuen** [comment]
Thanks a lot. @akhilravuri1

**Comment by akhilravuri1** [comment]
Hi @xnxuen 
Code changes are made you can pull the latest code and use it.
Thanks,
Akhil

**Comment by xnxuen** [comment]
Thanks for your timely support! @akhilravuri1
