### ISSUE TITLE
Supporting Stored procedure with user-defined ARRAY parameter

### ISSUE THREAD

**Issue by sedouard05** [ibmdb/go_ibm_db#35]
I have a stored procedure that has a user-defined array IN parameter. I am unable to pass multiple values when I call the stored procedure.

The stored procedure is:
`
CREATE PROCEDURE \"REST_TESTPROC66_1_0\" (IN @arrayValues INTARRAY)\nLANGUAGE SQL\nDYNAMIC RESULT SETS 1\nBEGIN\nDECLARE C1 CURSOR WITH RETURN FOR \n-- BEGIN SQL STATEMENT\nSELECT * FROM TEST2 WHERE PKCOL IN (SELECT T.i FROM UNNEST(@arrayValues) as T(i));\n-- END SQL STATEMENT\nOPEN C1;\nEND\n"
`

I was able to get output when I used the Db2 CLI using the following command:
`db2 "call REST_TESTPROC66_1_0(array[1,2,3])`

**Comment by sedouard05** [comment]
Is a user-defined array parameter supported? 

Could you provide an example if it is supported?

**Comment by akhilravuri1** [comment]
Hi @sedouard05 
A user-defined array is supported only in the table insert but not in Stored Procedure.
```
func IntArray() error {
	db, _ := sql.Open("go_ibm_db", con)
	defer db.Close()
	db.Exec("Drop table arr")
	_, err := db.Exec("create table arr(var1 int)")
	if err != nil {
		return err
	}
	a := []int{2, 3}
	b := []int8{2, 3}
	c := []int16{2, 3}
	d := []int32{2, 3}
	e := []int64{2, 3}
	st, err := db.Prepare("Insert into arr values(?)")
	defer st.Close()
	if err != nil {
		return err
	}
	_, err = st.Query(a)
	if err.Error() != "Stmt did not create a result set" {
		fmt.Println("Error while inserting []int")
		return err
	}
	_, err = st.Query(b)
	if err.Error() != "Stmt did not create a result set" {
		fmt.Println("Error while inserting []int8")
		return err
	}
	_, err = st.Query(c)
	if err.Error() != "Stmt did not create a result set" {
		fmt.Println("Error while inserting []int16")
		return err
	}
	_, err = st.Query(d)
	if err.Error() != "Stmt did not create a result set" {
		fmt.Println("Error while inserting []int32")
		return err
	}
	_, err = st.Query(e)
	if err.Error() != "Stmt did not create a result set" {
		fmt.Println("Error while inserting []int64")
		return err
	}
	return nil
}
```

you can also find more examples in testdata/main.go file.

Thanks,
Akhil

**Comment by abecher22** [comment]
It would be great to have this support.

**Comment by akhilravuri1** [comment]
Hi @abecher22 

Thanks for showing interest in this feature. 

Can you please let us know how you will use this feature?

Because if your SQL statement does not require input parameters you can use the array insert with the present driver.

Thanks,
Akhil
