### ISSUE TITLE
unsupported Scan, storing driver.Value type <nil> into type *string

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#36]
Hi team,

When running the Go code, I got the error message back,
```
2019/09/24 06:46:11 sql: Scan error on column index 5, name "TDEF": unsupported Scan, storing driver.Value type <nil> into type *string
```

It could not be re-produced stable,  until now, I have not find the root cause.  Seeking your help if any comments.

The code is simple,

```
var (
		cids       string
		tschem     string
		tname      string
		numNodes   int64
		numSources int64
		tdef       string
)

...
for rows.Next() {
		err := rows.Scan(&cids, &tschem, &tname, &numNodes, &numSources, &tdef)
...
```

And I ran the sql with SQLEditor, seems the output is good. 2231 rows returned,  and I checked the TDEF column text, no NULL or blank found, all returned with text.
![image](https://user-images.githubusercontent.com/19709103/65491441-a0e6d100-dee1-11e9-8b94-be1a407962e9.png)

Any idea what could be possible causing this issue?   Thanks.

**Comment by akhilravuri1** [comment]
I will try to reproduce the issue. Are you sure that TDEF column does not contain any null value?

On which platform and are you using BigSql?

**Comment by maxatcn** [comment]
Yes, it is BigSQL.

Sorry  @akhilravuri1 , I found one line with empty.
![image](https://user-images.githubusercontent.com/19709103/65493104-c2958780-dee4-11e9-888a-4c3e92b30604.png)
Do you think this is why returned the error?

Also two table, with Chinese character in the TDEF,
![image](https://user-images.githubusercontent.com/19709103/65493284-24ee8800-dee5-11e9-835c-35be7c51f526.png)

Thanks.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 


> Do you think this is why returned the error?

This might not be the issue because with an empty value in the column it should not fail. I test it now it was not failing.

Can you create a sample table with 2 columns of varchar datatype and try to insert only one column value and do the select statement from golang.

Go program:-
```
package main

import (
	"database/sql"
	"fmt"
	
	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	con := "HOSTNAME=localhost;PORT=45050;DATABASE=go;UID=uname;PWD=pass"
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)
	}
	st,err := db.Prepare("select * from empty");
	rows,err := st.Query()	
	for rows.Next(){
		var out2,out4 string;
		rows.Scan(&out2,&out4)
		fmt.Println(out2,out4)
	}
	rows.Close()
	st.Close()
	db.Close()
}
``` 
Thanks,
Akhil

**Comment by maxatcn** [comment]
@akhilravuri1  I tried to create a table,   `create table empty(col1 varchar(20), col2 varchar(30));`
then, `insert into empty(col1) values('col1');`
insert into empty(col2) values('col2');
then, `select * from empty;`
got result,
![image](https://user-images.githubusercontent.com/19709103/65559114-ef40b200-df6b-11e9-891b-0b94cdc2f222.png)


And then run the sample go code,
![image](https://user-images.githubusercontent.com/19709103/65559146-0a132680-df6c-11e9-9abf-7c86905977ae.png)

You see, the third line, the second column 'col2', value 'col2' did not print out. But it did not return error message.
Thought?

Thanks, 
Max

**Comment by akhilravuri1** [comment]
Hi @maxatcn 
Thanks for the information I was able to reproduce the issue.
```
C:\Go_Programs>go run empty_char.go
akhil
akhil ravuri

C:\Go_Programs>go run empty_char.go
This is next [97 107 104 105 108]
This is next <nil>
akhil
This is next [97 107 104 105 108]
This is next [114 97 118 117 114 105]
akhil ravuri
This is next <nil>
This is next [97 107 104 105 108]

```

I am trying to analyze the issue...this is very strange. I tried to print the data at the after the next..our driver(Next) has returned the data but Scan is not scanning the after the nil. Scan() is not our function. It is a database/sql package function. 

I guess Scan is not able to read NULL data. I will try to find a solution If not we can raise an issue in the go community.

Thanks,
Akhil

**Comment by maxatcn** [comment]
Thank you @akhilravuri1 .  Please let me know once solution is found or workaround. We are facing  a release and the DCUT is next Monday.  We will need to make a decision based on the situation. 

Thanks,
Max

**Comment by akhilravuri1** [comment]
Hi @maxatcn 

I have tried multiple ways and was able to get the data but you have to reframe it according to your format ( Like how to you need it ).

1.
```
                var out2,out4 sql.NullString;
		err = rows.Scan(&out2,&out4)
		if err != nil{
			fmt.Println(err)
		}
		if out2.Valid {
			fmt.Print(out2.String)
		} else {
			fmt.Print(" ")
		}
		if out4.Valid {
			fmt.Println(out4.String)
		} else{
			fmt.Println(" ")
OUTPUT:
akhil
akhil  ravuri
          akhil
```
2.
```
var out2,out4 interface{};
err = rows.Scan(&out2,&out4)
	if err != nil{
		fmt.Println(err)
	}
fmt.Print(out2)
fmt.Print(out4)

OUTPUT:-
[97 107 104 105 108] <nil>
[97 107 104 105 108] [114 97 118 117 114 105]
<nil> [97 107 104 105 108]
```
Convert the above to string.

Thanks,
Akhil

**Comment by maxatcn** [comment]
Thank you @akhilravuri1 .  I will try it.

**Comment by maxatcn** [comment]
One more question @akhilravuri1 .   I see the string is replaced with sql.NullString,  how about int64? Thanks.

**Comment by akhilravuri1** [comment]
> how about int64?

sql.NullInt64, sql.NullString,sql.NullFloat64, sql.NullBool, sql.NullTime

Thanks,
Akhil
