### ISSUE TITLE
SELECT works incorrectly with Unicode

### ISSUE THREAD

**Issue by VazMike** [ibmdb/go_ibm_db#37]

**Comment by VazMike** [comment]
Suppose I have table `log`:

**Comment by VazMike** [comment]
Suppose I have table `log`:
| id | emoji |
| 0  | 😊 |

I run following snippet
```
var emoji string
const stmt = `SELECT emoji FROM log WHERE id = 0;`
db.QueryRow(stmt).Scan(&emoji)
fmt.Println([]byte("😊"))
fmt.Println([]byte(emoji))
```

the output is

![image](https://user-images.githubusercontent.com/14861435/65870345-b5fdad00-e384-11e9-83c5-146535e81b62.png)

**Comment by VazMike** [comment]
I'm using Go 1.13, Windows.

**Comment by VazMike** [comment]
BTW `INSERT`ing Unicode data works correctly.

**Comment by akhilravuri1** [comment]
what is the datatype of emoji in the database?

**Comment by VazMike** [comment]
VARCHAR(2000)

**Comment by akhilravuri1** [comment]
try creating emoji as a binary data type.

**Comment by VazMike** [comment]
I need to use varchar

**Comment by akhilravuri1** [comment]
An image has to be stored in binary format or else data might get lost.

**Comment by VazMike** [comment]
emoji is not an image, it is unicode symbol

**Comment by akhilravuri1** [comment]
Hi @VazMike 

set this env  variable and run the program
```
set DB2CODEPAGE=1208
```

**Comment by VazMike** [comment]
thanks a lot
this solves the issue.
