### ISSUE TITLE
"unsupported column type 16" error when running SELECT on BOOLEAN columns

### ISSUE THREAD

**Issue by xartishuk** [ibmdb/go_ibm_db#38]
Hi, 
I have a table `T` with a `BOOLEAN` column `IS_ACTIVE`. If i run `SELECT IS_ACTIVE FROM T;` I get "unsupported column type 16" error. INSERT works fine.
I tried running `SELECT CAST(IS_ACTIVE AS BOOLEAN) FROM T;` - that doesn't work either.
As a temporary fix i'm running `SELECT CAST(IS_ACTIVE AS CHAR(1)) FROM T;`.

I'm on go1.13, Windows. This issue doesn't reproduce via jdbc driver, so I assume it's go_ibm_db.

**Comment by akhilravuri1** [comment]
Hi @xartishuk 
I was not able to reproduce the issue.
Please do go get again and try to run the program.

Thanks,
Akhil

**Comment by xartishuk** [comment]
@akhilravuri1  I was running it on v0.1.0 before. Now i tried it on v0.1.1 and on the last commit in master (a760002e475f459de2c0176e7d635b9815553767). Sadly, both didn't work, i still get the same error.

**Comment by akhilravuri1** [comment]
Hi @xartishuk 

I was not able to reproduce the issue.
Can you give us some more information like the clidriver version, server version which platform?

**Comment by akhilravuri1** [comment]
I was able to reproduce the issue. we will fix this.

**Comment by akhilravuri1** [comment]
@xartishuk  I have fixed the issue, please pull the latest code and try.

**Comment by xartishuk** [comment]
Yes, that works.
Thanks a lot @akhilravuri1 .
