### ISSUE TITLE
DB2 iSeries

### ISSUE THREAD

**Issue by MaitreDede** [ibmdb/go_ibm_db#39]
Hi,
It seams that your library does not work with a DB2 iSeries (AS400).
Error message is : `SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "<ip address>".  Communication function detecting the error: "connect".  Protocol specific error code(s): "110", "*", "*".  SQLSTATE=08001`

The database is firewalled, using these rules : https://render-prd-trops.events.ibm.com/support/pages/tcpip-ports-required-ibm-i-access-and-related-functions

Which parameters of the connectionstring may be missing ?

**Comment by akhilravuri1** [comment]
I was able to connect to iSeries machine using the below connection string
```
con := "hostname=host;database=db;port=100;uid=uname;pwd=pass"
```
can you please give me the parameters which you used in the connection string.
Thanks,
Akhil

**Comment by MaitreDede** [comment]
My constring is like  `con := "hostname=host;database=db;uid=uname;pwd=pass"`. I have a kind of tcp proxy to access the AS400. The IBM iAccess client works fine, and other apps in java (using jt400 driver).

This golang drivers seams to timeout when trying to connect, since default port used (50000) is not the default port of the DB2 iSeries on AS400.
What is your port 100 ? I only forwarded the ports listed in the IBM page https://render-prd-trops.events.ibm.com/support/pages/tcpip-ports-required-ibm-i-access-and-related-functions

**Comment by akhilravuri1** [comment]
Just check where your server is running and give the port number. My server is running at 446 so I have to give 446.

**Comment by MaitreDede** [comment]
My serverv follows the ports list I linked, so database, without SSL is 8471. I tried it without success.

**Comment by akhilravuri1** [comment]
run with 8471 and  9471. Then add protocol=TCP/IP and run with 8471 and  9471.
Please paste the output here. (total 4 comibantions)

**Comment by MaitreDede** [comment]
Hi,

Without `protocol=TCP/IP` I have the error I wrote on my fist message.

With `protocol=TCP/IP`, I get a better error message : `SQLDriverConnect: {08001} [IBM][CLI Driver] SQL1013N  The database alias name or database name "" could not be found.  SQLSTATE=42705`. The empty db name is the real error message, not truncated.

My connectionstring is : `HOSTNAME=myhost;DATABASE=mydb;UID=theuser;PWD=secret;PORT=8471;protocol=TCP/IP`

**Comment by MaitreDede** [comment]
I tried to add `DBALIAS=mydb`, the error message contains the `mydb` value. When removing the `DATABASE=` parameter I get the same error. With IBM iAccess client tools, I know my database name. It seams that the `db2cli` tool does not see it...

**Comment by akhilravuri1** [comment]
Are you sure that the database exists?
This error is thrown when database is not found. I was able to connect to this connection string
```
"hostname=local;database=H720060X;port=446;uid=akhil;pwd=***"
```

can you please give us some information like which version of the clidriver and server are you using.
Please take the trace and share the trace files.
trace commands
```
db2trc on -f 1.trc 
<Run the test to repro issue>
db2trc off

db2trc fmt -c 1.trc 1.drda

db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
db2trc fmt -cli 1.trc 1.cli
```

**Comment by akhilravuri1** [comment]
Hi @MaitreDede 
I have made some changes please clone the iseries branch and try to make the connection with the below format.

there should not be '/' in the protocol.
```
HOSTNAME=myhost;DATABASE=mydb;UID=theuser;PWD=secret;PORT=8471;protocol=TCPIP
```

**Comment by MaitreDede** [comment]
I am trying to use the `db2cli` app (downloaded with installer/setup.go) :
`db2cli execsql -execute -connstring ${CON} -inputsql sql.txt -outfile out.txt` with `protocol=TCP/IP` : I have the same error `The database alias name or database name "" could not be found.`.
With `protocol=TCPIP`, app does not respond. 
With you updated code, `TCP/IP` is error, `TCPIP` stuck.

**Comment by akhilravuri1** [comment]
> can you please give us some information like which version of the clidriver and server are you using.
> Please take the trace and share the trace files.
> trace commands
> 
> ```
> db2trc on -f 1.trc 
> <Run the test to repro issue>
> db2trc off
> 
> db2trc fmt -c 1.trc 1.drda
> 
> db2trc flw 1.trc 1.flw
> db2trc fmt 1.trc 1.fmt
> db2trc fmt -cli 1.trc 1.cli
> ```

sorry for the late response.
Please take this trace and share the files.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
> With `protocol=TCPIP`, app does not respond

app does not respond means command-line app or go app.

**Comment by akhilravuri1** [comment]
@MaitreDede try to add the database details to the db2cli.ini file in clidriver/cfg folder.
If not working with the above add the database details to clidriver/cfg/db2dsdriver.cfg.sample
and copy the file data to the clidriver/cfg/db2dsdriver.cfg(```cp /home/rakhil/clidriver/cfg/db2dsdriver.cfg.sample /home/rakhil/clidriver/cfg/db2dsdriver.cfg```) and try to connect

**Comment by akhilravuri1** [comment]
closing the issue as the user did not respond

**Comment by MaitreDede** [comment]
Hi @akhilravuri1 
Sorry for late response (project priorities). I am still trying to connect to my customer's db2 iseries.

I am first trying to use the db2cli tools following [this tutorial](https://globalengineer.wordpress.com/2017/02/28/configuration-of-db2-cliodbc-driver/). The `db2cli validate -dsn xxx` shows the parameters I have put in the `db2cli.ini` file.
But when trying to connect (db2cli execsql -dsn xxx), it stills display errors.

I am trying different parameters from https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0007964.html
