### ISSUE TITLE
Question / issue regarding character encoding and possibly endianess (UTF-16LE ?)

### ISSUE THREAD

**Issue by Knacktus** [ibmdb/go_ibm_db#41]
Hi all,

German umlaute are not converted correctly by the Scan() function in our environment. Everything else is working fine.

I don't know on which hardware our DB2 instances are running. Could be quite old UNIX, or new Linux.

When using the AQT client (http://www.querytool.com), all German umlaute are displayed correctly (but I don't know the encoding). When exporting from this tool to a CSV and loading to Visual Studio Code, the data is displayed correctly using the UTF-16LE encoding.

Is it possible that the character encoding of our DB2 instance is UTF-16LE whereas the driver is using plain UTF-16? Or big endianess? Sorry, I'm not the biggest expert in encodings and endianess.

If the issue could come from the driver using an encoding that does not fit our servers, is there a way to work around this? Can I convert the data somehow in my Go code?

All opinions are appreciated! Thanks a lot,

Jan

**Comment by akhilravuri1** [comment]
Scan() function is not go_ibm_db driver function. It is a sql package(standard go package) function. 
Please give us a sample program that can reproduce the issue.

Thanks,
Akhil

**Comment by Knacktus** [comment]
This is the code:


```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/ibmdb/go_ibm_db"
)

type Hierarchie struct {
	PROD     string
	KNOTEN   string
}

func ReadHierarchie(productId string) ([]Hierarchie, error) {
	con := "HOSTNAME=xxxxx;DATABASE=xxxxx;PORT=xxxxx;UID=xxxxx;PWD=xxxxx"
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)
	}
	defer db.Close()

	rows, err := db.Query("call xxxxx.xxxxx ('xxxxx','xxxxx','xxxxx','xxx','','','','','',100,'','','')")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	hierarchies := make([]Hierarchie, 0)
	for rows.Next() {
		var hierarchie Hierarchie
		err = rows.Scan(
			&hierarchie.PROD,
			&hierarchie.KNOTEN,
		)
		if err != nil {
			return nil, err
		}

		hierarchies = append(hierarchies, hierarchie)
	}
	return hierarchies, nil
}
```
Results are generally as expected, except for the all German umlaute. E.g.

Expected: Radträger
Actual: Radtr�ger

Hence my assumption that somewhere in the conversion chain the encodings are wrong.

**Comment by akhilravuri1** [comment]
@Knacktus 

I have taken some traces and the driver is returning the correct data. But somehow when you do rows.Scan() the sql package scan function is making some wrong encoding so please try to scan the data as byte and search how to convert the byte[] to a string that has german characters.

If I find a way to do it I will update you.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
@Knacktus 
please run this ``` set DB2CODEPAGE=1208``` command in your cmd and run the program.

**Comment by Knacktus** [comment]
@akhilravuri1 

Thanks a lot! Your first suggestion solved the issue. I've also set the DB2CODEPAGE environment variable to different encodings but with no positive effect. I guess the underlying DB2 driver gets the default encoding right (Windows 1252 in my case). That's why the ODBC base client has been working fine.

So the issue was indeed in Go's default conversion to utf-8.

Following the working code:

```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/ibmdb/go_ibm_db"
	"golang.org/x/text/encoding/charmap"
)

type Hierarchie struct {
	PROD   string
	KNOTEN string
}

func ReadHierarchie(productId string) ([]Hierarchie, error) {
	con := "HOSTNAME=xxxxx;DATABASE=xxxxx;PORT=xxxxx;UID=xxxxx;PWD=xxxxx"
	db, err := sql.Open("go_ibm_db", con)
	if err != nil {
		fmt.Println(err)
	}
	defer db.Close()

	rows, err := db.Query("call xxxxx.xxxxx ('xxxxx','xxxxx','xxxxx','xxx','','','','','',100,'','','')")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	hierarchies := make([]Hierarchie, 0)
	for rows.Next() {
		var hierarchie Hierarchie
		var (
			prod   []byte
			knoten []byte
		)
		err = rows.Scan(
			&prod,
			&knoten,
		)
		if err != nil {
			return nil, err
		}
		hierarchie.PROD = DecodeWindows1252(prod)
		hierarchie.KNOTEN = DecodeWindows1252(knoten)
		hierarchies = append(hierarchies, hierarchie)
	}

	return hierarchies, nil
}

func DecodeWindows1252(byteSlice []byte) string {
	decoder := charmap.Windows1252.NewDecoder()
	decodedByteSlice, _ := decoder.Bytes(byteSlice)
	return string(decodedByteSlice)
}
```
