### ISSUE TITLE
Access to the system database

### ISSUE THREAD

**Issue by tredoe** [ibmdb/go_ibm_db#44]
I cann't connect to the system database (to create a database), getting the next error:
```
ERROR [08004][IBM] SQL30061N The database alias or database name "SYSIBM          " was not found a the remote node. SQLSTATE=08004.
```

The sample program I'm trying to execute is:
```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	db, err := connectDB()
	if err != nil {
		println("Connect Error:\n" + err.Error())
		return
	}
	if err = db.Ping(); err != nil {
		println("Ping Error:\n" + err.Error())
		return
	}
	db.Close()
}

func connectDB() (*sql.DB, error) {
	driver := "go_ibm_db"
	connection := fmt.Sprintf(
		"Hostname=127.0.0.1;Protocol=tcpip;Port=50000;Database=%s;Uid=%s;Pwd=%s",
		"SYSIBM",
		"db2admin",
		"***",
	)
	return sql.Open(driver, connection)
}
```

Also, I've tested it with different database names (DB2, DBCOPY1, DB2INST1, DB2LUW) getting the same error.

At the error message, it shows `"SYSIBM          "`, so it is adding spaces to the given name. Does the error could be due to it?

* * *
I can only use the command 'db2' to create a database using `db2 CREATE DATABASE [name]` but I want to access to the system database to be able to create it from there, as can be done from other databases (MariaDB, MySQL, PostgreSQL, SQL Server).

**Comment by akhilravuri1** [comment]
Hi @tredoe 
On which platform are you working, db2 version and golang version.

Thanks,
Akhil

**Comment by tredoe** [comment]
Windows 10 Pro v1903
go version go1.13.4 windows/amd64
IBM DB2 Versión 11.5

**Comment by akhilravuri1** [comment]
Hi @tredoe 

I was able to connect to the database. please try to connect to the database using the db2clp command prompt and check whether the database exists or not.
Thanks,
Akhil

**Comment by tredoe** [comment]
What database are you connecting?

**Comment by akhilravuri1** [comment]
Hi @tredoe 
I am using the v11.1 LUW server and I am not using db2admin.
I have just opened the command prompt with admin privileges but with normal privileges also it works fine.
![image](https://user-images.githubusercontent.com/32290825/68649205-1832fb80-0548-11ea-86e4-b4add8853d57.png)


Thanks
Akhil.

**Comment by tredoe** [comment]
I am also running it from the prompt command.
Could you run this code to know if you can create a table?

```
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/ibmdb/go_ibm_db"
)

const (
	user   = "db2admin"
	pass   = "***"
	dbname = "SYSIBM"
)

func main() {
	db, err := connectDB()
	if err != nil {
		log.Fatal("Connect Error:\n" + err.Error())
	}
	if err = db.Ping(); err != nil {
		log.Fatal("Ping Error:\n" + err.Error())
	}
	defer db.Close()
	fmt.Println("Conected: ok")

	stmt := fmt.Sprintf("CREATE DATABASE %q user '%s' password '%s';",
		dbname, user, pass,
	)
	if _, err = db.Exec(stmt); err != nil {
		log.Fatal("Create Error:\n" + err.Error())
	}
	fmt.Println("Table created: ok")
}

func connectDB() (*sql.DB, error) {
	driver := "go_ibm_db"
	connection := fmt.Sprintf(
		"Hostname=127.0.0.1;Protocol=tcpip;Port=50000;Database=%s;Uid=%s;Pwd=%s",
		dbname, user, pass,
	)
	return sql.Open(driver, connection)
}
```

**Comment by akhilravuri1** [comment]
Hi @tredoe 
```
C:\Go_Programs>go run tredoe.go
Connected: ok
2019/11/13 13:59:19 Create Error:
SQLExecute: {42601} [IBM][CLI Driver][DB2/NT64] SQL0104N  An unexpected token ""go" user 'rakhil' password '****'" was found following "CREATE DATABASE ".  Expected tokens may include:  "<space>".  SQLSTATE=42601
exit status 1

C:\Go_Programs>
```
You can see that the connection was ok.
There was an error because you cannot create a database with db.Exec() API.
As of now, the golang driver does not support create a database.

Thanks,
Akhil
