### ISSUE TITLE
Request to support create/drop a database.

### ISSUE THREAD

**Issue by tredoe** [ibmdb/go_ibm_db#45]
Please, could you to add support to create and drop a database with db.Exec() API?

Thanks in advance!

**Comment by akhilravuri1** [comment]
Hi @tredoe 
Our driver is based on the go standard package database/sql.
As of now, database package does not support create a database (admin operation) so we cannot support it.

If go add's support for creating a database. we will also support that.

Thanks,
Akhil.

**Comment by tredoe** [comment]
I can create databases using the package database/sql at other DBMSs like Mysql, PostgreSQL, MariaDB, and Microsoft SQL Server (it's that I've tested until now).

By now, only faills with IBM DB2. The next ones to testing are Oracle and Firebird. So it is not an issue related to the support at database/sql.

To create a database, there is to connect to the master database and then to send a statement like 'CREATE DATABASE [name]'

**Comment by akhilravuri1** [comment]
> I can create databases using the package database/sql at other DBMSs like Mysql, PostgreSQL, MariaDB, and Microsoft SQL Server (it's that I've tested until now)

Can you send me the GitHub links of these drivers?

**Comment by tredoe** [comment]
MySQL/MariaDB: "github.com/go-sql-driver/mysql"
PostgreSQL: "github.com/lib/pq"
SQL Server: "github.com/denisenkom/go-mssqldb"

In fact, I could addthe code where it shows how I create a database. MySQL or PostgreSQL?

**Comment by akhilravuri1** [comment]
Hi @tredoe 
In IBM db2 to create a database, you have to disconnect from the database.

And in the go-driver, we can add that support if you are not connecting to the database.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
> could you to add support to create and drop a database with db.Exec() API?

@tredoe we cannot add a create database with db.Exec() but we can try to add this support with a new api.
Sample:-
```
import 'github.com/ibmdb/go_ibm_db'
func main(){
//connection string without database name.
go_ibm_db.CreateDB('databasename', 'host=localhost;uid=uname;pass=password,port=40000')
}
```

**Comment by tredoe** [comment]
It is not necessary to add a new API.

If the connection string has the key 'Database', then it connect to such DB, else it connects to the instance where we could send a statement like "CREATE DATABASE".

**Comment by akhilravuri1** [comment]
> If the connection string has the key 'Database', then it connect to such DB, else it connects to the instance where we could send a statement like "CREATE DATABASE".

Are you talking about IBM DB?
Did you pass the connection string(like datbase, host, uid, port, pass) or dsn=name?

**Comment by tredoe** [comment]
I'm talking about IBM DB2, and I used the string "Hostname=127.0.0.1;Protocol=tcpip;Port=50000;Database=%s;Uid=%s;Pwd=%s".

It was only an idea to not have to add a different API.

**Comment by akhilravuri1** [comment]
> I'm talking about IBM DB2, and I used the string "Hostname=127.0.0.1;Protocol=tcpip;Port=50000;Database=%s;Uid=%s;Pwd=%s".
> 
> It was only an idea to not have to add a different API.

Our clidriver does not work in that way...It uses different api to create a database.

Create database is admin operation.

**Comment by tredoe** [comment]
With Oracle there is also to use a command to create a database (sqlplus; db2 for IBM2), so there is no need to change the API on this driver. Those DBMSs work of that way and there is no need to change the API to be enable to create/drop a database.

Thanks anyway!

**Comment by akhilravuri1** [comment]
Hi @tredoe 

I don't know how oracle handles that create a database query but in our db2 you have to call a new api to create the database, not the exec api.

You can check this documentation where we support create and drop database API's.
https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#createDbSyncApi

we have taken your request to support create and drop database api but it will be supported in the same way how node js supports.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @tredoe 

Database creation support has been added. Please pull the latest code and use it.

Thanks,
Akhil
