### ISSUE TITLE
How to set connect timeout and execution timeout？

### ISSUE THREAD

**Issue by nh-live** [ibmdb/go_ibm_db#46]
How to set connect timeout and execution timeout？

**Comment by akhilravuri1** [comment]
Hi @nh-live 

To set a connection timeout you need to use ConnectTimeout= 100; in the connection string.
I don't know about execution time out but we can set Query timeout in Db2. For this, you need to pass QueryTimeout=100 in the connection string.

So your connection string will be:
```
"Hostname=localhost;Protocol=tcpip;Port=45050;Database=%s;Uid=%s;Pwd=%s;ConnectTimeout=100;QueryTimeout=100;"
```

If you are asking about execution timeout, not the query timeout can you give me some more information

Thanks,
Akhil

**Comment by nh-live** [comment]
Thank you for your prompt reply, which has solved my problem. Please add a complete description of the connection parameters. Thank you.

**Comment by akhilravuri1** [comment]
> Please add a complete description of the connection parameters.

You can find the description parameter in the IBM info center.
we will update the readme with parameters list or with info center link.

Thanks,
Akhil

**Comment by nh-live** [comment]
tsk
