### ISSUE TITLE
Grant user into a database

### ISSUE THREAD

**Issue by tredoe** [ibmdb/go_ibm_db#49]
I'm tryint to grant an user into a database but, is it possible that can not be created with the `db.Exec()` API? Just like it was happening at creating a database.

```
/*
[Shell]

db2 CREATE DATABASE demo_dev
net user demo demo /ADD
*/

package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/ibmdb/go_ibm_db"
)

const (
	//service = "DB2"
	dbname = "demo_dev"

	instUser = "db2admin"
	instPass = "***"

	dbUser = "demo"
	dbPass = "demo"
)

func main() {
	db, err := connectDB()
	if err != nil {
		log.Fatal("Connect Error:\n" + err.Error())
	}
	if err = db.Ping(); err != nil {
		log.Fatal("Ping Error:\n" + err.Error())
	}
	defer db.Close()
	fmt.Println("Connected: ok")

	stmt := fmt.Sprintf("GRANT DBADM ON DATABASE TO %s;", dbUser)
	if _, err = db.Exec(stmt); err != nil {
		log.Fatal("Grant Error:\n" + err.Error())
	}
	fmt.Println("Grant: ok")
}

func connectDB() (*sql.DB, error) {
	driver := "go_ibm_db"
	connection := fmt.Sprintf(
		"Hostname=127.0.0.1;Protocol=tcpip;Port=50000;Database=%s;Uid=%s;Pwd=%s",
		dbname, instUser, instPass,
		//"Hostname=127.0.0.1;Protocol=tcpip;Port=50000;Database=%s;Uid=%s;Pwd=%s",
		//dbname, dbUser, dbPass,
	)
	return sql.Open(driver, connection)
}
```

SQLSTATE=42502

**Comment by akhilravuri1** [comment]
Hi @tredoe 
grant permissions query will be executed using Exec func only...It does not require any new api support like a database.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
> SQLSTATE=42502

If the user doesn't have the PRIVILEGE TO PERFORM OPERATION then you will get this error.

Thanks,
Akhil

**Comment by tredoe** [comment]
> > SQLSTATE=42502
> 
> If the user doesn't have the PRIVILEGE TO PERFORM OPERATION then you will get this error.

I also had tested it with the administrator user:

`instUser = "db2admin"`

**Comment by akhilravuri1** [comment]
Hi @tredoe 
I was unable to reproduce the issue. can you please paste the exact output.

![image](https://user-images.githubusercontent.com/32290825/70423865-5b738200-1a94-11ea-81b6-37c47ff209bc.png)

Please try to grant the permissions from the db2cmd (CLP) command prompt and paste the output.

Thanks,
Akhil

**Comment by tredoe** [comment]
> I was unable to reproduce the issue. can you please paste the exact output.
> 
> Please try to grant the permissions from the db2cmd (CLP) command prompt and paste the output.

Hi,
Are you using the program that I added to grant the permissions?

**Comment by tredoe** [comment]
> db2 connect to demo_dev
> db2 GRANT DBADM ON DATABASE TO demo

It was run correctly from the command line but I want that it works from a SQL connection.

**Comment by tredoe** [comment]
The error that I get is:

```
SQLExecute: {42502} [IBM][CLI Driver][DB2/NT64] SQL0552N  "DB2ADMIN" does not have the privilege to perform operation "GRANT".  SQLSTATE=42502
```

**Comment by akhilravuri1** [comment]
You need to check whether your group(under which this user is present) has permissions or not.
This is not a bug you need to contact your db2administartor (server team) to grant the permissions.

Thanks,
Akhil

**Comment by tredoe** [comment]
Ok. Then I'll do it from the command line.
Thanks!
