### ISSUE TITLE
Error font 

### ISSUE THREAD

**Issue by levinhne** [ibmdb/go_ibm_db#5]
Select DB error font 

data": {
        "jobs": [
            {
                "id": 3,
                "name": "N\ufffdng-l\ufffdm-ng\u001a nghi\u001ap"
            },
            {
                "id": 9,
                "name": "Thi\u001at k\u001a"
            },
            {
                "id": 20,
                "name": "Truy\u001an th\ufffdng - Marketing"
            },
            {
                "id": 22,
                "name": "IT-Ph\u001an m\u001am"
            },
            {
                "id": 23,
                "name": "IT-Ph\u001an C\u001ang"
            },
            {
                "id": 25,
                "name": "T\ufffdi ch\ufffdnh"
            },

**Comment by akhilravuri1** [comment]
can you provide more information about the error.
