### ISSUE TITLE
The env setting does NOT work in docker file?

### ISSUE THREAD

**Issue by ZacZelner** [ibmdb/go_ibm_db#50]
Hi, I am using dockerfile to build one application using go_ibm_db.

The application works well in my local mac, and I am using:
export DB2HOME=/Users/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export DYLD_LIBRARY_PATH=$DB2HOME/lib
export CGO_LDFLAGS=-L$DB2HOME/lib

however, I set these env in the dockerfile, and can not work well.
dockerfile:
ENV DB2HOME=/Users/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ENV CGO_CFLAGS=-I$DB2HOME/include
ENV DYLD_LIBRARY_PATH=$DB2HOME/lib
ENV CGO_LDFLAGS=-L$DB2HOME/lib

I print these env values out before I run the application in the dock images.
cd /go/src/demowithJS

echo $DB2HOME
echo $CGO_CFLAGS
echo $DYLD_LIBRARY_PATH
echo $CGO_LDFLAGS

bee run

There is the error:
zac$ docker run -it -p 8081:8081 ocvtest
/Users/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
-I/Users/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include
/Users/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
-L/Users/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0
2019/12/10 02:16:52 INFO     ▶ 0001 Using 'demowithJS' as 'appname'
2019/12/10 02:16:52 INFO     ▶ 0002 Initializing watcher...
github.com/ibmdb/go_ibm_db/api
github.com/astaxie/beego/config
github.com/astaxie/beego/utils
github.com/astaxie/beego/vendor/gopkg.in/yaml.v2
# github.com/ibmdb/go_ibm_db/api
../github.com/ibmdb/go_ibm_db/api/api_unix.go:12:11: fatal error: sqlcli1.h: No such file or directory
 // #include <sqlcli1.h>
           ^~~~~~~~~~~
compilation terminated.

Please help us, thanks!

**Comment by ZacZelner** [comment]
IF I changed the 
dockerfile:
ENV DB2HOME=/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver (delete the Users/zac)
ENV CGO_CFLAGS=-I$DB2HOME/include
ENV DYLD_LIBRARY_PATH=$DB2HOME/lib
ENV CGO_LDFLAGS=-L$DB2HOME/lib

error changed to be:
2019/12/10 02:50:29 ERROR    ▶ 0003 Failed to build the application: # github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: cannot find -ldb2
/usr/bin/ld: cannot find -ldb2

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

Why are you using DYLD_LIBRARY_PATH?

If you are using docker you might be creating windows or Linux containers. so you need to set PATH or LD_LIBRARY_PATH

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi Akhil,

I have changed the dockerfile to be:
FROM golang:1.13.4 

ENV PATH $PATH:$GOPATH/bin
ENV DB2HOME=/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ENV CGO_CFLAGS=-I$DB2HOME/include
ENV LD_LIBRARY_PATH=/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
ENV CGO_LDFLAGS=-L$DB2HOME/lib

ADD github.com /go/src/github.com
...

still got the same issue with my comment 1#:

# github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: cannot find -ldb2
/usr/bin/ld: cannot find -ldb2
collect2: error: ld returned 1 exit status
2019/12/11 01:40:11 ERROR    ▶ 0003 Failed to build the application: # github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: cannot find -ldb2
/usr/bin/ld: cannot find -ldb2
collect2: error: ld returned 1 exit status

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 


> ENV DB2HOME=/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver

This has to be DB2HOME=$GOAPTH/src/github.com/ibmdb/go_ibm_db/installer/clidriver
and LD_LIBRARY_PATH=$GOAPTH/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

**Comment by ZacZelner** [comment]
Hi Akhil,

I have changed the dockerfile to be:
FROM golang:1.13.4


ENV PATH $PATH:$GOPATH/bin
ENV DB2HOME=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ENV CGO_CFLAGS=-I$DB2HOME/include
ENV LD_LIBRARY_PATH=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
ENV CGO_LDFLAGS=-L$DB2HOME/lib


Still got the same error:
github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: cannot find -ldb2
/usr/bin/ld: cannot find -ldb2
collect2: error: ld returned 1 exit status
2019/12/11 07:54:33 ERROR    ▶ 0003 Failed to build the application: # github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: cannot find -ldb2
/usr/bin/ld: cannot find -ldb2
collect2: error: ld returned 1 exit status

Please help me to check it again.

I have print all the env before I run the go application.
echo $GOPATH
echo $DB2HOME
echo $CGO_CFLAGS
echo $LD_LIBRARY_PATH
echo $CGO_LDFLAGS

zac$ docker run -it -p 8081:8081 ocvtest
/go
/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
-I/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include
/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
-L/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 
can you confirm that clidriver is present in this path(/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver)

**Comment by ZacZelner** [comment]
Yes, the clidriver is in this path.
The application can work well in my local Mac.

**Comment by akhilravuri1** [comment]
Can you share the docker file?

**Comment by akhilravuri1** [comment]
Your DockeFile should insclude
```
cd /root \
go get -d github.com/ibmdb/go_ibm_db \  
cd /root/go/src/github.com/ibmdb/go_ibm_db/installer \
go run setup.go
ENV DB2HOME=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver \
IBM_DB_HOME=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver \
CGO_CFLAGS=-I/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include \
CGO_LDFLAGS=-L/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib \
LD_LIBRARY_PATH=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib:$LD_LIBRARY_PATH \
PATH=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/bin:$PATH

```

**Comment by ZacZelner** [comment]
Here is my dockerfile:

dockerfile:
FROM golang:1.13.4 

ENV PATH $PATH:$GOPATH/bin
ENV DB2HOME=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ENV CGO_CFLAGS=-I$DB2HOME/include
ENV LD_LIBRARY_PATH=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
ENV CGO_LDFLAGS=-L$DB2HOME/lib

ADD github.com /go/src/github.com

ADD build.sh /build.sh

RUN chmod +x /build.sh

RUN /build.sh 

ADD demowithJS /go/src/demowithJS

ADD run.sh /

RUN chmod +x /run.sh

CMD ["/run.sh"]

build.sh:
#/bin/bash 

cd /go/src/github.com/beego/bee

go install

run.sh:

#!/bin/bash

cd /go/src/demowithJS

echo $GOPATH
echo $DB2HOME
echo $CGO_CFLAGS
echo $LD_LIBRARY_PATH
echo $CGO_LDFLAGS

bee run

**Comment by ZacZelner** [comment]
changed the dockerfile:
FROM golang:1.13.4 

ENV PATH=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver/bin:$PATH
ENV DB2HOME=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ENV IBM_DB_HOME=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ENV CGO_CFLAGS=-I$DB2HOME/include
ENV LD_LIBRARY_PATH=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib:$LD_LIBRARY_PATH
ENV CGO_LDFLAGS=-L$DB2HOME/lib

same error

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

I have understood a little bit about this why it is failing.
Are you trying to copy the driver from the local dir?

Thanks,
Akhil

**Comment by ZacZelner** [comment]
yes, I am copy the local dir, since there are lots of other sources I need under gitHub.com too, so I just copy them all into Docker.

I also thought the go_ibm_db in the GitHub need to install the driver firstly, so I chose to copy it from local.

If this is not supported, how should I write the go_ibm_db part in the docker file?

**Comment by akhilravuri1** [comment]
No that should not be a problem..I wanted to in the same how you are doing so I asked.

Can you please add this line before running the sample program
```
RUN go env
```
and please paste the output.
check whether CGO_LDFLAGS and CGO_CFLAGS have the values that are not.

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Here is the result
I think they have the values.

Step 13/16 : ADD run.sh /
 ---> Using cache
 ---> f201721d0eb5
Step 14/16 : RUN go env
 ---> Running in 46b25c050c41
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build360717037=/tmp/go-build -gno-record-gcc-switches"
Removing intermediate container 46b25c050c41
 ---> 232f62cc7624
Step 15/16 : RUN chmod +x /run.sh
 ---> Running in b6a7728ee800
Removing intermediate container b6a7728ee800
 ---> 1d4258131098
Step 16/16 : CMD ["/run.sh"]
 ---> Running in e289486496b1
Removing intermediate container e289486496b1
 ---> 2abe7ffabcdf
Successfully built 2abe7ffabcdf
Successfully tagged ocvtest:latest

**Comment by akhilravuri1** [comment]
> CGO_CFLAGS="-I/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include"

In this -I is capital 'i' (I) right not small L (l)

Thanks
Akhil

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

```
FROM amazonlinux:latest
RUN yum install -y gcc git go wget pam tar make gcc-c++ 
RUN cd /root \
&& go get -d github.com/ibmdb/go_ibm_db \
&& cd /root/go/src/github.com/ibmdb/go_ibm_db/installer \
&& go run /root/go/src/github.com/ibmdb/go_ibm_db/installer/setup.go
ENV DB2HOME=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver \ 
CGO_CFLAGS=-I/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include \ 
CGO_LDFLAGS=-L/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib \
LD_LIBRARY_PATH=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib:$LD_LIBRARY_PATH
RUN go env
COPY conn.go /root/
RUN go run /root/conn.go
```

with this Dockerfile, I was able to build successfully.

**Comment by ZacZelner** [comment]
yes, it's capital i, not small L, I double checked it.

**Comment by ZacZelner** [comment]
Can you share the dockfile's path?
Where is your application folder? The go/src/github.com is under your application folder?
What's root folder in your example?

Or you can see my folders and try to fix my dockerfile which I just run

User/zac/go/src/demowithJS
                                |
                                |--dockerfile
                           github.com
                                |--go_ibm_db
                                |--beego
            

Dockerfile:
FROM golang:1.13.4

#author
MAINTAINER Zac

# Install beego and the bee dev tool*
RUN go get github.com/astaxie/beego && go get github.com/beego/bee
RUN go get -d github.com/ibmdb/go_ibm_db \
&& cd /go/src/github.com/ibmdb/go_ibm_db/installer \
&& go run /go/src/github.com/ibmdb/go_ibm_db/installer/setup.go

ENV DB2HOME=/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver \ 
CGO_CFLAGS=-I/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include \ 
CGO_LDFLAGS=-L/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib \
LD_LIBRARY_PATH=/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib:$LD_LIBRARY_PATH
RUN go env

COPY . /go/src/demowithJS/
WORKDIR /go/src/demowithJS

EXPOSE 8080

CMD ["bee", "run"]

**Comment by ZacZelner** [comment]
The result and error when I run the dockerfile above:


Step 6/10 : RUN go env
 ---> Running in a6f6d028af4d
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build008589969=/tmp/go-build -gno-record-gcc-switches"
Removing intermediate container a6f6d028af4d
 ---> e5b70b6ced1f
Step 7/10 : COPY . /go/src/demowithJS/
 ---> 6451a22cf7b4
Step 8/10 : WORKDIR /go/src/demowithJS
 ---> Running in 8bd0455e3f34
Removing intermediate container 8bd0455e3f34
 ---> f38a18b67251
Step 9/10 : EXPOSE 8080
 ---> Running in c9a18fed763a
Removing intermediate container c9a18fed763a
 ---> 7ac29748d90c
Step 10/10 : CMD ["bee", "run"]
 ---> Running in e98e4afb547a
Removing intermediate container e98e4afb547a
 ---> d2a5c4e3647a
Successfully built d2a5c4e3647a
Successfully tagged ocvgit:latest

**Different error:**

# demowithJS
/usr/bin/ld: warning: libxml2.so.2, needed by /go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib/libdb2.so, not found (try using -rpath or -rpath-link)
2019/12/13 02:57:08 SUCCESS  ▶ 0003 Built Successfully!
2019/12/13 02:57:08 INFO     ▶ 0004 Restarting 'demowithJS'...
2019/12/13 02:57:08 SUCCESS  ▶ 0005 './demowithJS' is running...
./demowithJS: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory

**Comment by akhilravuri1** [comment]
> Can you share the dockfile's path?
> Where is your application folder? The go/src/github.com is under your application folder?
> What's root folder in your example?

Sorry, I am very new to docker...I just started it. I will try to run your Dockerfile.

One more question...Your docker is installed in Windows or Linux.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
With my docker file are you able to install the driver and run .go file?

**Comment by ZacZelner** [comment]
One more question...Where your docker is installed? --- Windows or Linux.
--On Mac

With my docker file are you able to install the driver and run .go file?

--Yes, I can install the .go file when I am packing the docker image.

Step 3/10 : RUN go get github.com/astaxie/beego && go get github.com/beego/bee
 ---> Using cache
 ---> 89d0fbfdf3d1
Step 4/10 : RUN go get -d github.com/ibmdb/go_ibm_db && cd /go/src/github.com/ibmdb/go_ibm_db/installer && go run /go/src/github.com/ibmdb/go_ibm_db/installer/setup.go
 ---> Running in 001c1b3b6a10
linux
linuxx64_odbc_cli.tar.gz
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
download successful
Extracting with tar -xvzf linuxx64_odbc_cli.tar.gz -C ./
clidriver/
clidriver/cfg/
clidriver/cfg/DigiCertGlobalRootCA.arm
clidriver/cfg/db2cli.ini.sample
clidriver/cfg/db2dsdriver.cfg.sample
clidriver/cfg/db2dsdriver.xsd
clidriver/cfgcache/
.....

**Comment by akhilravuri1** [comment]
You downloading the Mac version driver and you are copying it to the Linux platform and trying to execute.

So please copy the clidriver for the Linux platform.  In mac clidriver, you will have .dylib files and in Linux, we have .so files so that's why it says not able to find .so files.

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 
Are you able to install the driver?

**Comment by ZacZelner** [comment]
Hi Akhil，

I am confusing about the linux and mac version.

There is no difference in your readme about linux and Mac.
All using:

go get -d github.com/ibmdb/go_ibm_db
and just set the different env.

I have tried to download the go_ibm_db from github directly and install the driver when I am running the dockerfile.

It should download the linux version right? But still got the error.
Step 4/10 : RUN go get -d github.com/ibmdb/go_ibm_db && cd /go/src/github.com/ibmdb/go_ibm_db/installer && go run /go/src/github.com/ibmdb/go_ibm_db/installer/setup.go
---> Running in 001c1b3b6a10
linux
linuxx64_odbc_cli.tar.gz
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
download successful
Extracting with tar -xvzf linuxx64_odbc_cli.tar.gz -C ./
clidriver/

Please help me about my confusion. Thanks!

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

Our go_ibm_db is a wrapper on the cli driver which is a platform-specific driver.

Go-Driver(which call's cli api's to do oper) -->cli driver(platform-specific win,Linux,mac) --> Database.

When you install our go-driver it will detect your platform and downloads that platform cli driver.

You have installed the driver on mac where our go-driver detected mac and downloaded mac specific driver then you copied it to the Linux platform and tried to compile it.

windows clidriver will have .dll, Linux will have .so and mac will have .dylib files so you are getting the error .so files not found.

Is it clear?

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1,

I have NOT copied my own go_ibm_db folder into the docker in the past times.

I directly use 
RUN go get -d github.com/ibmdb/go_ibm_db \
&& cd /go/src/github.com/ibmdb/go_ibm_db/installer \
&& go run /go/src/github.com/ibmdb/go_ibm_db/installer/setup.go
in the dockerfile.

I think the docker will choose the linux version, right?

**Comment by ZacZelner** [comment]
See from the docker packing log:
Step 4/10 : RUN go get -d github.com/ibmdb/go_ibm_db && cd /go/src/github.com/ibmdb/go_ibm_db/installer && go run /go/src/github.com/ibmdb/go_ibm_db/installer/setup.go
---> Running in 001c1b3b6a10
linux
linuxx64_odbc_cli.tar.gz
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
download successful
Extracting with tar -xvzf linuxx64_odbc_cli.tar.gz -C ./
clidriver/

it downloaded the https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/**linuxx64_odbc_cli.tar.gz**

**Comment by akhilravuri1** [comment]
Yes, If it is a Linux container it will download Linux clidriver. If it is a windows container then it will download windows cli driver.

**Comment by ZacZelner** [comment]
But it still go error:
Hi @akhilravuri1 
/usr/bin/ld: warning: libxml2.so.2, needed by /go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib/libdb2.so, not found (try using -rpath or -rpath-link)
2019/12/13 02:57:08 SUCCESS ▶ 0003 Built Successfully!
2019/12/13 02:57:08 INFO ▶ 0004 Restarting 'demowithJS'...
2019/12/13 02:57:08 SUCCESS ▶ 0005 './demowithJS' is running...
./demowithJS: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory

can NOT find the so files

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

Can you run go env before the step where you are facing the error and run cd to the clidriver/lib directory and do ls.

Paste the output.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Please paste me the LD_LIBRARY_PATH variable value also.

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 

echo $GOPATH
echo $DB2HOME
echo $CGO_CFLAGS
echo $LD_LIBRARY_PATH
echo $CGO_LDFLAGS

ls /go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

 zac$ docker run -it -p 8080:8080 ocvgit
/go
/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
-I/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include
/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib **($LD_LIBRARY_PATH)**
-L/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
**icc  libDB2xml4c.so  libDB2xml4c.so.58	libDB2xml4c.so.58.0  libdb2.so	libdb2.so.1  libdb2clixml4c.so	libdb2clixml4c.so.1**  (The ls result)

The error shows it needs libxml2.so.2, it truly does not in the lib folder.

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 
which flavor are you using in Linux?

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
try running this command
```
apt-get install libxml2
```

**Comment by ZacZelner** [comment]
@akhilravuri1 ,

How can I run this command?

I tried this in the dockerfile:
RUN go get github.com/astaxie/beego && go get github.com/beego/bee
RUN go get -d github.com/ibmdb/go_ibm_db \
&& cd /go/src/github.com/ibmdb/go_ibm_db/installer \
&& go run /go/src/github.com/ibmdb/go_ibm_db/installer/setup.go

RUN apt-get install libxml2

but got error:
Step 4/13 : RUN go get -d github.com/ibmdb/go_ibm_db && cd /go/src/github.com/ibmdb/go_ibm_db/installer && go run /go/src/github.com/ibmdb/go_ibm_db/installer/setup.go
 ---> Using cache
 ---> 041a33b6debf
Step 5/13 : RUN apt-get install libxml2
 ---> Running in e6446313d14e
Reading package lists...
Building dependency tree...
Reading state information...
Package libxml2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libxml2' has no installation candidate
The command '/bin/sh -c apt-get install libxml2' returned a non-zero code: 100


apt-get is not supported on Mac also.

**Comment by akhilravuri1** [comment]
You can try this 
```
FROM amazonlinux:latest
RUN yum install -y gcc git go wget pam tar make gcc-c++ 
RUN cd /root \
&& go get -d github.com/ibmdb/go_ibm_db \
&& cd /root/go/src/github.com/ibmdb/go_ibm_db/installer \
&& go run /root/go/src/github.com/ibmdb/go_ibm_db/installer/setup.go
ENV DB2HOME=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver \ 
CGO_CFLAGS=-I/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include \ 
CGO_LDFLAGS=-L/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib \
LD_LIBRARY_PATH=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib:$LD_LIBRARY_PATH
RUN go env
RUN yum install libxml2
COPY conn.go /root/
RUN go run /root/conn.go
```

**Comment by ZacZelner** [comment]
hi @akhilravuri1 
Can you tell me where you put your dockerfile? Under root folder? the conn.go is in the same folder too?
The path of the dockerfile is very important to the docker image.

I am trying to combined the code you provided to me, this time, the docker can not find the  setup.go.

Step 6/16 : RUN go get -d github.com/ibmdb/go_ibm_db
 ---> Running in 2a326d0803ea
Removing intermediate container 2a326d0803ea
 ---> 81cd3f9be30c
Step 7/16 : RUN cd /go/src/github.com/ibmdb/go_ibm_db/installer && go run /go/src/github.com/ibmdb/go_ibm_db/installer/setup.go
 ---> Running in b6bb158825af
/bin/sh: line 0: cd: /go/src/github.com/ibmdb/go_ibm_db/installer: No such file or directory
The command '/bin/sh -c cd /go/src/github.com/ibmdb/go_ibm_db/installer && go run /go/src/github.com/ibmdb/go_ibm_db/installer/setup.go' returned a non-zero code: 1

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

You can do one thing instead of writing full path you can add 
```
RUN cd $GOPATH/src/github.com/ibmdb/go_ibm_db/installer && go run setup.go
``` 

Thanks
Akhil

**Comment by akhilravuri1** [comment]
> Can you tell me where you put your dockerfile? Under root folder? the conn.go is in the same folder too?
> The path of the dockerfile is very important to the docker image.

I have created a new folder in that I have placed conn.go file and Dockerfile. From that directory
I have opened cmd and ran docker build . this will take the dockerfile and create an image.

root folder? -- if you do not specify any folder where to install then it will use root. 

If you use my dockerfile I am building it in amazonlinux  so I have installed all the required packages which are missing in amazon linux. If you shift to amazon linux then you will have to find the missing files for those packages.

What happened when you installed libxml2?

Did it worked or you faced any other problem?

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 
since I see the /root in your log, I was thinking your folder name is root.
your dockerfile:
RUN cd **/root** \
&& go get -d github.com/ibmdb/go_ibm_db \
&& cd /root/go/src/github.com/ibmdb/go_ibm_db/installer \
&& go run /root/go/src/github.com/ibmdb/go_ibm_db/installer/setup.go
ENV DB2HOME=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver \ 


For the libxml2, right now It can be installed in the docker file.
However, I still got the error: can not finding the installer folder by using $GOPATH

Step 5/16 : **RUN yum install libxml2
 ---> Running in a5018efe8237**
Loaded plugins: ovl, priorities
Package libxml2-2.9.1-6.amzn2.3.3.x86_64 already installed and latest version
Nothing to do
Removing intermediate container a5018efe8237
 ---> 02e414034d17
Step 6/16 : RUN go get github.com/astaxie/beego && go get github.com/beego/bee
 ---> Running in d88cc9b34249
Removing intermediate container d88cc9b34249
 ---> 8eeaaaf24738
Step 7/16 : RUN go get -d github.com/ibmdb/go_ibm_db
 ---> Running in 5fa550a97595
Removing intermediate container 5fa550a97595
 ---> b4abc829f2b0
Step 8/16 : **RUN cd $GOPATH/src/github.com/ibmdb/go_ibm_db/installer && go run setup.go**
 ---> Running in 11d1a0a28d9d
/bin/sh: line 0: cd: /src/github.com/ibmdb/go_ibm_db/installer: No such file or directory

I thought if I just use 
FROM golang:1.13.4

It can find the installer folder, but If I added the 
FROM golang:1.13.4 
FROM amazonlinux:latest

It can not. golang must be my first layer in my dockerfile. If I changed the sequence, like:
FROM amazonlinux:latest
FROM golang:1.13.4 

The go related source code wont work,

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

> It can find the installer folder,

Is it working for you are not?

On which platform are you installing the driver?
I will try to write a dockerfile in the same way how you are doing it.

Thanks
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 ,

I finally succeed.

It's very strange that I use $GOPATH, it can not find the folder, although it points to /root/go.
I directly use /root/go, and succeeded.

RUN cd /root/go/src/github.com/ibmdb/go_ibm_db/installer && go run setup.go

Summary for this issue and solution (Using Mac):
1. Docker use Linux version and better to install the cli driver in docker file.
2. Need to add these packages:
RUN yum install -y gcc git go wget pam tar make gcc-c++ 
RUN yum install libxml2

3. Set the folder and env path carefully, 

Final Docker file (not include the application, just the go_ibm_db part)
FROM golang:1.13.4 
FROM amazonlinux:latest
RUN yum install -y gcc git go wget pam tar make gcc-c++ 
RUN yum install libxml2
RUN ls /root/go/src/github.com
RUN cd /root/go/src/github.com/ibmdb/go_ibm_db/installer && go run setup.go
ENV DB2HOME=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver \ 
CGO_CFLAGS=-I/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include \ 
CGO_LDFLAGS=-L/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib \
LD_LIBRARY_PATH=/root/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
ENV GOBIN=/usr/local/go/bin
ENV PATH=$PATH:$GOBIN:/root/go/bin

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 
Thanks for the information and dockerfile.

Why are you trying to set GOBIN manually?

Thanks
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 
Oh, this is for my beego application path setting, maybe we can delete it.

**Comment by akhilravuri1** [comment]
Okay..Thanks

**Comment by akhilravuri1** [comment]
@ZacZelner can you tell me on which platform have you installed our go driver. (In which Linux flavor)

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 , I am using Mac to develop my Go app. And this issue is on the process of using Docker to create the image. 

I think Docker choose the default linux version? I am not sure whether I get your question.

**Comment by akhilravuri1** [comment]
Got it!! you are specifying any platform on the docker file.

Thanks,
Akhil
