### ISSUE TITLE
How do we specify security mechanism?

### ISSUE THREAD

**Issue by prasanthcaibmcom** [ibmdb/go_ibm_db#52]
When the security is set , for example, to *Client*, we must specify securityMechanism=4.

In JDBC this is done by setting "properties".

What is the equivalent with the go_ibm driver ?

**Comment by akhilravuri1** [comment]
Hi @prasanthcaibmcom 
Add "authentication=CERTIFICATE | SERVER | SERVER_ENCRYPT | SERVER_ENCRYPT_AES | DATA_ENCRYPT | KERBEROS | GSSPLUGIN " in connection strinng.

https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0054601.html

please check the documentation in the readme file below example1. That link contains all the list of connection parameters that odbc driver supports.

Thanks
Akhil

**Comment by prasanthcaibmcom** [comment]
Thanks Akhil....how does this correlate to AUTHENTICATION=CLIENT on the db2 side ?  I do not see a similar option for that here.

Furthermore how does this relate to ssl ? 
Is AUTHENTICATION=CERTIFICATE equivalent to enabling SSL?
For example in JDBC we set sslConnection to true as a parameter.
Is there a way to trust self signed certificates?  

Thank you!

**Comment by akhilravuri1** [comment]
Hi @prasanthcaibmcom 

If you want to use you nned to add SECURITY=SSL and change the port (replace it with ssl port).

Add SSLCERTIFICATE="PATH".

If you have kdb and sth the please refer to the link which I have provided in the above comment.

Thanks,
Akhil

**Comment by prasanthcaibmcom** [comment]
I suppose I am not clear the relationship between:

**Comment by akhilravuri1** [comment]
Hi @prasanthcaibmcom 

Which server are you using?

If you are using the LUW server you have to use SECURITY and SSLCERTIFICATE.

If you are using zos server you have to use AUTHENTICATION.

Thanks,
Akhil

**Comment by prasanthcaibmcom** [comment]
And SSLCERTIFICATE will be a path to a trusted public certificate?

Does SSLCERTIFICATE need to be set when connecting to a public certificate with a certified source ?

the ibm drivers have SERVER_ENCRYPT | SERVER_ENCRYPT_AES.  Is SERVER_ENCRYPT equal to DES ?  Is there a way to set DES on the connect string ?

There is an `encryptionAlgorithm` argument in the JCC driver...what's the equivalent?

We did some testing with SERVER_ENCRYPT and SERVER_ENCRYPT_AES, but it seems that both of them work regardless of if the server `alternate_auth_enc` is set to AES_CMP or AES_ONLY.  What's the difference?
