### ISSUE TITLE
Alter table statement is not supported for BIGSQL

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#56]
Dear team,

I got one issue and the go code return error message,
```
2020/02/04 06:12:17 sql: ALTER TABLE SYSIBM.SYSTABLES DEACTIVATE ROW ACCESS CONTROL;
2020/02/04 06:12:17 [Error]: SQLExecute: {     } [IBM][CLI Driver][DB2/LINUXX8664] SQL0142N  The SQL statement is not supported.
```
I have monitored for a while, but there is not any error message reported in backend database server(BigSQL,  there is no error message in db2diag log at the time the issue occurred).

I am asking for your help.  If the go_ibm_db driver could return the error message before reaching to database?

Also, this issue only occurred when the test server provisioned and run the go code first time. Since the second time, the go code run successfully, there is not any problem.
Thanks.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 

There was a similar error while creating a view in BIGSQL #42 

This is error is thrown by the server and I have checked all the traces I could not find any error from go_ibm_db or clidriver. So I asked them to talk with the BIGSQL server team and why it not accepting this query.

**Comment by akhilravuri1** [comment]
HI @maxatcn 
one more thing which I came to know was it returns statement is not supported for the first time but it might have altered the table. Please check whether it altered the table or not.

At least, while creating view the scenario was same...It returns statement is not supported but it has created the view.

Thanks,
Akhil

**Comment by maxatcn** [comment]
Thanks for the quick response @akhilravuri1 ， I will check if the actual result is correct even reporting the error message.
Also a question, in the previous error in #42, is there any error messge found in db2diag log?  In my case, there is not any message produced in db2diag log. Thanks.

**Comment by maxatcn** [comment]
I checked the result, the alter table does not work.   No worries anyway.  It is reasonable I think.  
This is not a single statement run.   I have 5 sql statements,  and I put it into a transaction, one of them failed, all rolled back I think.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 

I have check all the logs. From logs I came to know that server is returning the error.

I have checked with our node-ibmdb driver also. Error is always same. 
1st time it fails and 2nd time it creates.

Thanks,
Akhil

**Comment by maxatcn** [comment]
Thanks @akhilravuri1 .    Ning told me,  `sql := "begin execute immediate 'CREATE SCHEMA \"" + schemaName + "\"';end"`,  this can be a workaround.
A question, if this can be used in transaction?

My code like, 
```
tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	for _, v := range sqlList {
		output, err := runCMD(v)
		if err != nil {
			log.Println("[Error]: " + err.Error())
			return err
		}
		sql := strings.Trim(string(output), "\n")

		_, err = tx.Exec(sql)
		if err != nil {
			log.Println("sql: " + sql)
			log.Println("[Error]: " + err.Error())
			return err
		}
	}

	err = tx.Commit()
	if err != nil {
		log.Println("[Error]: " + err.Error())
		return err
	}
	return nil
```

sqllist is a 5 sql statements slide. In the transaction, these 5 sqls run one by one. Is it ok if I put all the 5 sql statement as the workaround  format?  Thanks.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 

what does sqlList contain? proper SQL's or a SQL broken into 5 strings? because from you comment I can see only one sql.

can you list the SQL's?

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
> sqllist is a 5 sql statements slide. In the transaction, these 5 sqls run one by one. Is it ok if I put all the 5 sql statement as the workaround format?

yes you can perform all these 5 sql statements as single using compound statements.
please go through this doc..https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0004239.html
