### ISSUE TITLE
When cli driver used on Db2 server it does not behave like type-2 driver

### ISSUE THREAD

**Issue by rahul-s-s** [ibmdb/go_ibm_db#59]
(1) When cli driver is used directly on db2 server without credentials it does not work similar to **java type-2 driver** (meaning, only DB name is required and not user credentials)
(2) Error is thrown during query execution and not during connection

Sample code
```golang
package main

import (
    _ "github.com/ibmdb/go_ibm_db"
    "database/sql"
    "fmt"
)

func main(){
    //con:="HOSTNAME=localhost;DATABASE=METADB;PORT=50000;UID=username;PWD=password"
    con:="HOSTNAME=localhost;DATABASE=METADB;PORT=50000"
    fmt.Println("Connection string=", con)
    db, conErr:=sql.Open("go_ibm_db", con)
    if conErr != nil{
      fmt.Println("Error while connecting DB", conErr)
    }else{
      _, qErr := db.Query("select min(db_conn_time) as db_conn_time,current timestamp as db_current_time from table (MON_GET_DATABASE(0));")
        if qErr != nil {
          fmt.Println("Error while executing query=", qErr)
        }
      db.Close()
    }
}
```

**Scenario-1**
When CLI driver is used on db2 server without userid/password it throws error
**Anticipated behavior**  
1. CLI driver works as type-2 driver when used on DB2 server (no uid/password required)
2. Error should be thrown during connection and not during query execution.
3. Error should meaningful

```
export LD_LIBRARY_PATH=$HOME/clidriver/lib
env CGO_CFLAGS=-I$HOME/clidriver/include CGO_LDFLAGS=-L$HOME/clidriver/lib go run -v db_connection.go -d METADB -t localhost -r 50000
command-line-arguments
Connection string= HOSTNAME=localhost;DATABASE=METADB;PORT=50000
Error while executing query= SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30082N  Security processing failed with reason "17" ("UNSUPPORTED FUNCTION").  SQLSTATE=08001
```  

**Scenario-2**
When db2 libraries is used with driver on db2 server without userid/password it throws meaningful error 
**Anticipated behavior**  
1. CLI driver works as type-2 driver when used on DB2 server (no uid/password required)
2. Error should be thrown during connection and not during query execution.

```
export LD_LIBRARY_PATH=$HOME/sqllib/lib
env CGO_CFLAGS=-I$HOME/clidriver/include CGO_LDFLAGS=-L$HOME/clidriver/lib go run -v db_connection.go -d METADB -t localhost -r 50000
Connection string= HOSTNAME=localhost;DATABASE=METADB;PORT=50000
Error while executing query= SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30082N  Security processing failed with reason "3" ("PASSWORD MISSING").  SQLSTATE=08001
```

- os Version: CentOS 7.0

- cli-driver Version: v.0.2.0

- Db2 Server Version: 11.1.4
- go Version: 1.13.6 linux/amd64
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
O111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/db2inst1/.cache/go-build"
GOENV="/home/db2inst1/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/db2inst1/src"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/db2inst1/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/db2inst1/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build189927149=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

Steps to Reproduce:

1. Install driver on Db2 server
2. Run go test program as described above

**Comment by akhilravuri1** [comment]
Hi @rahul-s-s 

sql.Open() will not connect to the database(validating the connection string) it just takes the connection details and stores it in the object. 

when you perform db.Prepare() it will validate the connection string and preform operation(calls connect api and prepare api).

sql.Open() which is database/sql function is designed in such a way that it will not authenticate the connection string but checks whether the connection string contains all the required details or not like uid and password.

So that's why you may face 2 Scenarios.

How to solve this?

Use db.Ping() function which connects to the database.

Thanks,
Akhil

**Comment by rahul-s-s** [comment]
Hi @akhilravuri1  - Thanks for explanation, `db.Ping works` however it addresses part of the issue. 

Main part of scenario is using cli-driver like type-2 driver. When running from database server which means userid / password not is required when connecting to DB from server itself.

Could you please help to understand the following?

1. When driver is used on DB server is it possible connecting to DB without userid/password?
2. If driver is used on DB server how the connection to DB is made? local connection or network connection?

**Comment by akhilravuri1** [comment]
Hi @rahul-s-s 

```
package main

import(
	"fmt"
    _ "github.com/ibmdb/go_ibm_db"
    "database/sql"
)

func main(){
    db, err := sql.Open("go_ibm_db", "dsn=ruby")
    if err != nil {
        fmt.Println(err)
    }
	fmt.Println(db)
	if err = db.Ping(); err != nil {
        fmt.Println(err)
    } else {
	fmt.Println("connection successful")
	}
}
```
if you pass dsn instead of database it will connect to database without passing uname and password.

Thanks,
Akhil

**Comment by rahul-s-s** [comment]
Thanks @akhilravuri1  for your help.
