### ISSUE TITLE
Error /usr/bin/ld: cannot find -ldb2

### ISSUE THREAD

**Issue by tungmt** [ibmdb/go_ibm_db#6]
Hi, I apply your instruction for linux environment in dockerfile like that.

RUN go run /go/src/github.com/ibmdb/go_ibm_db/installer/setup.go
ENV DB2HOME /go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
ENV CGO_CFLAGS -I$DB2HOME/include
ENV CGO_LDFLAGS -L$DB2HOME/lib
ENV LD_LIBRARY_PATH /go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib

but I got this error when I build the image
/vendor/github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: cannot find -ldb2
/usr/bin/ld: cannot find -ldb2
collect2: error: ld returned 1 exit status

Can you give me a solution to pass this error? Thanks

**Comment by akhilravuri1** [comment]
Hi,
Once you go to /go/src/github.com/ibmdb/go_ibm_db/installer directory and check for clidriver folder,
if you have clidriver then check for lib folder. This -ldb2 is an linking error that means it is not able to find the libdb2.so file in clidriver/lib folder.

**Comment by bimalkjha** [comment]
Closing the issue as there is no response from more than a month. Please update here with details if you are still facing the issue. Thanks.
