### ISSUE TITLE
Allows insert a string argument to CHAR () FOR BIT DATA column

### ISSUE THREAD

**Issue by xhit** [ibmdb/go_ibm_db#60]
**Is your feature request related to a problem? Please describe.**
DB2 allows to insert or update a column `CHAR () FOR BIT DATA` with a `string`. This package only allows insert with arguments to this data type column a `[]byte`. For projects with customizable input-output is a regression in performance to know if the string to pass to a DB is correct for the destination data type.

**Describe the solution you'd like**
Internally in the package when string is passed like argument to `CHAR () FOR BIT DATA` then convert to `[]byte`.

**Note**: Only this data type. `BINARY, VARBINARY, BLOB` doesn't need this.

**Note 2**: In the project I found how deal with this. If this request can be realized with regression in performance for other data types then this request cannot be proceed.

**Comment by akhilravuri1** [comment]
Hi @xhit 
can you provide a sample program on what you are trying to do?

Thanks,
Akhil

**Comment by xhit** [comment]
First create a table with a column with the data type affected:

```sql
 CREATE TABLE TESTSCHEMA."test"
             (
                          "charbitcol" CHAR(100) FOR BIT DATA
             ); 
```

And try to insert a string to this data type:

```go
       //Connect to db first.....

	var query = "insert into \"test\" (\"charbitcol\") values(?)"

	stmt, err := db.Prepare(query)
	if err != nil {
		panic(err)
	}

	var value string

	_, err = stmt.Exec(value)
	if err != nil {
		panic(err)
	}
```

For this works,  in `Exec`, `value` need to be a []byte `[]byte(value)`

But this data type in DB2 can admit a string too (char, varchar, etc...). View document: https://www.ibm.com/support/knowledgecenter/SSFMBX/com.ibm.swg.im.dashdb.sql.ref.doc/doc/r0000813.html

This datatype can accept a hexadecimal value, so []byte has sense, this issue is for admit a string too and is not a rule, is a suggestion only.

**Comment by xhit** [comment]
Not necessary.

clidriver treat this like SQL_C_BINARY and others type use this C type.
