### ISSUE TITLE
CLI Driver log level change

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#61]
Hi Team, 
We got one issue and the Go code returns error message,
```
2020/02/18 06:09:47 Serving dvapi at https://[::]:3300
time="2020-02-18T06:13:36Z" level=error msg="SQLDriverConnect: {HY507} [IBM][CLI Driver] CLI0157E  Error opening a file. SQLSTATE=HY507"
time="2020-02-18T06:13:36Z" level=error msg="SQLDriverConnect: {HY507} [IBM][CLI Driver] CLI0157E  Error opening a file. SQLSTATE=HY507"
time="2020-02-18T06:13:37Z" level=error msg="SQLDriverConnect: {HY507} [IBM][CLI Driver] CLI0157E  Error opening a file. SQLSTATE=HY507"
time="2020-02-18T06:13:43Z" level=error msg="SQLDriverConnect: {HY507} [IBM][CLI Driver] CLI0157E  Error opening a file. SQLSTATE=HY507"
time="2020-02-18T06:13:43Z" level=error msg="SQLDriverConnect: {HY507} [IBM][CLI Driver] CLI0157E  Error opening a file. SQLSTATE=HY507"

```
This is only occurred when the server startup. After a few minutes, it works well.
And it only happens in the test cluster(inside docker container), we could not re-produce in local dev env.
Is there any configuration to change the log level and print more log message?
Thanks.

**Comment by akhilravuri1** [comment]
Hi @maxatcn 
"Error opening a file" what file are you trying to open.
Is your connection string correct? as I see there is a problem at the SQLDriverConnect api.

To print more logs please take db2trace:-
```
db2trc on -f 1.trc 
<Run the test to repro issue>
db2trc off

db2trc fmt -c 1.trc 1.drda
db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
db2trc fmt -cli 1.trc 1.cli
```

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @maxatcn 

This error occurs if there is no much space in your directory to create that file.

This problem can be resolved by adding the following entry to the \sqllib\db2cli.ini file:
```
[COMMON]
TempDir=x:\your directory
```
where x:\your directory specifies an existing directory on a drive that has space available. DB2® writes temporary files to this directory. The amount of space that is required depends on the size of the directory entries you are adding or updating. Generally, more space is required than the size of the largest entry you are updating.

Thanks,
Akhil

**Comment by maxatcn** [comment]
Thanks @akhilravuri1 .
The issue only occurred in the first few minutes of the server startup.  
After several minutes, when re-trying the same workload, it works well. 

I will try if the db2trace can be ran inside the docker container. 
Thanks.

**Comment by akhilravuri1** [comment]
closing the issue as the user did not respond.
