### ISSUE TITLE
Error on running sql query when the security is set to Kerberos

### ISSUE THREAD

**Issue by IdaZ1234567** [ibmdb/go_ibm_db#62]
Hello, 

I am trying to run sql query using Kerberos, but there is always this error returned. I don't know what I did wrong:
```
Error when query for db: SQLDriverConnect: {     } [IBM][CLI Driver] SQL1365N  db2start or db2stop failed in processing the plugin " ". Reason code = "4".
```
My connection string:
```
HOSTNAME=<hostname>;DATABASE=<dbname>;PORT=50002;UID=<username>;PWD=<password>;AUTHENTICATION=KERBEROS;TargetPrincipal=db2inst3@FYRE.IBM.COM
```
I am actually a little confused about what I should put into the `TargetPrincipal`, but the same error will be returned even if I do not put the `TargetPrincipal` into the connection string. So I guess `TargetPrincipal` is not the main cause.

Because JDBC could successfully run the query,  I think the setting for Kerberos is correct.

Reference:
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0054601.html, https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0060553.html

I wonder what could be the problem?

Thanks!

**Comment by IdaZ1234567** [comment]
I have another question. Because the VM I want to test does not have golang installed, I build it in one linux machine with golang installed and run the binary file in the target machine. If,  for example I did go build in one linux machine which because of fire wall or some other reasons returns this error when did the go run command, would the target VM inherit this error?

**Comment by IdaZ1234567** [comment]
There is also a document saying that in order to use Kerberos, we also need to setup `db2cli.ini` in the cli driver: https://www.ibm.com/developerworks/data/library/techarticle/dm-1502kerberos-db2/index.html. But it actually does not help even if I change that file.

My changed `db2cli.ini` file:
```

; Comment lines start with a semi-colon.

[tstcli1x]
uid=userid
pwd=password
autocommit=0
TableType="'TABLE','VIEW','SYSTEM TABLE'"

[tstcli2x]
; Assuming dbalias2 is a database in DB2 for MVS.
SchemaList="'OWNER1','OWNER2',CURRENT SQLID"

[MyVeryLongDBALIASName]
dbalias=dbalias3
SysSchema=MYSCHEMA

[Common]
TargetPrincipal =db2inst3/<hostname>@FYRE.IBM.COM
trace=1
tracefilename=<anywhere I want to save the file>

```

**Comment by akhilravuri1** [comment]
Hi @IdaZ1234567 
If you want to use Kerberos authentication then you need to set up your server to accept Kerberos authentication.

TargetPrinciple parameter is a must if you are using a cli driver.

Thanks,
Akhil

**Comment by IdaZ1234567** [comment]
Hello @akhilravuri1, but where should I set the `TargetPrinciple`. Am I suppose to add it in the connection string or I need to get into the VM and change `db2cli.ini` file in cli driver folder just like what I showed above?

**Comment by IdaZ1234567** [comment]
I think the server is correctly set to Kerberos because it is able to make jdbc query using Kerberos. I am confused by the error message I posted in my comment 1. What could be the cause for this error?

**Comment by akhilravuri1** [comment]
Hi @IdaZ1234567 

can you please change the connection string to this format and give a try?

```
Authentication=KERBEROS;HOSTNAME=<hostname>;DATABASE=<dbname>;port=50000;UID=db2inst3@FYRE.IBM.COM;PWD=<password>;
```

Thanks,
Akhil

**Comment by IdaZ1234567** [comment]
Hello @akhilravuri1 , I tried the connection: `Authentication=KERBEROS;HOSTNAME=<hostname>;DATABASE=<dbname>;port=50000;UID=db2inst3@FYRE.IBM.COM;PWD=<password>;` 
The returned result is:
```
SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30082N  Security processing failed with reason "17" ("UNSUPPORTED FUNCTION").  SQLSTATE=08001
```

**Comment by akhilravuri1** [comment]
Hi @IdaZ1234567 

Is Kerberos setup done at server side?

If you are able to connect to that server with Authentication=kerberos using JDBC connection string can you please share that connection string?

Thanks,
Akhil

**Comment by IdaZ1234567** [comment]
This is the testing code they shared with me:
```
	public static void kerberosTest() {
		String URL = "jdbc:db2://<hostname>:50002/repokk:securityMechanism=11;" ;
		Class driverClass = null;
		Driver jdbcDriver = null;        
        try
        {
            driverClass = Class.forName("com.ibm.db2.jcc.DB2Driver");
            jdbcDriver = (Driver)driverClass.newInstance();
        }
        catch (Exception e)
        {   	
        	 System.out.println("Can not find DB2Driver");
        }
       Properties prop = new Properties() ; 	
       prop.setProperty("retrieveMessagesFromServerOnGetMessage","true");
       prop.setProperty("user","db2inst3");
       prop.setProperty("password",<password>);
       prop.setProperty("kerberosServerPrincipal","");
       Connection conn = null ;
       try{
    	    conn = jdbcDriver.connect(URL, prop);
    	    System.out.println("Success");
       }catch(Exception ex) {
    	   ex.printStackTrace();
    	   System.out.println("failed");
       }
	}
```

**Comment by akhilravuri1** [comment]
Hi @IdaZ1234567 

Are you able to connect to the server using JDBC?

If yes, please use the same server, db name, port number and try to connect using Go.

I have tried in my system I am able to connect to my Kerberos authenticated server using the same connection string.

Thanks,
Akhil

Th

**Comment by abhinandanramesh** [comment]
Hi @akhilravuri1  I'm a colleague of the above user at IBM. We are using the same connection string as we are using JDBC. Perhaps, oen question would be - if we step back and look at db2cli.ini file as posted above, is it valid or is it even necessary to have the same? 

Any suggestions would be appreciated. Thank you!

**Comment by abhinandanramesh** [comment]
We would really appreciate if you could give us a small brief template of the steps you took to connect to the server at your end.

**Comment by akhilravuri1** [comment]
Hi @abhinandanramesh 


For Kerberos connection from go driver no need to change anything in the db2cli.ini file.
you just need to change the connection string to this format
```
Authentication=KERBEROS;HOSTNAME=<hostname>;DATABASE=<dbname>;port=50000;UID=db2inst3@FYRE.IBM.COM;PWD=<password>;
```

Even now if you are getting the same error run ```db2level``` and give me the output.

Thanks,
Akhil

**Comment by IdaZ1234567** [comment]
Hello @akhilravuri1 , the error message it will return if I use the connection string you posted above is: 
```
SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30082N  Security processing failed with reason "17" ("UNSUPPORTED FUNCTION").  SQLSTATE=08001
```
Which I think is because port `50000` is not Kerberos. But we tend to use the port `50002` I guess for `db2inst3` as `db2inst3` belongs to `50002`. Is there any specific reason that you want me to test port `50000`?

**Comment by IdaZ1234567** [comment]
Hello @akhilravuri1 , the problem is fixed. It is caused by that I haven't add the target user principal into the kadmin.local principal list of the VM we run. Thank you so much for your help @akhilravuri1!

**Comment by pgr-rmeester** [comment]
Where does kadmin.local live on a Mac?
