### ISSUE TITLE
Please help to create one simple example of DB2 connect with SSL mode

### ISSUE THREAD

**Issue by ZacZelner** [ibmdb/go_ibm_db#65]
Hi,
I read the closed issue of SSL db2 connection.
I still have no idea about how to add the ssl command.
I have the .**jks** file in my local and how to import it.
I think we also need a ssl **password** (Since I use the ssl password to the db2 client)

Can you help me to add the ssl file and password to the example.go?

func main(){
    con:="HOSTNAME=hostname;DATABASE=DSS;PORT=90000;UID=username;PWD=password;SECURITY=SSL;"
 db, err:=sql.Open("go_ibm_db", con)
    if err != nil{
        
		fmt.Println(err)
	}
	db.Close()
}

**Comment by akhilravuri1** [comment]
Hi @ZacZelner
example constr with ssl security 
```
func main(){
con:="HOSTNAME=hostname;DATABASE=DSS;PORT=90000;UID=username;PWD=password;SECURITY=SSL;SSLCERTIFICATE=PATHofSSLCERTIFICATE"
db, err:=sql.Open("go_ibm_db", con)
if err != nil{

	fmt.Println(err)
}
db.Close()
```

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 
I used this:
con:="HOSTNAME=hostname;DATABASE=DSS;PORT=90000;UID=username;PWD=password;SECURITY=SSL;SSLCERTIFICATE=\"/Users/zac/ssl/jcekdb.jks\""

still got error:
SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001

I can use in this SSL setting in my db2 client.

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

I see you are passing .jks certificate which is used only for java.

For cli, you need to pass the .arm file. please check for .arm file in /Users/zac/ssl folder and pass that file path as an argument in the connection string.

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 ,

SECURITY=SSL;SSLCERTIFICATE=/Users/zac/ssl/odsdevkey.arm"

Got the same error:

SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 
sorry, my bad.
It's SSLSERVERCERTIFCATE, not SSLCERTIFICATE.

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 
Thanks！I have tried this before, and still got the issue.

I have 2 questions now:
1. Do I need to install the gskit tool on my local?
2. Is there a way we use JDBC instead of CLI to connect DB2 using Go?

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

1) gskit will be there is in clidriver so no need to install it.

2) No cannot connect with the JDBC driver.

Thanks,
Akhil

**Comment by jmoscato** [comment]
> Hi @ZacZelner
> sorry, my bad.
> It's SSLSERVERCERTIFCATE, not SSLCERTIFICATE.
> 
> Thanks,
> Akhil

Hi @akhilravuri1

Just to be sure, is the spelling in your correction right? It appears to be missing the last "I" letter. So is it "SSLSERVERCERTIFCATE" or "**SSLSERVERCERTIFICATE**"?

Thanks

**Comment by akhilravuri1** [comment]
Hi @jmoscato 
Sorry, It is "SSLSERVERCERTIFICATE".

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 ,

if I do not need to install gskit on my local,
I still got the error when I was using:

con:="HOSTNAME=hostname;DATABASE=DSS;PORT=90000;UID=username;PWD=password;SECURITY=SSL;SSLSERVERCERTIFICATE=/Users/zac/ssl/odsdevkey.arm"

error:
SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001

The .arm file is the one our DBA send to me, I have not create it. DBA said this is the .arm file for the database I wish connect

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

I think golang is unable to find your .arm file.

Please run this program and check whether go is able to print the data or not.
```
package main

import (  
    "fmt"
    "io/ioutil"
)

func main() {  
    data, err := ioutil.ReadFile("/Users/zac/ssl/odsdevkey.arm")
    if err != nil {
        fmt.Println("File reading error", err)
        return
    }
    fmt.Println("Contents of file:", string(data))
}
```

Give me your go version and go env

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 
Here is the result of the file:

ruihuaz-MacBook-Pro:~ zac$ go run condev1.go
Contents of file: -----BEGIN CERTIFICATE-----
MIIGCzCCBPOgAwIBAgIDAMNxMA0GCSqGSIb3DQEBCwUAMGoxCzAJBgNVBAYTAlVT
LGQBAxYZc3RldmVuX21hbG9uZXlAdXMuaWJtLmNvbTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBANBoGSsRHfoKD2XT3/VFtbkuV4t4YpVvoOgL56byhu0X
1LdjcswQkulwHexlMmOVMzAaOP7E3tDH+F9K6zl1LYxUImRAH6jkUDbWEajzyCC4
MPXaOLOuCuYLUttw5EUfdz1+Sv4Ychz537L5QM3A50chlHVZUD+5iFRYnCEPeMkI
PeVtMY732iVuiYRX9j0pk5twK9MjGBeBkQsNC6dSTLIwgMku6ir5/2Pki6VqK+3P
9FHEk5yem2OtVLH4rjKoRi0qlHuc17mUd1oD4QN+nuQfuQRYvEm45DhXZ49BKW88
1wWEpDbpVrQ+pVpL8tZjxKm4c6xNg4v36KGCMeOAWDcCAwEAAaOCAmIwggJeMCAG
A1UdEQQZMBeCFXRiaXJkLnJ0cC5kc3QuaWJtLmNvbTAOBgNVHQ8BAf8EBAMCBaAw
HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIHUBgNVHR8EgcwwgckwgYSg
gYGgf6R9MHsxCzAJBgNVBAYTAlVTMTQwMgYDVQQKEytJbnRlcm5hdGlvbmFsIEJ1
c2luZXNzIE1hY2hpbmVzIENvcnBvcmF0aW9uMSUwIwYDVQQDExxJQk0gSU5URVJO
QUwgSU5URVJNRURJQVRFIENBMQ8wDQYDVQQDEwZDUkwxMDEwQKA+oDyGOmh0dHA6
Ly9kYXltdnMxLnBvay5pYm0uY29tOjIwMDEvUEtJU2Vydi9jYWNlcnRzL0NSTDEw
MS5jcmwwHQYDVR0OBBYEFOddBKx6Pm5CXL/XRhO1N/ts+0CQMB8GA1UdIwQYMBaA
FAYv2seaHz+HUblN0PbarpdGSp3IMIHzBgNVHSAEgeswgegwgeUGBFUdIAAwgdww
dgYIKwYBBQUHAgEWamh0dHA6Ly93My0wMy5pYm0uY29tL3RyYW5zZm9ybS9zYXMv
YXMtd2ViLm5zZi9Db250ZW50RG9jc0J5VGl0bGUvSW5mb3JtYXRpb24rVGVjaG5v
bG9neStTZWN1cml0eStTdGFuZGFyZHMwYgYIKwYBBQUHAgIwVgxUVXNlIG9mIHRo
aXMgY2VydGlmaWNhdGUgc2hvdWxkIGFkaGVyZSB0byBJQk0gY29ycG9yYXRlIHN0
YW5kYXJkcyBJVENTMTA0IGFuZCBJVENTMzAwMA0GCSqGSIb3DQEBCwUAA4IBAQAg
WhFWRiIUYVFVeX/D9ox/CKWCSm0ugXh1fh8Q6oSYCFdzNUM+OqWkH8YTZ18/AD+f
uMiUJvxA5LKqUqeLM2pEv7G5+uVOlo/4Ww3WTOZ59sGAkAdgAb37DCgxXrYFvn+h
ktMXg1hOoKf+JBpR1ge9wVujsDAoYOItZuiSWinF1wXcq/q1DkDfbczNeReRmimq
-----END CERTIFICATE-----

I think it can read the file.

The go version and env:
$ go version
go version go1.13.4 darwin/amd64

ruihuaz-MacBook-Pro:~ zac$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/zac/Library/Caches/go-build"
GOENV="/Users/zac/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zac/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/Users/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/Users/zac/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hx/0bd3dc5j2f95jy7lxjf51w5


Thank you!

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 


> con:="HOSTNAME=hostname;DATABASE=DSS;PORT=90000;UID=username;PWD=password;SECURITY=SSL;SSLSERVERCERTIFICATE=/Users/zac/ssl/odsdevkey.arm"

If your .arm is right then the port which you are passing is SSL port or normal port. Please check with your DBA on which port he has activated SSL.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 
Have you checked whether SSL activated port and the port which you are using is the same or not?

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 ,

I have double checked the port I wrote in the go file. It's correct. 
I can connect the database using this port in other db2 clients.

Thanks!

**Comment by akhilravuri1** [comment]
Hi @ZacZelner 

I will set up a new SSL security in my VM and I will update you.

Thanks,
Akhil

**Comment by ZacZelner** [comment]
Hi @akhilravuri1 , any update?

**Comment by rahul-s-s** [comment]
Hi Akhil @akhilravuri1  / @ZacZelner 

Could please tell if this issue is resolved and what configuration is required to use SSL connection?

Regards,
Rahul

**Comment by ZacZelner** [comment]
Not yet, have no more update yet

**Comment by akhilravuri1** [comment]
Hi @rahul-s-s 
Is the SSL setup done in your device?

If Yes please check which port is allocated for SSL?

Please change the port no to SSL port no and add SSL certificate number.

```
con:="HOSTNAME=hostname;DATABASE=DSS;PORT=sslportnumber;UID=username;PWD=password;SECURITY=SSL;SSLSERVERCERTIFICATE=/Users/zac/ssl/odsdevkey.arm"
```

Thanks,
Akhil

**Comment by rahul-s-s** [comment]
Hi Akhil @akhilravuri1 

I tried using DashDB and got connected successfully.
For the DashDB and SQLDB products from v11 onwards, the DigiCert Global Root CA Certificate, DigiCertGlobalRootCA.arm, is used for SSL connections. 

CA cert is under  `~/sqllib/cfg` folder

Since DashDB using Public CA `SSLSERVERCERTIFICATE` parameter is not required.

```
con:="HOSTNAME=hostname;DATABASE=DSS;PORT=sslportnumber;UID=username;PWD=password;SECURITY=SSL;"
```

FYI @ZacZelner

**Comment by akhilravuri1** [comment]
Closing as the user did not respond.
