### ISSUE TITLE
Unable to timeout during query when all connections in the pool are in used

### ISSUE THREAD

**Issue by sedouard05** [ibmdb/go_ibm_db#66]
I created a database with maximum connection to 10, maximum idle connection to 5, and connection lifetime to 5 minutes. We have a situation where the maximum connection is reached and a query is executed. Is there a way to timeout the query execution when there is no more available connection?

- os Version: RHE Linux Server release 7.7 (Maipo)
- cli-driver Version: DB2 v11.1.4.4
- Db2 Server Version: Db2 V11.5.2.0
- go Version: go1.12.6 linux/amd64
<details> <summary> <code> go env</code>Output: </summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build158068241=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by akhilravuri1** [comment]
Hi @sedouard05 
please check this issue #46 

Thanks,
Akhil

**Comment by sedouard05** [comment]
Hi @akhilravuri1,
I saw issue #46 and tried the solution. It did not work in my case. I think the issue is in the connection pool.  Could the connection pool time out the request if it is unable to get a connection within the time frame?

Here is my workaround:
`
db, _ := sql.Open("go_ibm_db", conString)
db.SetConnMaxLifetime(30 * time.Minute)
db.SetMaxIdleConns(5)
db.SetMaxOpenConns(10)

ctx, cancel := context.WithCancel(context.Background())
go func() {
	time.Sleep(60 * time.Second)
	cancel()
}()

rows, _ := db.QueryContext(ctx, "SELECT * FROM TEST_TABLE WHERE USER=?", strings.ToUpper(*dbUser))
`

**Comment by akhilravuri1** [comment]
Hi @sedouard05 
No, connection pool does not time out the request if it is unable to get a connection within the time frame.

Thanks,
Akhil

**Comment by sedouard05** [comment]
Hi @akhilravuri1,

Could this be added to the connection pool?

Thank you,

Sother

**Comment by akhilravuri1** [comment]
Hi @sedouard05 

We have seen that go database package has internal pooling so can you please give a try with normal connection?

With normal connection itself go will set all the required connection pooling requirements.

If you are facing this issue after that also we will take your request.


Thanks,
Akhil

**Comment by akhilravuri1** [comment]
closing as the user did not respond.
Thanks,
Akhil
