### ISSUE TITLE
Stored procedure becomes locked with failed rows.Next() call

### ISSUE THREAD

**Issue by acoady** [ibmdb/go_ibm_db#67]
I have created a user defined function that is called from a stored procedure. If the python file referenced in the function is not present at the correct location an error is triggered when the function is executed via the stored procedure. This error is encountered when using the `rows.Next()` call. The next call returns false on the first iteration and using `rows.Err()` gives this error.

 _SQLFetch: {     } [IBM][CLI Driver][DB2/LINUXX8664] SQL1646N  A routine failed because the fenced user ID cannot access required files in the sqllib directory or other instance or database directories._

Digging in further in sql.go (~ line 2989) close function when `err = rs.rowsi.Close()` is called err becomes:
SQLCloseCursor: {24000} [IBM][CLI Driver] CLI0115E  Invalid cursor state. SQLSTATE=24000

This comes from odbcstmt.go (~ line 75) closeByRows function when
 `ret := api.SQLCloseCursor(s.h)` is called. At this point the stored procedure is locked and cannot be deleted using another connection or external method/application. 

This can be worked around by using the initial connection and performing another operation, e.g. a dummy query, which will unlock the stored procedure. Although this is not ideal in a server environment.

I have created a sample application that displays this behaviour, I will append in the next comment.

Here are my environment details. I have encountered this on other platforms as well.
os Version: OSx Mojave 10.14.6
cli-driver Version: DB2 v11.1.4.4
Db2 Server Version: Db2 V11.5.2.0
go Version: go1.12.6 darwin/amd64
<details>
    <summary>go envOutput:</summary>

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/acoady/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/acoady/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/Users/acoady/go/src/db2rest/scripts/../../../pkg/dep/sources/https---github.com-ibmdb-go_ibm_db/installer/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/Users/acoady/go/src/db2rest/scripts/../../../pkg/dep/sources/https---github.com-ibmdb-go_ibm_db/installer/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ld/0ttffk414cz0hl8gc4n4xxt40000gn/T/go-build919222473=/tmp/go-build -gno-record-gcc-switches -fno-common"
</details>

**Comment by acoady** [comment]
Here is my example:

```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	//Update this with your hostname, database name, username and password
	conString := "HOSTNAME=myHostname.com;DATABASE=myDBName;PORT=50001;UID=myDBUser;PWD=myDBpassword;SECURITY=SSL"

	//You can update these constants if necessary
	schemaName := "TEST"
	tableName := "TEST1"
	functionName := "SCALAR_FUNCTION_ERROR"
	procedureName := "PROC1"

	dbConn1, err := sql.Open("go_ibm_db", conString)
	if err != nil {
		fmt.Println("Error opening connection", err.Error())
	}
	defer dbConn1.Close()

	createTableSQL := fmt.Sprintf("CREATE TABLE %s.%s (COL1 int, COL2 int);INSERT INTO %s.%s VALUES (10, 20);COMMIT;", schemaName, tableName, schemaName, tableName)
	_, err = dbConn1.Exec(createTableSQL)
	if err != nil {
		fmt.Println("Error creating table.", err.Error())
	}

	//Create the python function
	createFunctionSQL := fmt.Sprintf("CREATE FUNCTION %s.%s (integer, integer) RETURNS integer LANGUAGE PYTHON PARAMETER STYLE NPSGENERIC FENCED NOT THREADSAFE NO FINAL CALL ALLOW PARALLEL NO DBINFO DETERMINISTIC NO EXTERNAL ACTION RETURNS NULL ON NULL INPUT NO SQL EXTERNAL NAME '/tmp/somefile.py'", schemaName, functionName)
	_, err = dbConn1.Exec(createFunctionSQL)
	if err != nil {
		fmt.Println("Error creating function.", err.Error())
	}

	createProcedureSQL := fmt.Sprintf("CREATE PROCEDURE %s.%s ()\nLANGUAGE SQL\nSPECIFIC %s.%s\nDYNAMIC RESULT SETS 1\nBEGIN\nDECLARE C1 CURSOR WITH RETURN FOR \n-- BEGIN SQL STATEMENT\nSELECT %s.%s(COL1, COL2) FROM %s.%s;\n-- END SQL STATEMENT\nOPEN C1;\nEND\n", schemaName, procedureName, schemaName, procedureName, schemaName, functionName, schemaName, tableName)
	_, err = dbConn1.Exec(createProcedureSQL)
	if err != nil {
		fmt.Println("Error creating procedure.", err.Error())
	}

	// Testing hang on deleting a table after a failure with python function
	callProcedureSQL := fmt.Sprintf("CALL %s.%s", schemaName, procedureName)
	rows, err := dbConn1.Query(callProcedureSQL)
	if err != nil {
		fmt.Println("Error running procedure.", err)
	}
	defer rows.Close()
	if rows.Next() {
		fmt.Println("In the rows.next block.")
	}

	if err := rows.Err(); err != nil {
		rows.Close()
		fmt.Println("In the rows.Err block.\n", err)
	}

	//Open a second connection to show first connection is locked
	dbConn2, err := sql.Open("go_ibm_db", conString)
	if err != nil {
		fmt.Println("Error opening connection", err.Error())
	}
	defer dbConn2.Close()

	fmt.Println("Attempt to drop procedure with connection 2 - This will timeout, please be patient")
	dropProcedureSQL := fmt.Sprintf("DROP SPECIFIC PROCEDURE %s.%s", schemaName, procedureName)
	_, err = dbConn2.Exec(dropProcedureSQL)
	if err != nil {
		fmt.Println("Error in deleteing procedure.", err.Error())
	}

	//Running a query on connection 1 will release and allow the locked command on connection 2 to proceed
	r2, err2 := dbConn1.Query("SELECT * FROM SYSIBM.SYSDUMMY1")
	if err2 != nil {
		fmt.Println("Error during query.\n", err)
	}
	r2.Close()

	fmt.Println("Attempt to drop procedure with connection 2 - This will succeed")
	_, err = dbConn2.Exec(dropProcedureSQL)
	if err != nil {
		fmt.Println("Error in deleting procedure.", err.Error())
	}

}

```

**Comment by akhilravuri1** [comment]
Hi @acoady 
could you please send us a screenshot of the error you are facing?

Thanks,
Akhil

**Comment by acoady** [comment]
The 'error' is. that the procedure is locked even though it is no longer in use. If you attempt to drop the procedure using an external program or another connection it will timeout.

The only way to 'unlock' this procedure is to use the connection that encountered the lock to perform another operation or stop the server holding this connection.

Using my example program you can see:

_Error in deleting procedure. SQLExecute: {40001} [IBM][CLI Driver][DB2/LINUXX8664] SQL0911N  The current transaction has been rolled back because of a deadlock or timeout.  Reason code "68".  SQLSTATE=40001_

Here is a screencap. My script begins outputting go env, encounters a recoverable message that the function has already been created, encounters the expected error that python file is not accessible, and then encounters the timeout attempting to delete the procedure. 
![image](https://user-images.githubusercontent.com/62344203/77337105-d472ae80-6cfe-11ea-9894-80f813b15c78.png)

**Comment by akhilravuri1** [comment]
Hi @acoady 
Are you still facing this issue?

Thanks,
Akhil

**Comment by acoady** [comment]
I have not tried it again recently, have there been any changes in this area? @akhilravuri1

**Comment by akhilravuri1** [comment]
No there are no changes in this area but when I tested it on windows It is working fine.
I will try to reproduce it on mac.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @acoady 

when I run the program I get the following error:-
```
Error creating function. SQLExecute: {42601} [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "PYTHON" was found following "LANGUAGE".  Expected tokens may include:  "C".  LINE NUMBER=1.  SQLSTATE=42601

Error creating procedure. SQLExecute: {42884} [IBM][CLI Driver][DB2/LINUXX8664] SQL0440N  No authorized routine named "SCALAR_FUNCTION_ERROR" of type "FUNCTION" having compatible arguments was found.  LINE NUMBER=6.  SQLSTATE=42884

Error running procedure. SQLExecute: {42884} [IBM][CLI Driver][DB2/LINUXX8664] SQL0440N  No authorized routine named "TEST.PROC1" of type "PROCEDURE" having compatible arguments was found.  SQLSTATE=42884
```

Can you please provide a working sample on mac?

Thanks
Akhil

**Comment by acoady** [comment]
I believe the errors you have encountered are because the version of Db2 you are running does not support python user defined functions. You may need 11.5

**Comment by akhilravuri1** [comment]
Okay.. I will run the tests against 11.5

**Comment by akhilravuri1** [comment]
Please reopen if you are facing this issue with the latest driver.

Thanks,
Akhil
