### ISSUE TITLE
Build issue on ppc64le system

### ISSUE THREAD

**Issue by toroc** [ibmdb/go_ibm_db#68]
I'm trying to build a docker image that contains this go library for a CP4D micro-service. I'm specifying the ppc64le downloaded driver but the build fails due to missing dependencies:

- os Version: 3.10.0-1062.1.2.el7.ppc64le
- cli-driver Version: ppc64le_odbc_cli.tar.gz  downloaded from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/
- Db2 Server Version:
- go Version: 1.12.4
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
before running go env
GOARCH="ppc64le"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/goroot"
GOTMPDIR=""
GOTOOLDIR="/goroot/pkg/tool/linux_ppc64le"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/root/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/root/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build456840787=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

Logs from within the docker image
```logs
$ env CGO_ENABLED=1 GOOS=linux GOARCH=ppc64le go build -ldflags='-w -s'
# uc-go-api/vendor/github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: warning: libnuma.so.1, needed by /root/clidriver/lib/libdb2.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libibmc++.so.1, needed by /root/clidriver/lib/libdb2.so, not found (try using -rpath or -rpath-link)
/root/clidriver/lib/libdb2.so: undefined reference to `numa_interleave_memory@libnuma_1.2'
/root/clidriver/lib/libdb2.so: undefined reference to `numa_all_nodes_ptr@libnuma_1.2'
/root/clidriver/lib/libdb2.so: undefined reference to `__IBMCPlusPlusExceptionV3'
/root/clidriver/lib/libdb2.so: undefined reference to `numa_available@libnuma_1.1'
collect2: error: ld returned 1 exit status
```

Logs from a ppc64le VM:
```logs
env CGO_ENABLED=1 GOOS=linux GOARCH=ppc64le go build -ldflags='-w -s'
# uc-go-api/vendor/github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: skipping incompatible /root/carol-dev/clidriver/lib/libdb2.so when searching for -ldb2
/usr/bin/ld: cannot find -ldb2
/usr/bin/ld: skipping incompatible /root/carol-dev/clidriver/lib/libdb2.so when searching for -ldb2
/usr/bin/ld: cannot find -ldb2
collect2: error: ld returned 1 exit status
```

The go build command above works without any issues on MacOS and amd64.

**Comment by akhilravuri1** [comment]
Hi @toroc 

Are you still facing this issue?

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @toroc 
You need to add clidriver/lib to the library path variable.

Thanks,
Akhil
