### ISSUE TITLE
A note about licensing from the client

### ISSUE THREAD

**Issue by bombsimon** [ibmdb/go_ibm_db#78]
**Is your feature request related to a problem? Please describe.**
Lack of documentation.

**Describe the solution you'd like**
If you look at the [Python README](https://github.com/ibmdb/python-ibmdb#Licenserequirements) theres a section about License Requirements for the driver. This seems to be applicable for all these drivers under the `ibmdb` organisation but it's not mentioned in this project.

I would like this project/driver/repository to mention relevant information about
* Whether or not a license is required (if so, when)
* How one would obtain such a license
* How one would use this library after obtaining a license (I guess a `.lic` file)

**Describe alternatives you've considered**
Alternatives would be to just link to other project documentations but it seems more reasonable to have it in this project. This might be something that's obvious for a lot of developers but for me as someone who's really new to the IBM and DB2 world, this is totally new for me.

**Additional context**
n/a

**Comment by akhilravuri1** [comment]
Hi @bombsimon 
we will update our readme with license information.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @bombsimon 
Update the readme with license information.

Thanks,
Akhil

**Comment by bombsimon** [comment]
Thank you very much!
