### ISSUE TITLE
Not able to push in bluemix cloud.

### ISSUE THREAD

**Issue by ayanDas-isi** [ibmdb/go_ibm_db#79]
I was trying to push the code in bluemix inside go gin  cloud foundry app. But is is throwing issue in installing db2-cli . It is showing the error that 
2020-04-25T14:54:51.39+0000 [STG/0] ERR /home/vcap/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api_unix.go:12:11: fatal error: sqlcli1.h: No such file or directory
I understand I need to install db2 driver but how will I install db2 driver in ibm cloud environment?
Kindly help me in solving the issue. 
![db2error](https://user-images.githubusercontent.com/19358021/80309714-5f5e3180-87f4-11ea-9187-f8ffe0399e5b.png)

**Comment by akhilravuri1** [comment]
Hi @ayanDas-isi 

Go to /home/vcap/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/installer and run the setup.go file.
```
go run setup.go
```
Now set the below env's:-
```
export DB2HOME=/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
Linux:
export LD_LIBRARY_PATH=/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
Mac:
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/home/uname/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
```

**Comment by akhilravuri1** [comment]
closing the issue as the user did not respond
