### ISSUE TITLE
Issue running on Mac

### ISSUE THREAD

**Issue by cfonze** [ibmdb/go_ibm_db#8]
I'm having the following issue running on the Mac.  Any ideas?

panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/ibmdb/go_ibm_db/api.SQLBindCol.func1(0x4000100010001, 0xc00009c1b8, 0xc000000004, 0xc00009c198, 0x40ecc80)
	/Users/fonseca/Development/gocode/src/github.com/ibmdb/go_ibm_db/api/zapi_unix.go:26 +0x4c
github.com/ibmdb/go_ibm_db/api.SQLBindCol(0x4000100010001, 0xc00009c1b8, 0x4, 0xc00009c198, 0x0)
	/Users/fonseca/Development/gocode/src/github.com/ibmdb/go_ibm_db/api/zapi_unix.go:26 +0x59
github.com/ibmdb/go_ibm_db.(*BufferLen).Bind(0xc00009c198, 0x10001, 0x0, 0x4030004, 0xc00009c1b8, 0x4, 0x8, 0xc0000902a0)
	/Users/fonseca/Development/gocode/src/github.com/ibmdb/go_ibm_db/column.go:29 +0x62
github.com/ibmdb/go_ibm_db.(*BindableColumn).Bind(0xc00009c180, 0x10001, 0x0, 0xc00009c180, 0x0, 0x0)
	/Users/fonseca/Development/gocode/src/github.com/ibmdb/go_ibm_db/column.go:202 +0x6c
github.com/ibmdb/go_ibm_db.(*ODBCStmt).BindColumns(0xc0000c2000, 0x41d8650, 0x0)
	/Users/fonseca/Development/gocode/src/github.com/ibmdb/go_ibm_db/odbcstmt.go:148 +0x1eb
github.com/ibmdb/go_ibm_db.(*Stmt).Query(0xc000094270, 0x41d8650, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/fonseca/Development/gocode/src/github.com/ibmdb/go_ibm_db/stmt.go:93 +0xe5
database/sql.ctxDriverStmtQuery(0x4111840, 0xc00009a008, 0x4111940, 0xc000094270, 0x41d8650, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.11.5/libexec/src/database/sql/ctxutil.go:94 +0x16b
database/sql.rowsiFromStatement(0x4111840, 0xc00009a008, 0x4111700, 0xc000090270, 0xc00009c140, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.11.5/libexec/src/database/sql/sql.go:2511 +0x159
database/sql.(*Stmt).QueryContext(0xc0000c4000, 0x4111840, 0xc00009a008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.11.5/libexec/src/database/sql/sql.go:2463 +0x203
database/sql.(*Stmt).Query(0xc0000c4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.11.5/libexec/src/database/sql/sql.go:2501 +0x65
main.main()
	/Users/fonseca/Development/gocode/src/github.ibm.com/IROC/db2_go/main.go:24 +0x183

**Comment by akhilravuri1** [comment]
Hi cfonze
can you run go version and go env on your system and place the output.

**Comment by akhilravuri1** [comment]
@cfonze I have merged the fix into the master branch. Can you pull the latest code and verify the fix.

**Comment by cfonze** [comment]
Pull the latest and it works.  Thank you the quick turn around.

**Comment by akhilravuri1** [comment]
Thanks
Closing the issue as it is solved
