### ISSUE TITLE
/usr/bin/ld: cannot found -ldb2

### ISSUE THREAD

**Issue by awol2010ex** [ibmdb/go_ibm_db#85]
package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"os/signal"

	"github.com/gin-gonic/gin"
	"github.com/gohouse/gorose/v2"
	_ "github.com/ibmdb/go_ibm_db"
)

var err error
var engin *gorose.Engin

func init() {
	engin, err = gorose.Open(&gorose.Config{Driver: "go_ibm_db", Dsn: "HOSTNAME="+os.Getenv("HOSTNAME")+";DATABASE="+os.Getenv("DATABASE")+";PORT="+os.Getenv("PORT")+";UID="+os.Getenv("UID")+";PWD="+os.Getenv("PWD")})"root:root@tcp(localhost:3306)/test?charset=utf8&parseTime=true"})
}
func DB() gorose.IOrm {
	return engin.NewOrm()
}
func main() {
	var err error

	if err != nil {
		log.Println(err.Error())
	}
	r := gin.Default()
	gin.SetMode(gin.ReleaseMode)
	f, _ := os.Create("gin.log")
	gin.DefaultWriter = io.MultiWriter(f)

	r.GET("/staff/list", func(c *gin.Context) {
		list, err1 := DB().Query("select * from baozhang.wf_staff where staffid='ADMIN'")
		if err1 != nil {
			fmt.Println(err1)
		}
		c.JSON(200, gin.H{
			"message":   "success",
			"staffList": list,
		})

	})

	go func() {
		_ = r.Run(":9033")
	}()

	quit := make(chan os.Signal)
	signal.Notify(quit, os.Interrupt)
	<-quit
}

yum install -y gcc git tar pam gcc-c++ kernel-devel make libxml2 glibc-static glibc-devel
export GO111MODULE="on"
export GOPROXY="https://mirrors.aliyun.com/goproxy/"
export GOFLAGS=""
export CGO_ENABLED=1
export CGO_CFLAGS=-I/opt/clidriver/include
export DB2HOME=/opt/clidriver
export CGO_CPPFLAGS=""
export CGO_CXXFLAGS="-g -O2"
export CGO_FFLAGS="-g -O2"
export CGO_LDFLAGS="-Xlinker -rpath=/opt/clidriver/lib/  -static -L/opt/clidriver/lib/"
export PKG_CONFIG="pkg-config"
export GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build360717037=/tmp/go-build -gno-record-gcc-switches"
export LD_LIBRARY_PATH=/usr/lib64/:/opt/clidriver/lib/
export PATH=$PATH:/opt/clidriver/bin:/opt/clidriver/lib/
GOOS=linux GOARCH=amd64  go build --ldflags "-linkmode external -extldflags -static" -a -installsuffix cgo -tags netgo -o gin_db2_docker_demo .

build error
# github.com/ibmdb/go_ibm_db/api
/usr/bin/ld: cannot found -ldb2
/usr/bin/ld: cannot found -ldb2
collect2: Error：ld return 1

**Comment by akhilravuri1** [comment]
Hi @awol2010ex 
can you share the docker file?

Thanks,
Akhil

**Comment by awol2010ex** [comment]
It's just  run at bash ,not  in docker

**Comment by awol2010ex** [comment]
cenos 7.3

**Comment by akhilravuri1** [comment]
May I know why are you using "github.com/gohouse/gorose/v2" instead of "database/sql"

-Akhil

**Comment by awol2010ex** [comment]
It's ok on Windows .gorose is a orm framkwork ,so I didn't use "database/sql"

**Comment by akhilravuri1** [comment]
I will try to reproduce the issue on centos 7.3

Thanks,
Akhil

**Comment by bimalkjha** [comment]
@awol2010ex Are you still facing this issue by using the latest code of go ibm_db driver?
