### ISSUE TITLE
Can we use APIKey to connect to db?

### ISSUE THREAD

**Issue by xzy202** [ibmdb/go_ibm_db#86]
Hi , wondering can we connect to DB using API key instead of using username, password? Do we have an example of how the connection string should look like?

HOSTNAME="";DATABASE="";PORT="";AUTHENTICATION=GSSPLUGIN;APIKEY=""

**Comment by akhilravuri1** [comment]
Hi @xzy202 

Any connection parameter which works with CLI will work with GoDriver also.

Please check whether your clidriver can take APIKEY and establish the connection.

Thanks,
Akhil
