### ISSUE TITLE
*sql.DB.Query() doesn't catch some error

### ISSUE THREAD

**Issue by xnxuen** [ibmdb/go_ibm_db#87]
When we run statement `SELECT * FROM "QPLEX"."GAIANDB"."TEST" FETCH FIRST 20 ROW ONLY` directly, we'll encounter an error like the following
![image](https://user-images.githubusercontent.com/52769722/82528859-4be08500-9b6c-11ea-8b6a-edcfb70f1f88.png)
But with `db.Query(SELECT * FROM "QPLEX"."GAIANDB"."TEST" FETCH FIRST 20 ROW ONLY)`, it'll return with no error caught.

**Comment by akhilravuri1** [comment]
Hi @xnxuen 
can you provide a sample program?
which go version are you using, platform and clidriver version?

Thanks.
Akhil

**Comment by xnxuen** [comment]
go1.12.7
Openshift x86 Linux container
IBM Data Server Driver for ODBC and CLI v11.1.4.4

Thanks.

**Comment by akhilravuri1** [comment]
Hi @xnxuen 



> db.Query(SELECT * FROM "QPLEX"."GAIANDB"."TEST" FETCH FIRST 20 ROW ONLY)

Can you explain "QPLEX"."GAIANDB"."TEST"?

Because normally it should be schema.tablename

Thanks,
Akhil

**Comment by xnxuen** [comment]
It‘s the form of Db2 Federation, i.e. `default database`, `default schema`, `table name`

**Comment by akhilravuri1** [comment]
> can you provide a sample program?

Can you please provide a sample program?
Because I tried in Linux and I don't find any problem..If there is an error it returns the error.
If your sample program produces the error can you run the same sample program in your local machine(not on open shift container).

Thanks,
Akhil

**Comment by xnxuen** [comment]
Hi @akhilravuri1 Is there any way to get for example Db2 trace in your side?
