### ISSUE TITLE
Deal with HADR Failover error

### ISSUE THREAD

**Issue by mschneider82** [ibmdb/go_ibm_db#88]
The JDBC driver has failover handling `clientRerouteAlternateServerName` if an HADR error was given. 

A simular feature would be nice, where the the connection will be switched to an alternative host/port

```
Diag.NativeError = -1776
Diag.Message = "[IBM][CLI Driver] SQL1776N  The command cannot be issued on an HADR database. Reason code = \"1\".\n"
```

**Comment by akhilravuri1** [comment]
If you add the alternative server names in the db2dsdriver.cfg file you can use it.

please check this documentation and example
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/c0056272.html

Thanks,
Akhil
