### ISSUE TITLE
dyld: Library not loaded: libdb2.dylib on Mac

### ISSUE THREAD

**Issue by malhamid** [ibmdb/go_ibm_db#89]
I am having issues installing the DB2 driver for go. It keeps giving me an error message image not found. My env variables are provided below. 

- os Version: macOS Catalina 10.15.5 
- cli-driver Version: 0.20. and 0.3.0
- Db2 Server Version:
- go Version: 1.12.17
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
CGO_ENABLED="1"

</pre></details>

Steps to Reproduce:

1. This is how my env variables are set: 
```
export DB2HOME=/Users/<userid>/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/installer/clidriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Users/<userid>/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/installer/clidriver/lib
```
Please note that version 0.3.0 is also giving the same issue. 

This is the error message when trying to load the library
```
dyld: Library not loaded: libdb2.dylib
  Referenced from: /var/folders/mg/214phpcn0fgdtlwlhqrqltxm0000gn/T/go-build605409485/b001/exe/example1
  Reason: image not found
signal: abort trap
```

**Comment by Addzero** [comment]
I also found this error once running with GO version 1.13.11 or 1.14.x but after downgrade the version of GO to v1.13.4 the error was gone.

**Comment by solami** [comment]
I also found the same error on v0.2.0, go v1.12.9, and macOS 10.15.3, and it worked fine when I turned off the SIP.

**Comment by akhilravuri1** [comment]
Hi @malhamid 

there is some problem with our cli driver on mac os Catalina.

Our clidriver team is working on it once it is done we will let you know.

Thanks,
Akhil

**Comment by malhamid** [comment]
Sure, thanks @akhilravuri1 for the update.

**Comment by akhilravuri1** [comment]
Hi @malhamid 

Please install the driver run setup.go command as stated in the readme.
This will download the latest driver and use this driver. 

Thanks,
Akhil
