### ISSUE TITLE
Go SQL methods with context

### ISSUE THREAD

**Issue by asifjalil** [ibmdb/go_ibm_db#90]
Do you plan to implement methods such as PrepareContext, QueryContext, ExecContext, etc.?

Thanks.

**Comment by akhilravuri1** [comment]
Hi @asifjalil 
As of now, we don't have any plans to support that.

Thanks,
Akhil

**Comment by asifjalil** [comment]
Hi @akhilravuri1 

Thanks for replying. I also implemented a Go Db2 driver. In that driver, I implemented _ExecContext_ and _QueryContext_ where I run _SQLExecute_ in a goroutine and the main goroutine uses _SQLCancel_ to cancel _SQLExecute_ if the context timed out or cancelled: 

[asifjalil/cli/stmt.go#L212](https://github.com/asifjalil/cli/blob/master/stmt.go#L212)

For _PrepareContext_, I call _SQLPrepare_ just like in _Prepare_, but then I check if the context has been cancelled. If the context is cancelled, then _PrepareContext_ releases the statement handle and returns context error: 

[asifjalil/cli/conn.go#L143](https://github.com/asifjalil/cli/blob/master/conn.go#L143)

By the way, like you, my code is also based off of Alex Brainman's ODBC driver so our codes are similar.  If you are interested in implementing _PrepareContext_, _QueryContext_, and _ExecContext_, then I can create a pull request.

It is great to see IBM providing a Go Db2 driver.

Thanks.

**Comment by akhilravuri1** [comment]
Hi @asifjalil 
sorry for the late reply.



> By the way, like you, my code is also based off of Alex Brainman's ODBC driver so our codes are similar. If you are interested in implementing _PrepareContext_, _QueryContext_, and _ExecContext_, then I can create a pull request.

Yes, our code is also based on Alex Brainman's ODBC driver.

As of now, context support is not in our timeline. If any customer requests us for this support we will support it.

Please create a pull request we will look into it and run some test cases. We will keep it as verified and once any customer asks for the request we will merge it.

Thanks,
Akhil

**Comment by devanshah2** [comment]
@asifjalil No worries. Is the code mentioned at https://github.com/ibmdb/go_ibm_db/issues/90#issuecomment-642648126 the latest. If this was pulled into the go_ibm_db would it work?

Maybe @akhilravuri1 can help get it pulled in.

**Comment by akhilravuri1** [comment]
Hi @devanshah2 

As of now, the sql methods with context is not in our timeline. But, since you are looking for this capability we can add this.
Before adding we need to take look at this code and run the test cases like

If the driver implements context methods the sql.DB looks to use openConnector method and Connectors' conn method instead of sql.Open()

Thanks,
Akhil

**Comment by vmathur12** [comment]
Sorry for the delay. 
Merged the pull request.
Thanks

**Comment by vmathur12** [comment]
https://github.com/ibmdb/go_ibm_db/pull/176 
This commit has merged the fix.
Thanks
