### ISSUE TITLE
Wrong number of parameters in Query call

### ISSUE THREAD

**Issue by axelniedenhoff** [ibmdb/go_ibm_db#91]
When calling sql.DB.Query() with more than one argument (i.e. with arguments for placeholders), I get the following error message from Db2:
`SQLExecDirectW: {07001} [IBM][CLI Driver] CLI0100E  Wrong number of parameters. SQLSTATE=07001`

Sample program:
```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/ibmdb/go_ibm_db"
)

func main() {
	db, err := sql.Open("go_ibm_db", "DSN=TESTDB")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer db.Close()
	//The following works (no error):
	rows, err := db.Query("SELECT EMPNO FROM BLAH.EMP WHERE NAME='Smith'")
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(rows)
	//This will not work (CLI0100E error):
	rows, err = db.Query("SELECT EMPNO FROM BLAH.EMP WHERE NAME=?", "Smith")
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(rows)
}
```

go env:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/axel/.cache/go-build"
GOENV="/home/axel/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/axel/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build427371206=/tmp/go-build -gno-record-gcc-switches"
```

db2level:
`DB21085I  This instance or install (instance name, where applicable: "*") uses 
"64" bits and DB2 code release "SQL11014" with level identifier "0205010F".
Informational tokens are "DB2 v11.1.4.5", "special_39510", 
"DYN1911120100AMD64_39510", and Fix Pack "5".
Product is installed at 
"/home/axel/go/src/github.com/ibmdb/go_ibm_db/installer/clidriver".`

**Comment by akhilravuri1** [comment]
Hi @axelniedenhoff 

we have updated the db.Query() function.

Now db.Query() uses DirectExecute API(CLI function) . We do not support parameter markers in this function.

If you want to use parameter marker's you have to use db.Prepare() and st.Query() functions.


Thanks,
Akhil

**Comment by axelniedenhoff** [comment]
I see. That is a bit unexpected, because what I am calling is sql.DB.Query(). Of course that turns around and calls the Query function in the driver. But the documentation for sql.DB.Query() says you can give parameters to the call. (Which is actually useful for preventing SQL injection.) IMHO, a driver should not deviate from the “contract” established by database/sql.

**Comment by akhilravuri1** [comment]
@axelniedenhoff  yes the go lang document says that user can pass parameter in sql.DB.Query() but db.Query() internally calls prepare and query functions so we don't have a chance to support DirectExecute API from the sql package. So, we decided to support direct Execute API by overriding the existing function.

So, please use db.Prepare and st.Query when you use parameter markers.

Thanks,
Akhil

**Comment by axelniedenhoff** [comment]
Ah OK. Thank you for the explanation!

**Comment by alexcocia** [comment]
Still, IMHO, I don't see it as a proper solution, as you have a method accepting an args parameter, but not using it at all.

Have you considered to provide a solution for parameterized queries? Something as #106  (Just a suggestion, a better solution might surely exist)

**Comment by cvigo** [comment]
Guys perhaps I am missing something but, according to the database/sql documentation [here](https://golang.org/pkg/database/sql/#DB.Query), the function DB.Query accepts arguments as follows:

> func (db *DB) Query(query string, args ...interface{}) (*Rows, error)
> Query executes a query that returns rows, typically a SELECT. The args are for any placeholder parameters in the query.

If this driver is intended to interact with DB2 through the standard database/sql package, it must implement the functions definen in the standard as they are, right?
