### ISSUE TITLE
v0.3.0 unsupported type sql.Out

### ISSUE THREAD

**Issue by Speshl** [ibmdb/go_ibm_db#92]
With v0.3.0 sql.Out does not seem to be supported anymore.  If I downgrade versions back to v0.2.0 code works as expected.

Example Snippet:
	in1 := "Test1"
	var out1, out3 string
	var out2 int32
	sqlString := "CALL TESTSTOREDPROCEDURE(?, ? ,? ,?)"
	rows, err := db2db.Query(sqlString,
		in1,
		sql.Out{Dest: &out1},
		sql.Out{Dest: &out2},
		sql.Out{Dest: &out3})

Error Message with v0.2.0:
sql: converting argument $2 type: unsupported type sql.Out, a struct

**Comment by akhilravuri1** [comment]
Hi @Speshl 

Please use db.Prepare() and st.Query() 
we have changed our db.Query to support DirectExecute function.
So now db.Query does not support parameter markers.

please check #91 for more details.

Thanks,
Akhil

**Comment by Speshl** [comment]
Thanks for the quick response. Was able to get this working with v0.3.0 by switching to the following format.

st, err := db2db.Prepare(sqlString)
rows, err := st.Query(in1,
sql.Out{Dest: &out1},
sql.Out{Dest: &out2},
sql.Out{Dest: &out3})

**Comment by akhilravuri1** [comment]
Thanks
