### ISSUE TITLE
Is a TLS connection possible?

### ISSUE THREAD

**Issue by Vekleon** [ibmdb/go_ibm_db#93]
If so could you walk me through the steps, this would be really appreciated, thank you!

**Comment by Vekleon** [comment]
I'm currently working with a program which passes a tlsConfig from the crypto/tls library with ClientCAs set and InsecureSkipVerify set to true. How would I pass these properties to the DNS?

Thanks!

**Comment by akhilravuri1** [comment]
Hi @Vekleon 

 Secure Database Connection using SSL/TSL - ibm_db supports secure connection to Database Server over SSL same as ODBC/CLI driver. If you have SSL Certificate from server or an CA signed certificate, just use it in connection string as below:
```
connStr = "DATABASE=database;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;UID=username;PWD=passwd;Security=SSL;SSLServerCertificate=<cert.arm_file_path>;";
```

**Comment by akhilravuri1** [comment]
The SSL Certificate file must have .arm extention. Certificate file with .crt or any other extention would not work with SSLServerCertificate keyword.

**Comment by Vekleon** [comment]
I figured out the issue, I wasn't using the correct certificate.

Thanks and sorry for wasting your time.
