### ISSUE TITLE
Error when trying to connect the database with gssplugin

### ISSUE THREAD

**Issue by IdaZ1234567** [ibmdb/go_ibm_db#94]
Hello, 

When we tried to connect the database with GSSPLUGIN security, we keep getting this error:
`
SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "<hostname>".  Communication function detecting the error: "recv".  Protocol specific error code(s): "104", "*", "0".  SQLSTATE=08001
`

As the connection can be created through JCC driver with `"jdbc:db2://<hostname>:<port>/<dbname>:securityMechanism=15;sslConnection=true;apiKey=<apikey>;" `, I wonder whether this error is caused by the possibly wrong way we wrote the connection string or because the bug in clidriver? 

**Attempt 1**:
Connection string
` 
HOSTNAME=<hostname>;DATABASE=<dbname>;PORT=<port>;AUTHENTICATION=GSSPLUGIN;APIKEY=<apikey>
`
Error:
`SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "<hostname>".  Communication function detecting the error: "recv".  Protocol specific error code(s): "104", "*", "0".  SQLSTATE=08001`

**Attempt 2**:
Connection string
` 
HOSTNAME=<hostname>;DATABASE=<dbname>;PORT=<port>;AUTHENTICATION=GSSPLUGIN;SECURITY=SSL;APIKEY=<apikey>
`
Error:
`
SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30082N  Security processing failed with reason "17" ("UNSUPPORTED FUNCTION").  SQLSTATE=08001
`

**Question:**
1. I am also confused about why ssl is failed through clidriver while passed through JCC driver?
2. Is the way I wrote the connection string, especially for apikey right?
3. What could be the possible reasons that causes it only fail in clidriver?

Thanks

**Comment by akhilravuri1** [comment]
Hi @IdaZ1234567  

sorry for the late reply.

Please give uid and pass instead of APIKEY?
If the connection is successful please check your API key with the administrator.
If there is an error please paste the error here.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @IdaZ1234567 

For SSL connection there are many ways:-

You can pass the username and password with security=SSL.
or APIKEY
or APITOKEN.

So if APIKEY or APITOKEN is wrong you will receive reason 17 error.

So please pass username and password instead of APIKEY or APITOKEN to verify.

Thanks,
Akhil

**Comment by abhinandanramesh** [comment]
Thanks Akhilesh. We will try this out.

**Comment by akhilravuri1** [comment]
Hi @abhinandanramesh 

Have you tried?

connection string in Attempt 1 is wrong because security=ssl is missing.

Connection string in Attempt is 2 is right but reason 17 says that APIKEY which you are passing is enabled at the server-side (unsupported function).
Either you have to check the API key with server admin. So meanwhile when we connect using uid and password instead of APIKEY where we can check whether the issue is with the API key or SSL.

Thanks,
Akhil

**Comment by abhinandanramesh** [comment]
Hi @akhilravuri1 We will try it in the morning. The server was down today. We have to host a new one first thing in the morning.

But our cross functional teams reported they had success with username/password log in using go_ibm_db but not with 
API key. While for the same system and same APIKEY, it was successful using APIKEY via jdbc . I will verify their claim tomorrow and keep you posted over what to do if that's the case.

**Comment by IdaZ1234567** [comment]
Hi @akhilravuri1 

These are the results of our testing:

**Attempt 1**: Username and password without Authentication **[Success]**
Connection string:
`HOSTNAME=<hostname>;DATABASE=<dbname>;PORT=<port>;SECURITY=SSL;UID=<username>;PWD=<password>`

**Attempt 2**: APIKey without Authentication  **[Failed]**
Connection string:
`HOSTNAME=<hostname>;DATABASE=<dbname>;PORT=<port>;APIKEY=<apikey>` 
or
`HOSTNAME=<hostname>;DATABASE=<dbname>;PORT=<port>;SECURITY=SSL;APIKEY=<apikey>`
Error:
`SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30082N  Security processing failed with reason "17" ("UNSUPPORTED FUNCTION").  SQLSTATE=08001`

**Attempt 3**:  APIKey with Authentication **[Failed]**
Connection string:
`HOSTNAME=<hostname>;DATABASE=<dbname>;PORT=<port>;AUTHENTICATION=GSSPLUGIN;APIKEY=<apikey>`
Error:
`SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "<host>".  Communication function detecting the error: "recv".  Protocol specific error code(s): "104", "*", "0".  SQLSTATE=08001`

**Questions**:
1. We have double checked the apikey with jdbc, so we guess the apikey is right and valid. But we still got errors with ibm_go_db when we use APIKEY (reason "17") . We wonder what could be the possible reasons?

Thanks!

**Comment by akhilravuri1** [comment]
Hi @IdaZ1234567 

I am investigating the issue. I will update you by the end of the day.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @abhinandanramesh, @IdaZ1234567 

Can you please provide us some information like the clidriver version and to which server you are trying to connect?

Thanks,
Akhil

**Comment by abhinandanramesh** [comment]
@akhilravuri1 The clidriver version is 3.x, the latest version. The server we are trying to connect is a db2 warehouse on cloud instance, where we configure an API key on IBM cloud and then associate the API key onto the warehouse console which houses the db2. It is hosted in a kubernetes pod in a RHEL.

Let me know if you need any more specific details about the server. I will try my best to give without revealing confidentiality.

 @IdaZ1234567 can pass you the java query that works for API key if that helps.

**Comment by akhilravuri1** [comment]
> The clidriver version is 3.x, the latest version.

As of my knowledge, this is not the correct version. The version name should be v11.1 or v11.5 like that.

please run db2level in your command prompt and paste the output.

Thanks,
Akhil

**Comment by IdaZ1234567** [comment]
Hello @akhilravuri1 , the version for cli driver is `v11.1.4.4`

**Comment by akhilravuri1** [comment]
Hi @IdaZ1234567 
Can you paste the out of db2level?

The version is okay..but I wanted to check whether you are using a special build or a normal one.

Thanks,
Akhil

**Comment by abhinandanramesh** [comment]
**@akhilravuri1**

DB21085I  This instance or install (instance name, where applicable: 
"db2inst1") uses "64" bits and DB2 code release "SQL11054" with level 
identifier "0605010F".
Informational tokens are "DB2 v11.5.4.0", "s*********", "DYN************", 
and Fix Pack "0".
Product is installed at "/opt/ibm/db2/V11.5.0.0".

**Comment by akhilravuri1** [comment]
Hi @abhinandanramesh  and @IdaZ1234567 

I am able to reproduce the issue but when I check the log files found that at my server IAM authentication is not set.
So I have mailed the support team to get a server that has  IAM authentication. 
As of now, I am waiting for there response.

Thanks,
Akhil

**Comment by abhinandanramesh** [comment]
Hi @akhilravuri1, any luck? Thank you.

**Comment by akhilravuri1** [comment]
Hi @abhinandanramesh 

As of now what we came to know as that we were using the Bluemix Lite server which doesn't support this type of authentication.
So we are in talks with IBM for a server that supports all types of authentication. 

Sorry for the delay and please give us some time.

Thanks,
Akhil

**Comment by abhinandanramesh** [comment]
Thanks a lot, @akhilravuri1. Take your time. Please let us know, if we could do anything to speed things up.

**Comment by akhilravuri1** [comment]
Hi @abhinandanramesh 

Thanks so much for your comments.

Can you please share us your business requirement? This will help in getting the work done easily.

Thanks,
Akhil

**Comment by abhinandanramesh** [comment]
Hi @akhilravuri1 Sorry for the late response. I'm just trying to connect to a db2 with a plugin authentication mechanism enabled.  In this case, I'm trying to connect to a db2woc using APIKEY.

**Comment by bimalkjha** [comment]
@IdaZ1234567 Your database connection string in Attempt1 was incorrect as `Security=SSL` was missing, while connection string in Attempt2 is correct. 
Then reason behind behind change in JDBC and Go behavior is due use of different encryption libraries. Go and ODBC/CLI driver uses GSKit library for encryption/decryption. It seems, your system has some Db2 client or server installed and hence old version of GSKit library exist in your system PATH environment variable. This old version of GSKit library is getting loaded when you are trying to  connect using clidriver. You need to remove all reference of other GSKit libraries from system environment varialbes, then your connection should work. Thanks.
