### ISSUE TITLE
Unable to compile on AIX - go build command throws errors for ibmdb go driver

### ISSUE THREAD

**Issue by rahul-s-s** [ibmdb/go_ibm_db#95]
`go build` throws errors

/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:14:9: undefined: SQLSMALLINT
/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:15:9: undefined: SQLUSMALLINT
/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:16:9: undefined: SQLUSMALLINT
/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:20:12: undefined: SQLSMALLINT
/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:21:12: undefined: SQLUSMALLINT
/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:22:12: undefined: SQLUSMALLINT
/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:23:12: undefined: SQLUSMALLINT
/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:24:12: undefined: SQLUSMALLINT
/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:25:12: undefined: SQLUSMALLINT
/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:26:12: undefined: SQLUINTEGER
/go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.2.0/api/api.go:26:12: too many errors

- os Version: AIX 7.2.0.0
- cli-driver Version: 0.2
- Db2 Server Version: DB2 v11.1.4.5
- go Version: go version go1.14.2 aix/ppc64
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="ppc64"
GOBIN=""
GOCACHE="/.cache/go-build"
GOENV="/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="ppc64"
GOHOSTOS="aix"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="aix"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/freeware/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/freeware/lib/golang/pkg/tool/aix_ppc64"
GCCGO="gccgo"
GOPPC64="power8"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -maix64 -pthread -mcmodel=large -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build923214632=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

Steps to Reproduce:

1. Install go, ibmdb go driver and project
2. run go build
```
env DB2HOME=/home/tmp/clidriver CGO_CFLAGS=-I/home/tmp/clidriver/include CGO_LDFLAGS=-L/home/tmp/clidriver/lib go build
```

**Comment by akhilravuri1** [comment]
Hi @rahul-s-s 

I will try to reproduce the issue.

I have seen your pullreq also if I reproduce the issue I will use your pullreq to run the tests.

Once all the tests are done I will merge your pull req.

Thanks,
Akhil

**Comment by rahul-s-s** [comment]
Hi @akhilravuri1 - Could you please help on this? There are multiple internal projects are impacted by this issue.

**Comment by akhilravuri1** [comment]
Merged the pull req.
