### ISSUE TITLE
Error when trying to connect the database with gssplugin                           #94 was not addressed, creating another one hoping it would be addressed.

### ISSUE THREAD

**Issue by abhinandanramesh** [ibmdb/go_ibm_db#98]
Hello,

When we tried to connect the database with GSSPLUGIN security, we keep getting this error:
SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "<hostname>". Communication function detecting the error: "recv". Protocol specific error code(s): "104", "*", "0". SQLSTATE=08001

As the connection can be created through JCC driver with "jdbc:db2://<hostname>:<port>/<dbname>:securityMechanism=15;sslConnection=true;apiKey=<apikey>;" , I wonder whether this error is caused by the possibly wrong way we wrote the connection string or because the bug in clidriver?

Attempt 1:
Connection string
HOSTNAME=<hostname>;DATABASE=<dbname>;PORT=<port>;AUTHENTICATION=GSSPLUGIN;APIKEY=<apikey>
Error:
SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "<hostname>". Communication function detecting the error: "recv". Protocol specific error code(s): "104", "*", "0". SQLSTATE=08001

Attempt 2:
Connection string
HOSTNAME=<hostname>;DATABASE=<dbname>;PORT=<port>;AUTHENTICATION=GSSPLUGIN;SECURITY=SSL;APIKEY=<apikey>
Error:
SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30082N Security processing failed with reason "17" ("UNSUPPORTED FUNCTION"). SQLSTATE=08001

Question:

I am also confused about why ssl is failed through clidriver while passed through JDBC driver?
Is the way I wrote the connection string, especially for apikey right?
What could be the possible reasons that causes it only fail in clidriver?
Thanks

**Comment by akhilravuri1** [comment]
closing this as a duplicate
