### ISSUE TITLE
fatal error: sqlcli1.h: No such file or directory

### ISSUE THREAD

**Issue by azunia** [ibmdb/go_ibm_db#99]
please help..
system:
manjaro 

go version:
go version go1.14.4 linux/amd64

export -p:
declare -x CGO_CFLAGS="-I/home/duxingxia/GOPATH/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer/clidriver/include"
declare -x CGO_LDFLAGS="-L/home/duxingxia/GOPATH/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer/clidriver/lib"
declare -x DB2HOME="/home/duxingxia/GOPATH/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer/clidriver"
declare -x LD_LIBRARY_PATH="/home/duxingxia/GOPATH/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer/clidriver/lib"

go env:
GOPATH="/home/duxingxia/GOPATH"
CGO_CFLAGS="-I/home/duxingxia/GOPATH/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/home/duxingxia/GOPATH/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer/clidriver/lib"

**Comment by akhilravuri1** [comment]
Hi @azunia 

This error occurs when env is pointing to the wrong library path or when some files related to sqlcli.h files are missing.
So, please```ls``` in CFLAGS and LDFLAGS env path's and paste the output.

Thanks,
Akhil

**Comment by azunia** [comment]
you mean in folder clidriver? @akhilravuri1 

ls /home/duxingxia/GOPATH/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer/clidriver/include/
sqlca.h  sqlcli1.h  sqlcli.h  sqlda.h  sqlenv.h  sqlext.h  sql.h  sqlstate.h  sqlsystm.h  sqltypes.h  sqlucode.h  sqlunx.h

ls /home/duxingxia/GOPATH/pkg/mod/github.com/ibmdb/go_ibm_db@v0.3.0/installer/clidriver/lib
icc  libdb2clixml4c.so  libdb2clixml4c.so.1  libdb2.so  libdb2.so.1  libDB2xml4c.so  libDB2xml4c.so.58  libDB2xml4c.so.58.0

Thanks.

**Comment by akhilravuri1** [comment]
Hi @azunia 

cli folder looks fine.

Are you installing this in docker?

can you share the steps on how you installed the driver?

Thanks,
Akhil

**Comment by azunia** [comment]
@akhilravuri1  thank you , but  not docker, just my computer
import github.com/ibmdb/go_ibm_db  in goland
go run setup.go   wait for download..
and edit my /etc/profile
all follow the steps in readme.md

maybe i  cant use my own GOPATH?
i am lost....................

**Comment by akhilravuri1** [comment]
Hi @azunia 

I think you are installing the driver using go mod.
Can you please install the driver with go mod...then we can know whether there is a problem while reading the clidriver?

Thanks,
Akhil

**Comment by azunia** [comment]
Thanks, @akhilravuri1 
Finally  
I fixed it by changing my OS to windows and reinstall it..
It worked!
Thanks again!
